### ISSUE TITLE
Making predictions on data outside dataset

### ISSUE THREAD

**Issue by 2c2c** [NicolasHug/Surprise#101]
Hey. Sorry to bother you with a question through an issue.

I'm building a recommendation engine using data I scraped off a website. Someone can go to my site, enter their username for the site I scraped, and get the highest predicted items returned back to them.

I *think* what I've written is correct. I'm taking all the `iids` in my dataset and creating tuples `(userid, iid, 0)` where 0 is just a fake rating so I can call the `test` method. Does this sound about right?

```
# get unique list of all animes in training data
ANIME_LIST = set([d[1] for d in data.raw_ratings])

trainset = data.build_full_trainset()
algo = SVD()
algo.train(trainset)

u = mal.User("2c2c")

user_animes = [ua[1] for ua in u.ratings]

# create 3-tuples of userid, animeid, rating.
# rating is bogus but we need this shape to generate predictions
target = [(u.ratings[0][0], iid, 0) for iid in ANIME_LIST
          if iid not in user_animes]

predictions = algo.test(target)
top_n = get_top_n(predictions, n=10)

for uid, user_ratings in top_n.items():
    print(uid)
    for iid, rating in user_ratings:
        print(iid, rating, f"myanimelist.net/anime/{iid}")
```

Thanks for any help

**Comment by NicolasHug** [comment]
Yes this is the way I would go about it. Any weird results?

**Comment by 2c2c** [comment]
Hey. The results looked fine, but were close enough to mean values that I wanted to make sure I wasn't doing anything dumb :-)

I'm now messing with nearest_neighbor (using knn algo with `user_based: True` in `sim_options`). The workflow is basically the same: user isnt part of the dataset, I want to display nearest neighbors when it gets submitted.

Since nearest_neighbor takes a uid and not a set of predictions it seems like this isn't possible. Am I wrong here? I have code but it's a bit buried, let me know if you need it

**Comment by NicolasHug** [comment]
Yes looking for nearest neighbors can only be done for users (or items) that are on the original dataset.
