### ISSUE TITLE
Can surprise give recommendations on multiple dimensions? like user_location user_language user_height  item_lang item_old item_price

### ISSUE THREAD

**Issue by Roee16** [NicolasHug/Surprise#102]
Hi,
beside the triple: user_id item_id rate.
does surprise can get: more features?
like this: user_location user_language user_height  item_lang item_old item_price
in issue #69 
what does it means " to tweak the data pipeline machinery yourself. "?
how?
where?
10x

**Comment by NicolasHug** [comment]
No, surprise was designed for collaborative filtering scenarios, not content-based recommendation.

> to tweak the data pipeline machinery yourself

This means you'll have to modify the library to suit your needs.

**Comment by Roee16** [comment]
so it does not support "cold start"  cases?

**Comment by NicolasHug** [comment]
If your plan was to handle cold start by using content-based features, then no.
