### ISSUE TITLE
Can I fold in new user's rating into the trainset?

### ISSUE THREAD

**Issue by littlehome-eugene** [NicolasHug/Surprise#103]
Here's what I want:

When a new user rates 20 movies, I'd like to show him movie recommendations.
(I don't want him to wait for another day to see the recommendation)

I'm using KNNBaseLine

It seems to incorporate new user's ratings, I have to do the following.

* rebuild trainset to include the new ratings
* retrain the new trainset (mostly rebuild similarity matrix)
* get top_n predictions for the user.

Is there a more efficient way than the above procedure?

**Comment by NicolasHug** [comment]
No, the way you do it is currently the only way. A long-term objective is to support iterative 'retrain()' (or refit()) methods, but for KNN algorithms I doubt it would change anything, as the whole similarity matrix would need to be recomputed anyway.

**Comment by littlehome-eugene** [comment]
isn't single row/column update sufficient to incorporate new user's rating?

**Comment by NicolasHug** [comment]
In the rating matrix, yes. But in the similarity matrix if you add a rating for user u and item i, you'd need to update the similarities sim(u, v)  for all users v having rated i (considering that you compute similarities between users).

**Comment by littlehome-eugene** [comment]
For item-item similarities, 

if I add rating for user u and item i, 
I need to update the similarities sim(i, j) for all items j that has rating for i.

So the computation cost depends on how popular item i is.

Thank you for clarification.

**Comment by NicolasHug** [comment]
> I need to update the similarities sim(i, j) for all items j that has rating for i.

you'd need to update the similarities sim(i, j) for all items j rated by u.
