### ISSUE TITLE
cannot import name similarities

### ISSUE THREAD

**Issue by srzhu97** [NicolasHug/Surprise#105]
#### Versions

I already used pip to install the surprise package, but when I run the "get started, example" code, it shows that "cannot import name similarities". I am very confused why this happen.
![image](https://user-images.githubusercontent.com/29928433/32423558-0e07c702-c275-11e7-93dc-769c84ae9c3f.png)
![image](https://user-images.githubusercontent.com/29928433/32423564-14784922-c275-11e7-9d57-b3a0a5ef9bba.png)

**Comment by NicolasHug** [comment]
This problem has already occurred a million times, please see past issues. It's because the .c extensions are not compiled. What's the installation log?
