### ISSUE TITLE
ALS addition?

### ISSUE THREAD

**Issue by julioasotodv** [NicolasHug/Surprise#108]
Hi @NicolasHug!

Thank you for Surprise; it is really cool and well written :)

Do you plan to include Alternating Least Squares in the future?

**Comment by NicolasHug** [comment]
Hi, and thanks!
ALS is not a recommendation algorithm, it is a minimization technique - sometimes used for optimizing RS algorithms.
ALS is implemented in surprise for the computation of baseline estimates.

What did you have in mind?

**Comment by julioasotodv** [comment]
Well, just like SVD or NMF, ALS is usually used for matrix decomposition (for collaborative filtering, in order to obtain the latent features). It scales really well for problems that can be solved by dynamic programming

**Comment by NicolasHug** [comment]
Do you have any refs?
As far as I know, ALS does not operate at the same level as SVD or NMF. ALS (a minimization process) can be used for SVD or NMF (two different kinds of matrix factorizations), but that's it.

**Comment by YuyangZhangFTD** [comment]
@NicolasHug I guess he means that ALS can be used to implement NMF or SVD,  just like Spark does.

**Comment by NicolasHug** [comment]
Yes that is also what I thing, but that's not what he says.

**Comment by YuyangZhangFTD** [comment]
Maybe he hopes you can to implement NMF with ALS  @NicolasHug  :P

**Comment by NicolasHug** [comment]
PR are always welcome but I don't intend to work myself on ALS for any MF algorithm. Right now, all MF predictors are optimized with SGD (reference to papers are included in the doc).

**Comment by jasonsalas** [comment]
Hi @NicholasHug,

Do you plan to include some content-based algorithms, as well? The collaborative filtering features are wonderful and a great learning too, but will you tackle TF-IDF and hyvrid approaches, too?

**Comment by NicolasHug** [comment]
As previously mentioned no, I won't.

**Comment by NaveganteX** [comment]
Hello, Nicolas.

I have a doubt regarding the baselines estimates.

So, the equation for minimizing b^*, is the one with the regularization terms, with \lambda_{1}. The papers states that It could be calculated by decoupling b_{i} from b_{u}. I was checking your code and you’re subtracting b_{u} in the b_{i} calculation. Why is that? You claim that it is coded as the paper says. Could you give me a hint whenever it’s possible?

**Comment by NicolasHug** [comment]
https://www.youtube.com/watch?v=gCaOa3W9kM0&t=32m55s
