### ISSUE TITLE
I need to bring more implicit data to SVDpp

### ISSUE THREAD

**Issue by poguez** [NicolasHug/Surprise#109]
Hi, I have been using surprise for a experiment. I need to bring more implicit data to my model. As far as I have seen right now the only implicit data comes from the rated items. So, I would like to code it.

Do you have any suggestions for the implementation?

Do you have in mind how to provide the additional implicit data for the model?

**Comment by NicolasHug** [comment]
I think the easiest way to proceed would be to put the implicit feedback in a separate file, and hack your way into the different methods/classes in the data pipeline: `Dataset`, `Trainset`, `raw_folds()`, `construct_trainset()`, etc...

Depending on your needs this could be done with only a few changes, but if you need all features to be compatible then it might require a bigger refactoring.
