### ISSUE TITLE
How to dump user vector and item vector after training?

### ISSUE THREAD

**Issue by zoumingithub** [NicolasHug/Surprise#11]

**Comment by NicolasHug** [comment]
Care to elaborate please ?

I assume you want to dump the factors vectors when using a matrix factorization-based algorithm? If so, you'll find these numpy arrays in the dump dictionary with:

    dump['algo']['pu']
    dump['algo']['qi']

Note that if you were performing cross validation, these are only the vectors from the **last** fold. If being able to retrieve the vectors from the other folds is useful to you, I may add this as an option.

Nicolas

**Comment by NicolasHug** [comment]
Can I close this issue?
