### ISSUE TITLE
AttributeError: DatasetAutoFolds instance has no attribute 'global_mean'

### ISSUE THREAD

**Issue by windmaple** [NicolasHug/Surprise#112]
I'm literally copying the code in the guide and got the following error:

```
(ml) weiwe@weiwe2:~/Desktop$ python tt.py
Traceback (most recent call last):
  File "tt.py", line 17, in <module>
    algorithm.train(data)
  File "surprise/prediction_algorithms/matrix_factorization.pyx", line 136, in surprise.prediction_algorithms.matrix_factorization.SVD.train
  File "surprise/prediction_algorithms/matrix_factorization.pyx", line 183, in surprise.prediction_algorithms.matrix_factorization.SVD.sgd
AttributeError: DatasetAutoFolds instance has no attribute 'global_mean'
(ml) weiwe@weiwe2:~/Desktop$ ^Cm tt.py
(ml) weiwe@weiwe2:~/Desktop$ cat tt.py
import pandas as pd
from surprise import SVD, Reader, Dataset, KNNBasic
from surprise import evaluate, print_perf
ratings_dict = {'itemID': [1, 1, 1, 2, 2],
                                'userID': [9, 32, 2, 45, 'user_foo'],
                                'rating': [3, 2, 4, 3, 1]}
df = pd.DataFrame(ratings_dict)

# A reader is still needed but only the rating_scale param is requiered.
reader = Reader(rating_scale=(1, 5))
# # The columns must correspond to user id, item id and ratings (in that order).
data = Dataset.load_from_df(df[['userID', 'itemID', 'rating']], reader)
data.split(2)  # data can now be used normally


algorithm = SVD()
algorithm.train(data)

```

It seems split() doesn't do its job

**Comment by windmaple** [comment]
Pls ignore. I've figured it out.

**Comment by sachinpuranik99** [comment]
I am encountering a similar issue.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-f10d7d3a1151> in <module>()
     22 # We can now use this dataset as we please, e.g. calling cross_validate
     23 algo = SVD()
---> 24 algo.fit(data)
     25 
     26 #cross_validate(NormalPredictor(), data, cv=2)

C:\Users\Sachin\Anaconda2\lib\site-packages\surprise\prediction_algorithms\matrix_factorization.pyx in surprise.prediction_algorithms.matrix_factorization.SVD.fit()
    153 
    154         AlgoBase.fit(self, trainset)
--> 155         self.sgd(trainset)
    156 
    157         return self

C:\Users\Sachin\Anaconda2\lib\site-packages\surprise\prediction_algorithms\matrix_factorization.pyx in surprise.prediction_algorithms.matrix_factorization.SVD.sgd()
    202         cdef int u, i, f
    203         cdef double r, err, dot, puf, qif
--> 204         cdef double global_mean = self.trainset.global_mean
    205 
    206         cdef double lr_bu = self.lr_bu
AttributeError: DatasetAutoFolds instance has no attribute 'global_mean'



import pandas as pd

from surprise import NormalPredictor
from surprise import Dataset
from surprise import Reader
from surprise.model_selection import cross_validate
from surprise import SVD


ratings_dict = {'itemID': [1, 1, 1, 2, 2],
                'userID': [9, 32, 2, 45, 'user_foo'],
                'rating': [3, 2, 4, 3, 1]}
df = pd.DataFrame(ratings_dict)

reader = Reader(rating_scale=(1, 5))

data = Dataset.load_from_df(df[['userID', 'itemID', 'rating']], reader)

algo = SVD()
algo.fit(data)
