### ISSUE TITLE
ValueError: could not convert string to float: <None> when importing custom CSV file

### ISSUE THREAD

**Issue by 1MT3J45** [NicolasHug/Surprise#117]
Since I've already visited a [closed topic](https://github.com/NicolasHug/Surprise/issues/41) I'll save your time to point me there. Besides it didn't work for me, hence the issue.
 
#### Description
I am have created my own small dataset which I need to load in df, but Error pops up giving no clue at all. Here it is `ValueError: could not convert string to float:`

My data is in foll. format:
UID, IID, RATING, TIMESTAMP.
These headers are not added in the file, as well as timestamp is numpy generated just to satisfy the input structure of Dataset.load_from_file.
```
3	1	2.8978348799	1
3	2	2.66925567528	1
3	3	2.76930156182	1
3	4	2.89734636809	1
3	5	2.87166587319	1
3	6	2.85160161405	1
3	7	2.97846699093	1
3	8	2.8286242937	1

```
and is \t seperated

#### Steps/Code to Reproduce
So the code that returns me a ValueError is this
```
sim_op = {'name': co_pe, 'user_based': True}
algo = KNNBasic(sim_options=sim_op)

reader = Reader(line_format="user item rating", sep='\t', rating_scale=(1, 5))
df = Dataset.load_from_file('sucl0.csv', reader=reader)

```
#### Expected Results
Since, I'm using PyCharm IDE, when I see u.data loaded successfully the **show variables** displays 
> DatasetAutoFolds: <surprise.dataset.DatasetAutoFolds instance at 0x7f747d216ea8>
so, this is what I expect when I load my file (scul0.csv) as well

#### Actual Results

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-70-16aedd25c9c7>", line 1, in <module>
    df = Dataset.load_from_file('sucl0.csv', reader=reader)
  File "/home/mister-t/.local/lib/python2.7/site-packages/surprise/dataset.py", line 173, in load_from_file
    return DatasetAutoFolds(ratings_file=file_path, reader=reader)
  File "/home/mister-t/.local/lib/python2.7/site-packages/surprise/dataset.py", line 306, in __init__
    self.raw_ratings = self.read_ratings(self.ratings_file)
  File "/home/mister-t/.local/lib/python2.7/site-packages/surprise/dataset.py", line 205, in read_ratings
    itertools.islice(f, self.reader.skip_lines, None)]
  File "/home/mister-t/.local/lib/python2.7/site-packages/surprise/dataset.py", line 455, in parse_line
    return uid, iid, float(r) + self.offset, timestamp
ValueError: could not convert string to float: 
```

#### Versions

```
Linux-4.4.0-103-generic-x86_64-with-Ubuntu-16.04-xenial
('Python', '2.7.12 (default, Nov 20 2017, 18:23:56) \n[GCC 5.4.0 20160609]')
('surprise', '1.0.3')


```

**Comment by NicolasHug** [comment]
Hi,

If you have a timestamp in your csv file, you need to specify it in the `line_format` parameter.

Note: none of the algorithms that are currently implemented can handle timestamps

**Comment by 1MT3J45** [comment]
Hey, but that works just fine with **u.data** from movielens even when it has timestamps to it. So let's say if I mention "timestamp" in line format, will it discard? or I'll have to remove it manually?

**Comment by NicolasHug** [comment]
Indeed, if you don't specify the timestamp in `line_format`, it will be ignored anyway. I forgot about this behavior.

That being said, I can perfectly parse your rating file with either
`reader = Reader(line_format='user item rating', sep='\t')`
or
`reader = Reader(line_format='user item rating timestamp', sep='\t')`.

It would  seem that some lines in your file are not in the correct format (wrong separator, maybe?)

BTW, you don't need to have timestamps in your file: just don't generate them.
