### ISSUE TITLE
Google Cloud App Engine Deploying with numpy

### ISSUE THREAD

**Issue by lee-aaron** [NicolasHug/Surprise#118]
#### Description

I'm wondering if there is a way to disable the requirement for numpy because I'm listing it as a requirement to install on Google Cloud Platform before it installs scikit-surprise.

#### Steps/Code to Reproduce

Clone
https://github.com/lee-aaron/OtakuRecommender

Run
`gcloud app deploy`

#### Expected Results

Nothing wrong on GCP

#### Actual Results

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dn3x_6ag/scikit-surprise/
Step #1: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
Finished Step #1

```

#### Versions

```
Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty
Python 3.5.3 (default, Nov 23 2017, 11:34:05) 
surprise 1.0.4
```
Since I am deploying to GCP, I don't think this is quite necessary although this is what I am using on my laptop.

**Comment by NicolasHug** [comment]
Pip has a `--no-dependencies` switch, but I'm not sure this is what you're looking for.

I have no experience with GCP, but I find it strange that numpy would cause any issue? If you're installing surprise and numpy is already there (and it **has** to be there), it will simply be ignored.

**Comment by lee-aaron** [comment]
The problem is that when I deploy to GCP, it always does a fresh install meaning that it will install all libraries listed in the requirements.txt file. I saw that GCP downloads the other libraries specified in my requirements.txt but does not install them until it has finished downloading all the ones listed. Also, I saw that numpy is listed on GCP but it is only version 1.6.x. I cannot also change the command that GCP runs when I deploy because it will always run pip install -r requirements.txt

**Comment by NicolasHug** [comment]
Unfortunately numpy has to be installed before installing surprise, so you'd need to find a way to launch surprise's installation after that of numpy. I'm sorry but I can't help you more than that as I have no experience with GCP.

**Comment by lee-aaron** [comment]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/flexible/scipy/requirements.txt

^ this is an example where scipy requires numpy to be installed/downloaded beforehand on GCP.

https://github.com/scipy/scipy/blob/master/setup.py

^ and this is their setup.py file. Perhaps there is a way to modify your setup.py to mimic theirs? If this doesn't work, I'll explore other options then. Thanks a lot for looking into it.

**Comment by NicolasHug** [comment]
Sorry but I really don't have the time to look into it.
I remember writing `setup.py` was a huge pain becasue of Cython: Surprise uses Cython, which will compile pyx code to C, and C code is then compiled to extensions (with whatever your compiler is). When compiling C code, some headers from numpy are needed: that's why you need numpy already installed on the machine. I haven't found any simple workardoun than to just impose the numpy dependency **at install time**.

**Comment by reshawn** [comment]
Building upon what Nabeel said, deploying to app engine is a fresh install each time so you can't sequentially install packages like that via the requirements file but you can use a custom runtime environment to do it in one deploy. See here: https://cloud.google.com/appengine/docs/flexible/python/customizing-the-python-runtime

But basically in the app.yaml file you change 'runtime: python' to 'runtime: custom'
and run 'gcloud beta app gen-config --custom' to generate a docker file.
Then before the pip install -r requirements.txt is ran, 
put 'RUN pip install numpy' to ensure numpy is installed before attempting to install surprise
