### ISSUE TITLE
How do i find training error ?

### ISSUE THREAD

**Issue by balajibalasubramanian** [NicolasHug/Surprise#12]
I used SVD  matrix factorization .First I used GridSearch to tune my hyperparameters. Then I trained the algorithm on my whole dataset using  trainset = data.build_full_trainset().
Now I want to find training error on trainset to check if my algorithm is suffering by high bias. How should I do that ? Can you send me the code ?

**Comment by NicolasHug** [comment]
`from surprise import Dataset                                                   
from surprise import SVD                                                       
from surprise import accuracy                                                  
                                                                               
data = Dataset.load_builtin('ml-100k')                                         
trainset = data.build_full_trainset()                                          
algo = SVD()                                                                   
algo.train(trainset)                                                           
                                                                               
testset = data.construct_testset(raw_testset=data.raw_ratings)                 
predictions = algo.test(testset)                                               
rmse = accuracy.rmse(predictions, verbose=True)                                   
`

**Comment by balajibalasubramanian** [comment]
Tysm for your quick response. It worked !!

**Comment by BabulalS** [comment]
Hey @NicolasHug, Is there new implementation added to this.
