### ISSUE TITLE
Is there a error in Reader?

### ISSUE THREAD

**Issue by a6822342** [NicolasHug/Surprise#120]
#### Description

Hello, When I define the sep in my Reader,there is alway use the default split() without my sep which prodefined in my code. So a error occur: 'line_format paramter is incorrect'.

 I think it should be split(sep).
Waiting for your reply. Thanks.

#### Steps/Code to Reproduce

Here is a example. 
reader=Reader(line_format=‘user,item,rating,timestamp’), when I debug into this, here are a line : splitted_format=line_format.spilt() without using my defined sep.
#### Expected Results
splitted_format={'user','item','rating','timestamp'}, it should have four elements in this list rather than only one element in this list such as {'user,item,rating,timestamp'}.
#### Actual Results
 {'user,item,rating,timestamp'}
#### Versions

surprise v 1.0.4

**Comment by NicolasHug** [comment]
The `line_format` parameter should only be space-sperarated. Then you need to specify the `sep`parameter. I'll try to make it clearer.

**Comment by a6822342** [comment]
@NicolasHug ohhh, ok, Thank you.
