### ISSUE TITLE
Built-in datasets causing issues with flask and Elastic Beanstalk

### ISSUE THREAD

**Issue by nabeeltariq2** [NicolasHug/Surprise#125]
Hi Nicholas,

I'm trying to implement surprise in an online recommender systems tool using flask, and to be deployed on AWS Elastic Beanstalk. The package works fine in an offline dev environment, but the built-in datasets module causes significant conflicts with WSGI permissions when deployed to AWS (see error log below). Im actually using my own datasets, so dont really need the built-in module. 

Is it possible to install and deploy surprise without the built-in datasets module? Or is there any other way i can overcome this error. I've tried a lot of solutions (even related to WSGI permissions), but it doesnt help. I also do apologize in advance if the question comes across as extremely basic.

Best,
Nabeel.

------------------------------------
/var/log/httpd/error_log
-------------------------------------
[Thu Jan 18 18:28:08.081827 2018] [:error] [pid 509] [remote 127.0.0.1:212]     from .reader import Reader
[Thu Jan 18 18:28:08.081832 2018] [:error] [pid 509] [remote 127.0.0.1:212]   File "/opt/python/run/venv/local/lib64/python2.7/site-packages/surprise/reader.py", line 6, in <module>
[Thu Jan 18 18:28:08.081852 2018] [:error] [pid 509] [remote 127.0.0.1:212]     from .builtin_datasets import BUILTIN_DATASETS
[Thu Jan 18 18:28:08.081857 2018] [:error] [pid 509] [remote 127.0.0.1:212]   File "/opt/python/run/venv/local/lib64/python2.7/site-packages/surprise/builtin_datasets.py", line 38, in <module>
[Thu Jan 18 18:28:08.081866 2018] [:error] [pid 509] [remote 127.0.0.1:212]     path=join(get_dataset_dir(), 'ml-100k/ml-100k/u.data'),
[Thu Jan 18 18:28:08.081871 2018] [:error] [pid 509] [remote 127.0.0.1:212]   File "/opt/python/run/venv/local/lib64/python2.7/site-packages/surprise/builtin_datasets.py", line 23, in get_dataset_dir
[Thu Jan 18 18:28:08.081879 2018] [:error] [pid 509] [remote 127.0.0.1:212]     os.makedirs(folder)
[Thu Jan 18 18:28:08.081884 2018] [:error] [pid 509] [remote 127.0.0.1:212]   File "/opt/python/run/venv/lib64/python2.7/os.py", line 150, in makedirs
[Thu Jan 18 18:28:08.081894 2018] [:error] [pid 509] [remote 127.0.0.1:212]     makedirs(head, mode)
[Thu Jan 18 18:28:08.081899 2018] [:error] [pid 509] [remote 127.0.0.1:212]   File "/opt/python/run/venv/lib64/python2.7/os.py", line 157, in makedirs
[Thu Jan 18 18:28:08.081906 2018] [:error] [pid 509] [remote 127.0.0.1:212]     mkdir(name, mode)
[Thu Jan 18 18:28:08.081933 2018] [:error] [pid 509] [remote 127.0.0.1:212] OSError: [Errno 13] Permission denied: '/home/wsgi'
[Thu Jan 18 18:29:11.578837 2018] [:error] [pid 509] [remote 172.31.35.59:212] mod_wsgi (pid=509): Target WSGI script '/opt/python/current/app/application.py' cannot be loaded as Python module.
[Thu Jan 18 18:29:11.578864 2018] [:error] [pid 509] [remote 172.31.35.59:212] mod_wsgi (pid=509): Exception occurred processing WSGI script '/opt/python/current/app/application.py'.
[Thu Jan 18 18:29:11.578883 2018] [:error] [pid 509] [remote 172.31.35.59:212] Traceback (most recent call last):
[Thu Jan 18 18:29:11.578907 2018] [:error] [pid 509] [remote 172.31.35.59:212]   File "/opt/python/current/app/application.py", line 15, in <module>
[Thu Jan 18 18:29:11.578927 2018] [:error] [pid 509] [remote 172.31.35.59:212]     import recommender1
[Thu Jan 18 18:29:11.578933 2018] [:error] [pid 509] [remote 172.31.35.59:212]   File "/opt/python/current/app/recommender1.py", line 9, in <module>
[Thu Jan 18 18:29:11.578943 2018] [:error] [pid 509] [remote 172.31.35.59:212]     from surprise import evaluate, print_perf, dump, Reader, Dataset
[Thu Jan 18 18:29:11.578948 2018] [:error] [pid 509] [remote 172.31.35.59:212]   File "/opt/python/run/venv/local/lib64/python2.7/site-packages/surprise/__init__.py", line 19, in <module>
[Thu Jan 18 18:29:11.578959 2018] [:error] [pid 509] [remote 172.31.35.59:212]     from .dataset import Dataset
[Thu Jan 18 18:29:11.578964 2018] [:error] [pid 509] [remote 172.31.35.59:212]   File "/opt/python/run/venv/local/lib64/python2.7/site-packages/surprise/dataset.py", line 40, in <module>
[Thu Jan 18 18:29:11.579062 2018] [:error] [pid 509] [remote 172.31.35.59:212]     from .reader import Reader
[Thu Jan 18 18:29:11.579071 2018] [:error] [pid 509] [remote 172.31.35.59:212]   File "/opt/python/run/venv/local/lib64/python2.7/site-packages/surprise/reader.py", line 6, in <module>
[Thu Jan 18 18:29:11.579080 2018] [:error] [pid 509] [remote 172.31.35.59:212]     from .builtin_datasets import BUILTIN_DATASETS
[Thu Jan 18 18:29:11.579086 2018] [:error] [pid 509] [remote 172.31.35.59:212]   File "/opt/python/run/venv/local/lib64/python2.7/site-packages/surprise/builtin_datasets.py", line 38, in <module>
[Thu Jan 18 18:29:11.579095 2018] [:error] [pid 509] [remote 172.31.35.59:212]     path=join(get_dataset_dir(), 'ml-100k/ml-100k/u.data'),
[Thu Jan 18 18:29:11.579100 2018] [:error] [pid 509] [remote 172.31.35.59:212]   File "/opt/python/run/venv/local/lib64/python2.7/site-packages/surprise/builtin_datasets.py", line 23, in get_dataset_dir
[Thu Jan 18 18:29:11.579108 2018] [:error] [pid 509] [remote 172.31.35.59:212]     os.makedirs(folder)
[Thu Jan 18 18:29:11.579113 2018] [:error] [pid 509] [remote 172.31.35.59:212]   File "/opt/python/run/venv/lib64/python2.7/os.py", line 150, in makedirs
[Thu Jan 18 18:29:11.579123 2018] [:error] [pid 509] [remote 172.31.35.59:212]     makedirs(head, mode)
[Thu Jan 18 18:29:11.579127 2018] [:error] [pid 509] [remote 172.31.35.59:212]   File "/opt/python/run/venv/lib64/python2.7/os.py", line 157, in makedirs
[Thu Jan 18 18:29:11.579135 2018] [:error] [pid 509] [remote 172.31.35.59:212]     mkdir(name, mode)
[Thu Jan 18 18:29:11.579151 2018] [:error] [pid 509] [remote 172.31.35.59:212] OSError: [Errno 13] Permission denied: '/home/wsgi'
[Thu Jan 18 18:29:12.280204 2018] [:error] [pid 509] [remote 172.31.35.59:212] mod_wsgi (pid=509): Target WSGI script '/opt/python/current/app/application.py' cannot be loaded as Python module.
[Thu Jan 18 18:29:12.280227 2018] [:error] [pid 509] [remote 172.31.35.59:212] mod_wsgi (pid=509): Exception occurred processing WSGI script '/opt/python/current/app/application.py'.

**Comment by NicolasHug** [comment]
Hi,
It looks like the error is due to [get_dataset_dir()](https://github.com/NicolasHug/Surprise/blob/master/surprise/builtin_datasets.py#L14) which tries to create a folder in the home directory.
Is there a way for you to set the environment variable `SURPRISE_DATA_FOLDER` to a directory where you would have write right?
If not, I'm afraid you would have to revert to version 1.0.4...

I'll try to find a fix that prevents from creating the data directory unless explicitely asked for, but that would only be available in the next releases.

>  it possible to install and deploy surprise without the built-in datasets module?

Yes, you could clone the repo, remove this `get_dataset_dir()` function and all of its calls, and install your own version from there.

Hope this helps!
Nicolas

**Comment by nabeeltariq2** [comment]
Hi Nicholas,
Thanks for these options! I'll try to implement them, see what works and get back to you on what does.

Best,
Nabeel

**Comment by nabeeltariq2** [comment]
Hi Nicholas,

I managed to get it working by reverting to version 1.0.4. Are there any significant differences between the current version (1.0.5) and 1.0.4? I cant seem to find the changelog. Especially, the algorithm part is extremely important to my project, and if there are any major differences to those, i may need to go back to the current version.

**Comment by NicolasHug** [comment]
You can find the [change log here](https://github.com/NicolasHug/Surprise/blob/master/CHANGELOG.md).
Major difference is the introduction to cross-validation iterators, algorithms haven't change except for some initialization process in the MF algorithms.

**Comment by nabeeltariq2** [comment]
Thanks!
