### ISSUE TITLE
A couple of questions about metrics and benchmarks

### ISSUE THREAD

**Issue by francasino** [NicolasHug/Surprise#126]
#### Description

Hi guys, 

Thank you for your efforts, you did a good job there. I have one comment and one question. 

1. The comment.
 I managed to add more accuracy metrics to the accuracy.py doc. However, in the case of functions that have two outpus, like in the case of precision and recall, when I want to use the crossover validation, the program fails, because it is prepared to receive only one value. Could you change that in an easy way ? I mean, to let crossover validation receive n >1 values from a function and print that n values it as if they were different?  What I have now is the precision and recall function repeated with a different name, and one gives the precision and the other the recall. Therefore, I have to call i twice, which is no efficient

2. The question / doubt.

I have been reading about adding new datasets. All the examples are about adding a kind of data and then calling the crossvalidate method with an algorithm. In my case, what I have are datasets with methods already applied. So that the dataset has been already processed and then what I want is to know which is the accuracy. How could I do that ? 

For example, I have the movielens 100k with KNN (or k-means, or whatever) already applied on it, so that it is fulfilled with values. How can I compare the accuracy of such dataset with the raw movielens 100k ?  

Also... did you implement a reader for csv files which is compliant with your system ? 

Sorry that I have no high skills in python :)

**Comment by NicolasHug** [comment]
Hi,

1. You'll need to have a function calculating recall, and another calculating precision. It may not be completely optimal but computing metrics is usually not significant compared to training time.
2. I guess the easiest way is to parse your dataset, create a list of `Prediction` object (see the docs) and feed it to one of your metric functions.

Nicolas

**Comment by francasino** [comment]
Nicolas,

Thank you for the fast response. 

1. ok ! 

2. Could you provide some example or be more concrete please ? I checked the docs but it is not fully clear for me. My intention is to use the crossvalidator with such datasets, so what I would want to do is something like ... 

From file examples/load_from_dataframe.py¶
import pandas as pd

from surprise import NormalPredictor
from surprise import Dataset
from surprise import Reader
from surprise.model_selection import cross_validate

data = read movielens100k of your system.
data_test = Dataset.load_from_CSV file

# We can now use this dataset as we please, e.g. calling cross_validate
cross_validate(data_test, data, cv=5.....)

So that instead of using a predictor, use the data_test. 

Thx

**Comment by NicolasHug** [comment]
If you want to be able to run cross-validation procedures then I think the more versatile way would be to create a dummy prediction algorithm which is omniscient and which returns the correct rating. That is, when you call `algo.estimate(u, i)`, it returns the ground truth rating of `u` for `i`.

**Comment by francasino** [comment]
Ok I understand. Thanks again
