### ISSUE TITLE
pearson similarity don't compute correctly for float-valued ratings

### ISSUE THREAD

**Issue by ODemidenko** [NicolasHug/Surprise#127]
I have user ratings with values in a range from 1 to 5, but there are also 4.5 scores as well.
Upon loading a dataset I specify that ratings are in [1,5] range
When I tried to compute a pearson similarity matrix (KNNBasic alg) - it returns wrong correlations, for most of the items. It seems like the problem is due to the floating point raings, as I found in similaritites.pearson that all matrices, participating in the calculation, are allocated of type int.

Of course, I can force my rating into a [1;10] scale, use current code, and then squeeze back the result into [1,5] range. But shouldn't float values be rather supported by the lib? If not (say, for the sake of lower memory consumption during calculations) - at least I expect it to check the dataset and inform user that float-typed ratings are present and they won't be handled correctly.

**Comment by NicolasHug** [comment]
Wow, indeed the ratings should be `double`!
I checked and all other similarity metrics have the same issue, except for `pearson_baseline`.
Do you want to submit a PR? Else I'll do it., no worries

Thanks a lot for catching this!

**Comment by ODemidenko** [comment]
I'll be glad to contribute, in a couple of days

**Comment by NicolasHug** [comment]
Awesome, I'll be waiting for your PR

**Comment by ODemidenko** [comment]
Sorry, I can't do it:
 I don't understand the reason, but simply changing types in np.arrays to np.double (and np.double_t in corresponding cdefs) - doesn't help. It doesn't influence the result of the function. And I have no idea what else to check.

**Comment by NicolasHug** [comment]
I think that's because you're not recompiling Cython code: after you modify a .pyx file you need to run cython.
The easiest way (for me) is to run `pip install -e .` again.

**Comment by ODemidenko** [comment]
Thanks, I found the problem. I will try to finish this tomorrow
