### ISSUE TITLE
Serializing recommenders

### ISSUE THREAD

**Issue by z1mvader** [NicolasHug/Surprise#13]
It is not clear to me if is possible to serialize a recommender for later use using the `surprise.dump.dump` function, if it is the case I would change the documentation to be more explicit about this

**Comment by NicolasHug** [comment]
Hi,

Indeed the `dump` function cannot be used for serialization of the algorithms. It only dumps some relevant information such as the parameters of the algorithm and some of its attributes, but what's dumped is not a proper algorithm object.

I'll change the doc to make it clearer. Would such a feature be useful for you? If you need it I will try to add it in the next release.

Thanks,
Nicolas

**Comment by z1mvader** [comment]
Yeah! I'd like to train a model and then store it for later use, even if i replace the attributes of another algorithm object with the ones serialized it wont be enough?

**Comment by NicolasHug** [comment]
You're right this should actually work.
What is dumped is the `__dict__` attribute of the algorithm object so replacing this field could do the job.

Can you try to do something like this and see how it goes?

    algo = SVD() # or the class that you used
    dump_obj = pickle.load(open('./dump_file', 'rb'))
    algo.__dict__ = dump_obj['algo']

**Comment by z1mvader** [comment]
let's check it ouf, if you are ok with that it could be included on the dump submodule?

**Comment by NicolasHug** [comment]
Yes definitely. I've tested in on a small example and it seems to work.

We could add a function `load_algo` in the dump module that takes the `dump_obj` as parameter and that would return a fully instantiated algorithm object. We would probably need to use [this](http://stackoverflow.com/questions/4821104/python-dynamic-instantiation-from-string-name-of-a-class-in-dynamically-imported) with the `dump_obj['algo'].name` attribute to instantiate the correct algorithm class.

I think  the `predictions` parameter of the `dump` function should optional as well.

Do you want to submit a pull request? Or else I'll do it, no problem.

**Comment by z1mvader** [comment]
let me do it then

**Comment by NicolasHug** [comment]
Cool, don't forget to read the contribution [guidelines](https://github.com/NicolasHug/Surprise/blob/master/CONTRIBUTING.md) ;)
