### ISSUE TITLE
Suppress automatic print

### ISSUE THREAD

**Issue by nabeeltariq2** [NicolasHug/Surprise#133]
Hi Nicholas,

Is there a way to suppress output for rmse and mae metrics? Whenever, i run them they automatically print. I'm using surprise in a web app and printing during python scripts throws up IOerrors and breaks the app. 

This, is there a way not to print any output for surprise functions?

Best,
Nabeel.

**Comment by NicolasHug** [comment]
Have you tried the verbose parameters?

**Comment by NicolasHug** [comment]
Did it work?

**Comment by nabeeltariq2** [comment]
I did try to solve it using the solution mentioned on https://stackoverflow.com/questions/8391411/suppress-calls-to-print-python

Ddnt work, but i actually managed to get around the issue for now by upgrading the server. Not sure if this is a viable solution, but may have to do for now. 

Thanks for your help!
