### ISSUE TITLE
AlgoBase.predict() returns the same value for all uid and iid values

### ISSUE THREAD

**Issue by skurzhanskyi** [NicolasHug/Surprise#140]
#### Description

I tried to test Matrix Factorization-based algorithms on my own dataset and admitted that `AlgoBase.predict()` returns the same value for all `uid` and `iid` values. Then I tested on default dataset and the result was the same. Maybe, there's a mistake in my code, but I can't get it at the moment.

#### Steps/Code to Reproduce

```python
from surprise import SVD
from surprise import Dataset


data = Dataset.load_builtin('ml-100k')
algo = SVD()
trainset = data.build_full_trainset()
algo.fit(trainset)

users_ids = trainset.all_users()
items_ids = trainset.all_items()

ratings = []
for i in range(min(100, len(users_ids))):
    for j in range(min(100, len(items_ids))):
        ratings.append(algo.predict(users_ids[i], items_ids[j]).est)
print len(set(ratings))
```
#### Expected Results
```10000``` or smth less (not 1)
#### Actual Results
```1```
#### Versions

Darwin-16.7.0-x86_64-i386-64bit
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
surprise 1.0.5

**Comment by NicolasHug** [comment]
That's because `predict()` expects raw ids but `trainset.all_users/items()` returns inner ids. Please see [this note](http://surprise.readthedocs.io/en/stable/FAQ.html#what-are-raw-and-inner-ids).

**Comment by skurzhanskyi** [comment]
Thank you for your swift answer!
I really didn't note that. But, actually, firstly I tried to use data from my file, but I get something like "this item not in unknown". Unfortunately, I am not on the work computer at the moment. Will it be OK if I describe my problem in detail on Monday?

**Comment by NicolasHug** [comment]
Yes, if you tried but didn't find a solution on your own feel free to ask (of course please do some research before:) )

**Comment by skurzhanskyi** [comment]
You, actually, were right. The problem was with my dataset. There were non-ASCII characters in items, so unicode and string variables differed. Using `to_raw_iid` you get string, but filed in DataFrame is unicode. So, if you check their equality, you'll get True. But the result of predict depends on the type.

Thank for your help anyway. The task may be closed. But I think converting to string in predict would be great.

**Comment by elaine-peiru** [comment]
@skurzhanskyi I have the same problem when I using my own dataset, can you specify how you solve this problem? I also go all the same estimate rating all the time. I understand the raw id and inner id in the note, but I have no idea where I should modify in the origin code. Would be great if you can share your experience. Thank you :)

**Comment by elaine-peiru** [comment]
@skurzhanskyi thanks! the question was solved by remove the str().

**Comment by alpalalpal** [comment]
Solved this issue by convert ids from string to integer or float

**Comment by oyyablokov** [comment]
I had the same issue, but the problem turned out to be the fact that the matrix I used to fit the model with had NaNs. I fixed this and it worked.

**Comment by BabulalS** [comment]
I'm also facing the same issue. I am using surprise package for FMCG dataset for building recommendation engine and see all the users and items have same **r_ui** and max  provided **est** for different **uid** and **iid**, and I do not clearly get the above solution. 
Initially I had string names but then created id's and there are no NULL values too. 
Please do help me here. I am not able to attach screen shot and hence pasting the output.

`Prediction(uid=73481, iid=90525, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=73481, iid=90538, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=73481, iid=90561, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=73481, iid=90526, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=73481, iid=90449, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=73481, iid=36941, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=73481, iid=70326, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=73481, iid=90451, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=73481, iid=70319, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=74952, iid=305, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=74952, iid=1545, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=74952, iid=1785, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=74952, iid=17816, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=74952, iid=24702, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=74952, iid=29210, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=74952, iid=29342, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=74952, iid=29380, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=74952, iid=29463, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),
 Prediction(uid=74952, iid=36656, r_ui=65.81704786294596, est=10, details={'was_impossible': False}),`
