### ISSUE TITLE
joblib issue

### ISSUE THREAD

**Issue by joerngrahl** [NicolasHug/Surprise#142]
#### Description

I cannot get surprise to run, because of a problem with using multiple cores. I searched the documentation, the web, and stackoverflow. I already use the` "if __name__=="__main__"` trick, it does not help. 

#### Steps/Code to Reproduce
```
import surprise 
from surprise import Dataset
from surprise.model_selection import cross_validate


def main():
    data = Dataset.load_builtin('ml-100k')
    # Use the famous SVD algorithm.
    algo = surprise.SVD
    # Run 5-fold cross-validation and print results.
    cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5,  verbose=True)


if __name__ == "__main__":
    main()

```
#### Expected Results

```
Evaluating RMSE, MAE of algorithm SVD on 5 split(s).                       
                                                                      
            Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std            
RMSE        0.9311  0.9370  0.9320  0.9317  0.9391  0.9342  0.0032         
MAE         0.7350  0.7375  0.7341  0.7342  0.7375  0.7357  0.0015         
Fit time    6.53    7.11    7.23    7.15    3.99    6.40    1.23           
Test time   0.26    0.26    0.25    0.15    0.13    0.21    0.06 
```

#### Actual Results

> ImportError: [joblib] Attempting to do parallel computing without protecting your import on a system that does not support forking. To use parallel-computing in a script, you must protect your main loop using "if __name__ == '__main__'". Please see the joblib documentation on Parallel for more information

#### Versions

Windows-7-6.1.7601-SP1
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
surprise 1.0.5

**Comment by NicolasHug** [comment]
Thanks for issuing this.                                                       
                                                                               
It seems related to #139, have you tried to set the `n_jobs` parameter to 1?

**Comment by joerngrahl** [comment]
Thank you for your quick reply!
I did this now. The result is the following error. A parameter seems to be missing once I override the default for `n_jobs`. Here is the message:

>   File "C:\Users\grahl\Anaconda3\lib\site-packages\surprise\model_selection\validation.py", line 164, in fit_and_score
>     algo.fit(trainset)
> 
>   File "surprise/prediction_algorithms/matrix_factorization.pyx", line 152, in surprise.prediction_algorithms.matrix_factorization.SVD.fit
> 
> TypeError: **fit() takes exactly 2 positional arguments (1 given)**

**Comment by NicolasHug** [comment]
>algo = surprise.SVD

This needs to be `algo = surprise.SVD()`

**Comment by NicolasHug** [comment]
BTW I doubt this is related but *maybe* now joblib would work fine (`n_jobs=-1`)?

**Comment by NicolasHug** [comment]
Awesome :)

That's good news: given issue  #139 I feared that there was an inherent problem with Windows and joblib, but that's apparently not the case.
