### ISSUE TITLE
Predicting ratings for out-of-dataset users?

### ISSUE THREAD

**Issue by ddbourgin** [NicolasHug/Surprise#144]
I'm interested in using a (trained) recommendation model to predict ratings for a user who did not exist in either the train or test sets. Something akin to: after training, some new user comes along and rates items [...] with ratings [...], and now I want to query my trained recommender to return the projected ratings for this user on all other items in the dataset. 

I tried looking in the documentation for such a use-case, but was unable to find one. Is this easily done?

**Comment by ddbourgin** [comment]
Oops, I see this has been addressed in issue #113. Apologies and closing.

**Comment by Rabrg** [comment]
@NicolasHug Has there been any update on incremental learning, like an ETA?

**Comment by NicolasHug** [comment]
Sorry, what's an ETA?

And no, nothing new about incremental learning. It's still a long-term objective but I can't commit to any deadline.

**Comment by Rabrg** [comment]
Sorry, it's an abbreviation for Estimated Time of Arrival.

And okay, thanks for the quick response.
