### ISSUE TITLE
No verbose option for algo.fit()

### ISSUE THREAD

**Issue by Oreki47** [NicolasHug/Surprise#145]
So I am customizing the training flow, and found that their is no verbose option for algo.fit(), i.e., it has to print out several lines, which is a bit disrupting.

Interestingly, when the fit_and_score method calls on algo.fit(), it does not print out anything.

**Comment by NicolasHug** [comment]
Could you please provide a sample code to reproduce the results?

>Interestingly, when the fit_and_score method calls on algo.fit(), it does not print out anything.

Yes that's because joblib catches all the ouput I think.

**Comment by Oreki47** [comment]
```
data = Dataset.load_builtin(name='ml-100k')
sim_options = {'name': 'pearson'}
algo = KNNBaseline(k=18, sim_options=sim_options)

trn, tst = train_test_split(data, test_size=0.1)
algo.fit(trn)
```
This gives the following output:
```
Estimating biases using als...
Computing the pearson similarity matrix...
Done computing similarity matrix.
```

The behavior is expected, since KNNBaseline.fit() calls compute_baseline() which print out the 1st line and compute_similarities() which print out the 2nd and 3rd. This is almost an none issue when we call fit() once or twice. But if we are doing cross_validation with variation on k, it would be printing out a hell lot. So I am asking to see if there is a way to work around or could be added in the future.

https://github.com/NicolasHug/Surprise/blob/58f35085a460e51408f9440a332abb385ce25f80/surprise/prediction_algorithms/knns.py#L265-L270

**Comment by NicolasHug** [comment]
Ok yeah so that comes from the `compute_baselines` and `compute_similarity` methods. These prints should be optional indeed -- but the option should probably be in the `__init__` method rather tha in `fit`. I'll fix this for the next release, thanks for issuing this.
