### ISSUE TITLE
Unable to install Surprise on Windows 10

### ISSUE THREAD

**Issue by harshalwavre7** [NicolasHug/Surprise#147]
![erro](https://user-images.githubusercontent.com/26541367/36728634-741988f2-1be7-11e8-8460-a4a8f5993238.PNG)

As the system already contains the Redistributable file already installed.
Windows 10 x64
numpy and cython already installed

**Comment by NicolasHug** [comment]
Are you installing with pip, conda, something else?
Looks like the error message tells you exactly what you need: you have to install Visual C++.

**Comment by harshalwavre7** [comment]
I have tried with pip, conda and also cloning the git still getting the same error mentioned above

**Comment by NicolasHug** [comment]
So have you installed Visual C++? By installing with conda you should not have to do it though.

**Comment by harshalwavre7** [comment]
Yes I have 
And when trying with conda getting 
Error:
"CondaIndexError: Invalid index file: https://conda.anaconda.org/conda-forge/win-64/repodata.json: Expecting value: line 1 column 1 (char 0)"

**Comment by harshalwavre7** [comment]
Output of the above Code Snippet :
Windows-10-10.0.14393-SP0
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]

###########
Command  : pip install scikit-surprise
Error log :
(C:\Users\harshal\AppData\Local\Continuum\Anaconda3) C:\Users\harshal>pip install scikit-surprise
Collecting scikit-surprise
  Using cached scikit-surprise-1.0.5.tar.gz
Requirement already satisfied: numpy>=1.11.2 in c:\users\harshal\appdata\local\continuum\anaconda3\lib\site-packages (from scikit-surprise)
Requirement already satisfied: six>=1.10.0 in c:\users\harshal\appdata\local\continuum\anaconda3\lib\site-packages (from scikit-surprise)
Requirement already satisfied: joblib>=0.11 in c:\users\harshal\appdata\roaming\python\python36\site-packages (from scikit-surprise)
Building wheels for collected packages: scikit-surprise
  Running setup.py bdist_wheel for scikit-surprise ... error
  Complete output from command C:\Users\harshal\AppData\Local\Continuum\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\harshal\\AppData\\Local\\Temp\\pip-build-se2_iqey\\scikit-surprise\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\harshal\AppData\Local\Temp\tmpu4lw8zkipip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\surprise
  copying surprise\accuracy.py -> build\lib.win-amd64-3.6\surprise
  copying surprise\builtin_datasets.py -> build\lib.win-amd64-3.6\surprise
  copying surprise\dataset.py -> build\lib.win-amd64-3.6\surprise
  copying surprise\dump.py -> build\lib.win-amd64-3.6\surprise
  copying surprise\evaluate.py -> build\lib.win-amd64-3.6\surprise
  copying surprise\reader.py -> build\lib.win-amd64-3.6\surprise
  copying surprise\trainset.py -> build\lib.win-amd64-3.6\surprise
  copying surprise\utils.py -> build\lib.win-amd64-3.6\surprise
  copying surprise\__init__.py -> build\lib.win-amd64-3.6\surprise
  copying surprise\__main__.py -> build\lib.win-amd64-3.6\surprise
  creating build\lib.win-amd64-3.6\surprise\model_selection
  copying surprise\model_selection\search.py -> build\lib.win-amd64-3.6\surprise\model_selection
  copying surprise\model_selection\split.py -> build\lib.win-amd64-3.6\surprise\model_selection
  copying surprise\model_selection\validation.py -> build\lib.win-amd64-3.6\surprise\model_selection
  copying surprise\model_selection\__init__.py -> build\lib.win-amd64-3.6\surprise\model_selection
  creating build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\algo_base.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\baseline_only.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\knns.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\predictions.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\random_pred.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\__init__.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  running egg_info
  writing scikit_surprise.egg-info\PKG-INFO
  writing dependency_links to scikit_surprise.egg-info\dependency_links.txt
  writing entry points to scikit_surprise.egg-info\entry_points.txt
  writing requirements to scikit_surprise.egg-info\requires.txt
  writing top-level names to scikit_surprise.egg-info\top_level.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'scikit_surprise.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'scikit_surprise.egg-info\SOURCES.txt'
  copying surprise\similarities.c -> build\lib.win-amd64-3.6\surprise
  copying surprise\similarities.pyx -> build\lib.win-amd64-3.6\surprise
  copying surprise\prediction_algorithms\co_clustering.c -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\matrix_factorization.c -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\optimize_baselines.c -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\slope_one.c -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\co_clustering.pyx -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\matrix_factorization.pyx -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\optimize_baselines.pyx -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\slope_one.pyx -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
  running build_ext
  building 'surprise.similarities' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for scikit-surprise
  Running setup.py clean for scikit-surprise
Failed to build scikit-surprise
Installing collected packages: scikit-surprise
  Running setup.py install for scikit-surprise ... error
    Complete output from command C:\Users\harshal\AppData\Local\Continuum\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\harshal\\AppData\\Local\\Temp\\pip-build-se2_iqey\\scikit-surprise\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\harshal\AppData\Local\Temp\pip-4560euls-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\surprise
    copying surprise\accuracy.py -> build\lib.win-amd64-3.6\surprise
    copying surprise\builtin_datasets.py -> build\lib.win-amd64-3.6\surprise
    copying surprise\dataset.py -> build\lib.win-amd64-3.6\surprise
    copying surprise\dump.py -> build\lib.win-amd64-3.6\surprise
    copying surprise\evaluate.py -> build\lib.win-amd64-3.6\surprise
    copying surprise\reader.py -> build\lib.win-amd64-3.6\surprise
    copying surprise\trainset.py -> build\lib.win-amd64-3.6\surprise
    copying surprise\utils.py -> build\lib.win-amd64-3.6\surprise
    copying surprise\__init__.py -> build\lib.win-amd64-3.6\surprise
    copying surprise\__main__.py -> build\lib.win-amd64-3.6\surprise
    creating build\lib.win-amd64-3.6\surprise\model_selection
    copying surprise\model_selection\search.py -> build\lib.win-amd64-3.6\surprise\model_selection
    copying surprise\model_selection\split.py -> build\lib.win-amd64-3.6\surprise\model_selection
    copying surprise\model_selection\validation.py -> build\lib.win-amd64-3.6\surprise\model_selection
    copying surprise\model_selection\__init__.py -> build\lib.win-amd64-3.6\surprise\model_selection
    creating build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\algo_base.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\baseline_only.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\knns.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\predictions.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\random_pred.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\__init__.py -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    running egg_info
    writing scikit_surprise.egg-info\PKG-INFO
    writing dependency_links to scikit_surprise.egg-info\dependency_links.txt
    writing entry points to scikit_surprise.egg-info\entry_points.txt
    writing requirements to scikit_surprise.egg-info\requires.txt
    writing top-level names to scikit_surprise.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'scikit_surprise.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'scikit_surprise.egg-info\SOURCES.txt'
    copying surprise\similarities.c -> build\lib.win-amd64-3.6\surprise
    copying surprise\similarities.pyx -> build\lib.win-amd64-3.6\surprise
    copying surprise\prediction_algorithms\co_clustering.c -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\matrix_factorization.c -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\optimize_baselines.c -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\slope_one.c -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\co_clustering.pyx -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\matrix_factorization.pyx -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\optimize_baselines.pyx -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\slope_one.pyx -> build\lib.win-amd64-3.6\surprise\prediction_algorithms
    running build_ext
    building 'surprise.similarities' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

Command "C:\Users\harshal\AppData\Local\Continuum\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\harshal\\AppData\\Local\\Temp\\pip-build-se2_iqey\\scikit-surprise\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\harshal\AppData\Local\Temp\pip-4560euls-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\harshal\AppData\Local\Temp\pip-build-se2_iqey\scikit-surprise\ 

######

Command : conda install -c conda-forge scikit-surprise

Error log:
(C:\Users\harshal\AppData\Local\Continuum\Anaconda3) C:\Users\harshal>conda install -c conda-forge scikit-surprise
Fetching package metadata ...
CondaIndexError: Invalid index file: https://conda.anaconda.org/conda-forge/win-64/repodata.json: Expecting value: line 1 column 1 (char 0)

**Comment by NicolasHug** [comment]
Looks like you either haven't installed visual C++ as requiered, or have incorrect settings with conda. Have you tried to Google the `CondaIndexError: Invalid index file` error?

**Comment by NicolasHug** [comment]
Also (again): have you looked at related past issues?

**Comment by harshalwavre7** [comment]
Hi Nicolas Thanks for the prompt replies 
The Error was resolved after installing the 
Build Tools for Visual Studio 2017(and not the Build Tools for Visual Studio 2015)

after the installation of Build Tools for Visual Studio 2017
another the error was due to .dll files missing which can be resolved from the below mentioned 
URL : ( https://stackoverflow.com/questions/43858836/python-installing-clarifai-vs14-0-link-exe-failed-with-exit-status-1158)
