### ISSUE TITLE
Inconsistency in train-test split

### ISSUE THREAD

**Issue by himanData** [NicolasHug/Surprise#148]
#### Description

Hello,
I just started playing with Surprise and I think it has the potential to be great. So far I found one issue. I will keep checking if I find more.
So in train-test split method, it returns two sets: trainset and testset:

trainset, testset = train_test_split(data, test_size=.25)

However, these two objects are not the same type. Is there a reason for that?
Trainset is an instance while testset is a list.

Thansks

**Comment by NicolasHug** [comment]
That's just a matter of design.
The trainset is an object which contains more information than just a list of ratings (see the docs for details). A testset does not need to have a proper class for now, it can just be a list of ratings.

**Comment by himanData** [comment]
Thank you very much
