### ISSUE TITLE
Using predefined train and test set

### ISSUE THREAD

**Issue by himanData** [NicolasHug/Surprise#149]
#### Description

Hello,
Reading your documentation I see that there is an option for using predefined train and test folds using cross-validation. I want to use one train set and one test set that both are already created. This is how I have done it using your library:

folds_files = [(train_file,test_file)]
data = Dataset.load_from_folds(folds_files, reader=reader)
pkf = PredefinedKFold()
for trainset, testset in pkf.split(data):
    algo.fit(trainset)
    predictions= algo.test(testset)

Could you please tell me if there is a better way to do this task using Surprise so that I don't have to use cross-validation with 1 fold?

Thanks

**Comment by NicolasHug** [comment]
Something like 
`trainset, testset = next(pkf.split(data))`
should do the trick  think

**Comment by himanData** [comment]
So I guess I still need to use the pkf.plit(data) and assume I have one fold. 

Thanks a lot
