### ISSUE TITLE
No (float) used for the divisions 

### ISSUE THREAD

**Issue by himanData** [NicolasHug/Surprise#150]
#### Description
Hello
I just realized in many divisions the float() has not been used to avoid getting the zero as the result. For example, in Python, 2/3 would give us 0 so we have to use float(2)/3 to get 0.6666. I only checked the similarities.pyx file but there could be the same issue in other files as well. 

```
sim[xi, xj] = prods[xi, xj] / (np.sqrt(sq_diff_i[xi, xj] *
                                                       sq_diff_j[xi, xj]))
                # the shrinkage part
                sim[xi, xj] *= (freq[xi, xj] - 1) / (freq[xi, xj] - 1 +
                                                     shrinkage)

```

**Comment by NicolasHug** [comment]
This is cython code so variables are typed here.

Also in the rest of the code we always import division from future, so that python 2 behaves like python 3: a single slash gives you a flash when result isn't an integer.
