### ISSUE TITLE
How can prevent my dataset to train over again for each recommendation, and get the recommendation for the specific user? 

### ISSUE THREAD

**Issue by aliko13** [NicolasHug/Surprise#151]
Hi! I am creating a web application that gives a recommendation for the users. 
User rates items and I need to send that user, item, rating to the model to give predictions.
The piece of code below loads the dataset, trains, and predicts the items for all the users. 
I want to save the "algo" model as a .pkl file (the same way as in scikit-learn), and use for the predictions.
On the other hand, I want to get recommendation only for a specific user.
Is it possible?
Thanks in advance :)

#get the csv file to dataframe
df = pd.read_csv(file_path)

reader = Reader(rating_scale=(1, 5))

data = Dataset.load_from_df(df[['user', 'item', 'rating']], reader)

trainset = data.build_full_trainset()
algo = SVD()
algo.fit(trainset)

testset = trainset.build_anti_testset()

          #is it right way?
        # set the testset to data for requested ID
        testset = [val for val in testset if val[0]==id]

predictions = algo.test(testset)

**Comment by NicolasHug** [comment]
Hi,
You'll need to use the `predict` method of the algorithm to target a specific user.
For pickling the algorithm, please refer to the docs.
