### ISSUE TITLE
How can we give the result of similarity calculations as a parameter to the recommendation algorithm?

### ISSUE THREAD

**Issue by himanData** [NicolasHug/Surprise#152]
#### Description
Hello,
Imagine someone wants to use different similarity measures for different parts of the data. How can we get the similarities for those portions separately and feed them as inputs to our recommendation algorithm? Something similar to Apache Mahout which I put the code here:

```
DataModel model = new FileDataModel(new File("/path/to/dataset.csv"));
UserSimilarity similarity = new PearsonCorrelationSimilarity(model);
UserBasedRecommender recommender = new GenericUserBasedRecommender(model, neighborhood, similarity);
```
Thanks a lot

**Comment by NicolasHug** [comment]
Can you please expand a bit on *use different similarity measures for different parts of the data*? Not sure at all what this means.

**Comment by himanData** [comment]
For example, imagine you want to use Pearson similarity for users above 40 years old and cosine for users below 40. This is just an imaginary example but there might be some cases where we need to have multiple similarity measures. Then our recommendation algorithm for those users need to use separate similarity measures.

**Comment by NicolasHug** [comment]
How does that differ from using a different algorithm for each part of the data?

**Comment by himanData** [comment]
It is different in that sense that every other part of the process is the same just the similarity calculation. It would be a good idea If we could have the similarity results ready and then give it to our algorithm for the rating prediction. Exactly like the Mahout code I wrote above. The UserSimilarity object has been calculated and then it is given to the GenericUserBasedRecommender.

**Comment by NicolasHug** [comment]
I see.
That's just a matter of convenience then, you don't get any performance / accuracy gain from this. The *every other part of the process* bit is basically just the computation of the prediction.

So to answer your original question: the way to have this in surprise is to instanciate different algorithms, with the similarities that you want. It's then up to you to route a prediction to the recommender of your choice.
