### ISSUE TITLE
Getting different top10-recommendations for each run with the sample code in FAQ

### ISSUE THREAD

**Issue by zhenliu2012** [NicolasHug/Surprise#155]
#### Description
Hi Nicholas,
I am having a problem with unreproducible recommendation results by running the same code. I use the sample code in FAQ doc (examples/top_n_recommendations.py). For a specific user with uid='186', I get different recommendations each time I run this code. I also tried to change the n_epochs parameter in SVD() to a larger number ( e.g. 50), but still.. the recommendations I get are different from each run.

My expected results would be that the top-10 recommendations from different runs are at least ~80% similar, but the actual results are quite different.

Can you enlighten me on why this is happening and possible way to fix it? Please correct me if I am wrong.

Thanks!
Zhen

#### Steps/Code to Reproduce

```python
from collections import defaultdict
from surprise import SVD
from surprise import Dataset

def get_top_n(predictions, n=10):
    '''Return the top-N recommendation for each user from a set of predictions.

    Args:
        predictions(list of Prediction objects): The list of predictions, as
            returned by the test method of an algorithm.
        n(int): The number of recommendation to output for each user. Default
            is 10.

    Returns:
    A dict where keys are user (raw) ids and values are lists of tuples:
        [(raw item id, rating estimation), ...] of size n.
    '''

    # First map the predictions to each user.
    top_n = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))

    # Then sort the predictions for each user and retrieve the k highest ones.
    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings[:n]

    return top_n

data = Dataset.load_builtin('ml-100k')
trainset = data.build_full_trainset()
algo = SVD()
testset = trainset.build_anti_testset()
#first run
algo.fit(trainset)
predictions = algo.test(testset)
top_n = get_top_n(predictions, n=10)
for uid, user_ratings in top_n.items():
    if uid == '186':
        print(uid, [iid for (iid, _) in user_ratings])
#second run
algo.fit(trainset)
predictions = algo.test(testset)
top_n = get_top_n(predictions, n=10)
for uid, user_ratings in top_n.items():
    if uid == '186':
        print(uid, [iid for (iid, _) in user_ratings])
#third run
algo.fit(trainset)
predictions = algo.test(testset)
top_n = get_top_n(predictions, n=10)
for uid, user_ratings in top_n.items():
    if uid == '186':
        print(uid, [iid for (iid, _) in user_ratings])
```

#### Expected Results
would be at least 80% similar. I also compared the results with scipy.linalg.svds, they are only 20% similar, but result from scipy.linalg.svds is stable and reproducible .

#### Actual Results
186 ['408', '513', '14', '659', '178', '318', '488', '483', '133', '114']
186 ['286', '313', '169', '178', '408', '318', '1449', '64', '611', '522']
186 ['408', '170', '318', '114', '936', '133', '483', '28', '427', '531']

#### Versions

Darwin-16.0.0-x86_64-i386-64bit
Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 21 2017, 18:29:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
surprise 1.0.5

**Comment by NicolasHug** [comment]
Have you tried using a fixed random state for SVD?
