### ISSUE TITLE
How to handle binary user-item matrix (observations)?

### ISSUE THREAD

**Issue by rydevera3** [NicolasHug/Surprise#157]
#### Description

This isn't not an issue but a question on how to handle the reader when my matrix is (user id, item id, 1) - where 1 represents if they purchased an item. My data isn't ratings but rather whether the person purchased the item or not. 

`reader = Reader(rating_scale=(1, 5))`
I set the rating_scale = (1, 1) when I looked at my predictions most of them were the same for each user.

Ex:

```
(1, [622, 636, 768, 2035, 2593, 3045, 593, 750, 1188, 2882])
(2, [622, 636, 768, 2035, 2593, 3045, 593, 750, 1188, 2882])
```

**Comment by drdhaval2785** [comment]
maybe you should try (0, 1)
(1,1) would mean only 1 to 1 i.e. only 1 is possible.
(0,1) would mean that 0 and 1 are valid points.
Just a thought.
@rydevera3

**Comment by NicolasHug** [comment]
As previously mentioned multiple times, binary ratings are not supported (yet).

**Comment by drdhaval2785** [comment]
I withdraw my comment in light of observation of author.

**Comment by rishabh-vij** [comment]
> #### Description
> This isn't not an issue but a question on how to handle the reader when my matrix is (user id, item id, 1) - where 1 represents if they purchased an item. My data isn't ratings but rather whether the person purchased the item or not.
> 
> `reader = Reader(rating_scale=(1, 5))`
> I set the rating_scale = (1, 1) when I looked at my predictions most of them were the same for each user.
> 
> Ex:
> 
> ```
> (1, [622, 636, 768, 2035, 2593, 3045, 593, 750, 1188, 2882])
> (2, [622, 636, 768, 2035, 2593, 3045, 593, 750, 1188, 2882])
> ```

Hi @rydevera3 How did you handle this issue finally? Did you use some other library or found a workaround to use surprise for handling binary ratings?

**Comment by IvanEvan** [comment]
> #### 描述
> 这不是问题，而是关于当我的矩阵为（用户ID，商品ID，1）时如何处理阅读器的问题-其中1表示他们是否购买了商品。我的数据不是等级，而是该人是否购买了该物品。
> 
> `reader = Reader(rating_scale=(1, 5))`
> 当我查看预测时，我将rating_scale =（1，1）设置为每个用户大多数。
> 
> 例如：
> 
> ```
> (1, [622, 636, 768, 2035, 2593, 3045, 593, 750, 1188, 2882])
> (2, [622, 636, 768, 2035, 2593, 3045, 593, 750, 1188, 2882])
> ```

Hi，I got the same question, have u solve it?

**Comment by mattiacampana** [comment]
According to the Surprise website, (surprisingly!) the framework only deals with explicit rating data.
In other words, it does not support binary feedbacks.
In my opinion, this should be a major feature to implement in Surprise. In real world applications, is quite clear that users are unwilling to specify a rating on their purchase or downloads.
Therefore, should be more useful to support binary (implicit) users’ feedbacks.
