### ISSUE TITLE
How to retrieve the k-nearest neighbors?

### ISSUE THREAD

**Issue by Tauranis** [NicolasHug/Surprise#16]
Given the collaborative filtering issue, how can I retrieve the top K recommendations for a given user?
The documentation is not clear enough for that.

Is the scikit-surprise only an evaluation tool or can it be applied for real world scenario?

Kind Regards,

Tauranis

**Comment by Tauranis** [comment]
Also, once the best configuration is found, how to train with the whole dataset?

**Comment by NicolasHug** [comment]
Hi,

Do you need to retrieve the k-nearest neighbors of a user or the k items with highest rating prediction for a given user? The title of the issue suggests the former, your description suggests the latter.

Either way, you will need to retrieve these lists yourself, as surprise does not support this directly (for now). It should only take a few lines of code though.

For the first one you will need the `sim` field of your algorithm, which is the similarity matrix that is built during the training stage. It is almost done in the docs [here](http://surprise.readthedocs.io/en/v1.0.2/building_custom_algo.html#using-similarities-and-baselines).

To retrieve the items with highest rating prediction, just parse the `predictions` list as returned by the [test](method).

As for training on the whole dataset, it is all explained in the [User Guide](http://surprise.readthedocs.io/en/v1.0.2/getting_started.html#train-on-a-whole-trainset-and-specifically-query-for-predictions)

Surprise was mostly designed to be an evaluation tool and mostly to make the implementation of new algorithms quick and easy. It's probably not the best tool for *real world scenario* but deppending on your needs, it may still be efficient. It's really up to you to decide.

**Comment by NicolasHug** [comment]
Did I answer your questions? If so, can I close the issue?
