### ISSUE TITLE
Accessing the Similarity Matrix

### ISSUE THREAD

**Issue by vsai121** [NicolasHug/Surprise#162]
Hello,
I am using the cosine similarity for item based collaborative filtering.

The code is given below

```
sim_options = {
'name': 'cosine',
'user_based': False
}

knn = KNNWithZScore(k = 100 , min_k = 1 ,sim_options=sim_options)

knn.fit(trainingSet)

predictions = knn.test(testSet)
```

Instead of directly getting the predictions, is there any way to access the similarity matrix which is computed?

Thanks a lot!

**Comment by NicolasHug** [comment]
Yes you can use the algo.sim attribute

**Comment by vsai121** [comment]
I tried using what you suggested but I ran into this error.
```
Traceback (most recent call last):
  File "knnBasic.py", line 93, in <module>
    sim = knn.sim
AttributeError: 'KNNWithZScore' object has no attribute 'sim'
```

**Comment by NicolasHug** [comment]
You need to compute the similarity matrix first. Calling `fit()` will do.

**Comment by vsai121** [comment]
Thanks for your help.

I will close the issue now.
