### ISSUE TITLE
Common users in cosine similarity.

### ISSUE THREAD

**Issue by vsai121** [NicolasHug/Surprise#165]
Hello,
In the documentation for the cosine module, it states the following.

Only common users (or items) are taken into account.

Is there a way to set a parameter which decides the number of common users or items such as:

```
sim_options = {
'name': 'cosine',
'user_based': False,
'common_users' = 10
}
```

Thank you

**Comment by NicolasHug** [comment]
No, the whole set U_ij (i.e. the set of users having rated both items i and j) will be used to compute cos(i, j).

May I ask why you'd want to limit it to 10 users? How would you choose which users to use and which users to discard?

You can, however, force this number to be greater than some value using the min_support parameter (see the docs for details).

**Comment by vsai121** [comment]
Yes, what I meant to ask was how to force the number of common users to be greather than some arbitary value.

I will look into the documentation.

Thank You
