### ISSUE TITLE
Different number of latent factor vector will change the result？

### ISSUE THREAD

**Issue by a6822342** [NicolasHug/Surprise#171]
#### Description

Hello, Nicolas. I have try different number of latent vector such as 20, 30, 40 in SVD, but the rmse always comes out the same result. Is there any error in my code? 
Thank you,Nicolas.
#### Steps/Code to Reproduce

reader=Reader(line_format='user item rating timestamp', sep='::')
algo=SVD(n_factors=20) 
folds_file=[(trainpath  , testpath)]
data=Dataset.load_from_folds(folds_file,reader=reader)
pkf=PredefinedKFold()
trainser,testset=next(pkf.split(data))
algo.fit(trainset)
accuracy.rmse(algo.test(testset))

#### Versions

surprise v1.0.5

**Comment by NicolasHug** [comment]
Changing the number of factor does addect the RMSE in e.g. the movielens datasent so that's probably on your end. Maybe your dataset is too small and the model overfits?
As far as I can tell the code looks OK

**Comment by a6822342** [comment]
Hello, NicolasHug,  the dataset is movielens 10M.  And 80% of it is trainset and 20% is testset. I change the value of parameter named "clip" in method predict(self, uid, iid, r_ui=None, clip=Ture, verbose=False) from Ture to False.  And rmse doesn't change obvious too. 
Then I run same code on movielens 100k ( clip is Ture ) , it seems good and the rmse changes when number of latent vector changes.
And I overwrite the print method of RMSE, changeing print('RMSE :{0:1.4f}'.format(rmse_)) to print('RMSE :{0:1.8f}'.format(rmse_)).

experiment results:
dataset: ml-10m
number of latent vector： 10                 20               30                   40                50
rmse                             1.06288611   1.06288652  1.06288621   1.06288662    1.06288605
From the result , we can see the rmse is nearly stable. Is there some problem in dataset movielens 10m or the model is overfits on movielens 10m dataset? 
Thank you.

**Comment by NicolasHug** [comment]
Then everything is fine.

It's probably just because the current default parameters of SVD aren't tuned for ML10M, and the RMSE you get (which seems pretty high) is mostly due to other parameters not being set properly.
Try changing the number of epochs and / or regularization parameters.

You can also use gridsearch or randomized grid search for that.

**Comment by a6822342** [comment]
ok, thank you very much. I will close the issue later.
