### ISSUE TITLE
how to import a new prediction algorithms in my .py file?

### ISSUE THREAD

**Issue by DoubleYing** [NicolasHug/Surprise#173]
I add a new algorithm in this file "Surprise\surprise\prediction_algorithms\matrix_factorization.pyx", and I complie it to generate the right .pyd file. But, when I want to use the new algorithm in my.py file . I find it cannot import the algorithm class, so what other configuration should I do ?

**Comment by NicolasHug** [comment]
you don't need to add your new algo to one of the package's files.

Just use a different file
