### ISSUE TITLE
In load dataframe example, AttributeError: 'NoneType' object has no attribute 'offset' 

### ISSUE THREAD

**Issue by sroder** [NicolasHug/Surprise#175]
#### Description
While Loading Data from Dataframe, I am getting the error NoneType object has no attribute 'offset'

#### Steps/Code to Reproduce
data = Dataset.load_from_df(df=matrix_setup[['CustomerID','StockCode','AmountSpend']],reader=None)

my dataframe looks likes this
  | CustomerID | StockCode | AmountSpend
-- | -- | -- | --
17850.0 | 85123A | 15.30
17850.0 | 71053 | 20.34
17850.0 | 84406B | 22.00

#### Expected Results
no error
#### Actual Results
NoneType object has no attribute 'offset'
#### Versions

Windows-7-6.1.7601-SP1
('Python', '2.7.14 |Anaconda, Inc.| (default, Nov  8 2017, 13:40:13) [MSC v.1500 32 bit (Intel)]')
('surprise', '1.0.5')

**Comment by NicolasHug** [comment]
you need the reader param

**Comment by sroder** [comment]
Thanks, that was lame from me
