### ISSUE TITLE
Knowledge-based RS in Graphs at SurPRISE

### ISSUE THREAD

**Issue by itsoum** [NicolasHug/Surprise#176]
Hello Nicolas,

I have check your library and there is a really good job. Bravo!
I have a twofold idea.
In SurPRISE, is possible a set of data to be considered as graph? Can I feed the algorithms with a big list filled of representations of graphs where each graph is a python list of tuples `[('A', 'B'), ('B', 'C'), ('B', 'D'), ('C', 'D'), ('E', 'F'), ('F', 'C')]` ? 
After that I am able to recommend new nodes used similarities (as a first step) to identified the common or nearest neighbors of a node?
I want to develop a RS for micro-services and I don't want use CF, ratings and human/computer interaction there. Thus the beautiful ratings' prediction algorithms like NMF and yours analogical RS are unuseful for the begin (of course can I predict the missing distances=links if I have a item x item dinstances matrix).

Best regards,
Ilias

**Comment by NicolasHug** [comment]
Hi,

Surprise only supports explicit ratings for now.

I wish I could point you towards another lib that focuses on graph RS, but I don't know any (I'm interested if you find one though)

Nicolas

**Comment by itsoum** [comment]
You consider it as possible/feasible to I begin an extension of Surprise in Graph RS?
