### ISSUE TITLE
What is the testset list return by train_test_split()?

### ISSUE THREAD

**Issue by elaine-peiru** [NicolasHug/Surprise#177]
Hi,
I have a question to what is the testset list return from the train_test_split()?
As they are neither inner id or raw id..
I need this list (which then be transformed as a table) to get the predicted-rating for all the user/item pair on the testset in order to evaluate the precision and recall.
But since now the first two column seems like neither (user/item) inner id or (user/item) raw id, I don't know how to proceed.
Would be great if someone can answer me the question! Thank you:)  
<img width="1116" alt="screen shot 2018-05-12 at 17 17 58" src="https://user-images.githubusercontent.com/28541158/39958848-c7bc84f4-5608-11e8-8ad6-5a2df0b62e22.png">

**Comment by NicolasHug** [comment]
the testset object is a list of tuples (raw user id, raw item id, ground truth rating).

**Comment by elaine-peiru** [comment]
Thanks for your quick reply. I understand now :)
However, After train_test_split(), when I run this code to generate the est value for all the user/item pair on the testset, i always got the error message of "Item 64034 is not part of the trainset."
<img width="628" alt="screen shot 2018-05-13 at 17 08 14" src="https://user-images.githubusercontent.com/28541158/39968616-5c7e9c2c-56d0-11e8-81cc-6f2e2d27063e.png">
What could be the potential problem of this? I have been trying to solve the problem for a while and still didn't get it right. Could you please give me some hint? Thanks!

**Comment by NicolasHug** [comment]
You're converting to raw ids to inner ids and then back to raw ids. Don't do that.

Just use m.userID and m.movieID in algo.predict and it should be fine.

**Comment by elaine-peiru** [comment]
You are right! Thank you! The problem solved :)
