### ISSUE TITLE
Error while designing my own algorithm

### ISSUE THREAD

**Issue by SantGIIT** [NicolasHug/Surprise#178]
I run the following code in python:
=============================================
class MyOwnAlgo(AlgoBase):

    def __init__(self):
        AlgoBase.__init__(self)

    def fit(self, trainset):
        AlgoBase.fit(self, trainset)
        self.value = 4  #Fixing it to 4, for sanity check experiment
        return self

    def estimate(self, u, i):
        return self.value
  
algo = MyOwnAlgo()
algo.fit(train_data)
algo.predict(str(uid),str(iid),r_ui=6)
==========================================
But why the result of the predict method is not 4? It is coming out to be 1 as all the training data has value 1. Please, help me understand this.

**Comment by NicolasHug** [comment]
What's your rating scale? I suspect it's because the prediction is clipped into your rating scale which is (1, 1).
Use predict(..., clip=False) and see how it goes.

**Comment by SantGIIT** [comment]
Yeah... Got it.... Setting clip to false worked. 
Rating scale was in the range [0,1], in fact, it is binary. 
Thank you so much NicolasHu.
