### ISSUE TITLE
How to split my dataset into a training and testing data

### ISSUE THREAD

**Issue by rodrigocesar** [NicolasHug/Surprise#18]
I am trying to understand how I can split my dataset into the a training and testing set.

I am using the following code to read my dataset:

```
import os
from os.path import dirname
import pandas as pd  
from surprise import SVD
from surprise import Dataset, Reader
from surprise import evaluate, print_perf
from surprise import GridSearch
from surprise.dump import dump
from surprise import KNNBasic


# Entrar endereço da tabela de ratings.
file_path = dirname(os.path.abspath(os.getcwd())) + \
    "/Data/Compras_normalizado_media_surprise.csv"
print(file_path)

# Preparar e configurar o reader to scikit-surprise.
reader = Reader(line_format='user item rating', sep=';')


# Ler os dados na forma cliente, produto, rating.
data = Dataset.load_from_file(file_path, reader=reader)
```
How can I split data into data_train and data_test?

**Comment by NicolasHug** [comment]
I'm sorry but have you read the [docs](http://surprise.readthedocs.io/en/v1.0.2/getting_started.html)?

**Comment by rodrigocesar** [comment]
Yes, I did. 
It says that I could use, for instance:

```
for trainset, testset in data.folds():

    # train and test algorithm.
    algo.train(trainset)
    predictions = algo.test(testset)

    # Compute and print Root Mean Squared Error
    rmse = accuracy.rmse(predictions, verbose=True)
    
    dump('./Models', predictions, trainset, algo)
```
Is that a valid way to build a test set? Is there another way? 

I am also interested in how the split is being made. Where can I get information about it?

Thanks!

**Comment by NicolasHug** [comment]
What exactly do you need to do? Do you need to perform a k-folds cross-validation procedure? Or is your dataset already split into predefined folds? Both cases are clearly explained in the doc, and looking at the other issue you opened it seems that you already are performing 5-folds cross validation. If what you need is another use-case, please be more specific because I fail to see what you don't understand.

All the info you need about the splitting is in the code. There is not much to know about it honestly, the dataset is just split into k folds of equal sizes. At each of the k iteration, 1 fold is used for testing, and the k - 1 remaining folds are used for training.

**Comment by rodrigocesar** [comment]
My data is not split. It is clear what cross-validation does.

What I need to do is to get the whole dataset, 1) split into train and test sets, lets say 90% train and 10% test and then 2) perform cross-validation on the training set to fit a model.

I could not find a function for step #1 in the documentation.

**Comment by NicolasHug** [comment]
Please read the first section of the [Doc](http://surprise.readthedocs.io/en/v1.0.2/getting_started.html) and come back to me if that's still unclear.

Again: you were already doing cross-validation in your previous issue, so you seem to be asking me something you already know how to do.

**Comment by rodrigocesar** [comment]
I already said cross-validation is clear. I think the former post is clear but will try again.

#1 - First, I want to split my dataset into a training set and a test set. Lets say I save the training and test sets on separate files.

#2 - Then, I would like to use cross-validation or Grid Search using ONLY the training set, so I can tune the parameters of the algorithm.

3# - Then, I would like to test the performance of the best algorithm using the test set.

**Comment by NicolasHug** [comment]
This is really hacky but it should do what you need.

    from __future__ import (absolute_import, division, print_function,         
                            unicode_literals)                                  
                                                                               
    import random                                                              
                                                                               
    from surprise import NormalPredictor                                       
    from surprise import Dataset                                               
    from surprise import accuracy                                              
                                                                               
                                                                               
    algo = NormalPredictor()                                                   
                                                                               
    # Load your full dataset. You will probably want to use load_from_file     
    tmp_data = Dataset.load_builtin('ml-100k')                                 
                                                                               
    # shuffle ratings if you want                                              
    random.shuffle(tmp_data.raw_ratings)                                       
                                                                               
    # 90% trainset, 10% testset                                                
    threshold = int(.9 * len(tmp_data.raw_ratings))                            
                                                                               
    trainset_raw_ratings = tmp_data.raw_ratings[:threshold]                    
    train_data = Dataset.load_builtin('ml-100k') # don't change this           
    train_data.raw_ratings = trainset_raw_ratings                              
                                                                               
    train_data.split(n_folds=5)                                                
                                                                               
    # Select your best algo with whatever you want.                            
    for trainset_cv, testset_cv in train_data.folds():                         
        algo.train(trainset_cv)                                                
        predictions = algo.test(testset_cv)                                    
        accuracy.rmse(predictions)                                             
                                                                               
                                                                               
    # retrain on the whole train set                                              
    trainset = train_data.build_full_trainset()                                
    algo.train(trainset)                                                       
                                                                               
    # now test on the testset                                                  
    test_raw_ratings = tmp_data.raw_ratings[threshold:]                        
    test_data = Dataset.load_builtin('ml-100k') # don't change this            
    test_data.raw_ratings = test_raw_ratings                                   
    testset = test_data.construct_testset(raw_testset=test_raw_ratings)        
                                                                               
    predictions = algo.test(testset)                                           
    accuracy.rmse(predictions) 

Obviously a much, much, much simpler way would be to split your data yourself into two distinct files.

What you want to do still seems a bit wierd to me. If you want an unbiased estimation of the performances of your algorithm, you could just use  cross validation.

BTW, stuff like "hi", "hello"  and "thanks" are nice to hear from time to time.

Nicolas

**Comment by NicolasHug** [comment]
Did you manage to do what you wanted? If so, can I close the issue?

Thanks

**Comment by rodrigocesar** [comment]
Ok, thanks for the help. I will just replace the `# Select your best algo with whatever you want` step with a grid search.

And no, if you want an unbiased estimation of the predictive power of an algorithm using grid search to tune the parameters, you should not just apply cross-validation to the entire dataset for obvious reasons.

You said "Obviously a much, much, much simpler way would be to split your data yourself into two distinct files." Of course it is! That is why I asked just that since the beginning. Actually, the title of this issue reads: How to split my dataset into a training and testing data.

I really appreciate your help!

BTW I said thanks after your first reply to this issue and also on the other issue and if you think you were polite along your responses, think again!

**Comment by NicolasHug** [comment]
Hi,

You are right that if you fit the algorithm with grid search the cross validation performances will be biased. I did not really understand what you wanted to do, but it is clear to me now it is indeed a very legitimate use case. I've come up with a cleaner solution (using gridsearch):

    from __future__ import (absolute_import, division, print_function,         
                            unicode_literals)                                  
                                                                               
    import random                                                              
                                                                               
    from surprise import SVD                                                   
    from surprise import Dataset                                               
    from surprise import accuracy                                              
    from surprise import GridSearch                                            
                                                                               
                                                                               
    # Load your full dataset.                                                  
    data = Dataset.load_builtin('ml-100k')                                     
    raw_ratings = data.raw_ratings                                             
                                                                               
    # shuffle ratings if you want                                              
    random.shuffle(raw_ratings)                                                
                                                                               
    # 90% trainset, 10% testset                                                
    threshold = int(.9 * len(raw_ratings))                                     
    trainset_raw_ratings = raw_ratings[:threshold]                             
    test_raw_ratings = raw_ratings[threshold:]                                 
                                                                               
    data.raw_ratings = trainset_raw_ratings  # data is now your trainset       
    data.split(n_folds=3)                                                      
                                                                               
    # Select your best algo with grid search. Verbosity is buggy, I'll fix it. 
    print('GRID SEARCH...')                                                    
    param_grid = {'n_epochs': [5, 10], 'lr_all': [0.002, 0.005]}               
    grid_search = GridSearch(SVD, param_grid, measures=['RMSE'], verbose=0)    
    grid_search.evaluate(data)                                                 
                                                                               
    algo = grid_search.best_estimator['RMSE']                                  
                                                                               
    # retrain on the whole train set                                           
    trainset = data.build_full_trainset()                                      
    algo.train(trainset)                                                       
                                                                               
    # now test on the trainset                                                 
    testset = data.construct_testset(trainset_raw_ratings)                     
    predictions = algo.test(testset)                                           
    print('Accuracy on the trainset:')                                         
    accuracy.rmse(predictions)                                                 
                                                                               
    # now test on the testset                                                  
    testset = data.construct_testset(test_raw_ratings)                         
    predictions = algo.test(testset)                                           
    print('Accuracy on the testset:')                                          
    accuracy.rmse(predictions)  

This is still a bit hacky but it does a better job than the first version (if you find any bug please come back to me!). I'll add this to the doc and to the examples soon.

Nicolas

**Comment by rodrigocesar** [comment]
Thanks!

**Comment by NaveganteX** [comment]
Hello, Nicolas!

Hope all is good! I am doing my master thesis and I am using your amazing Surprise package, which you made for the occasion (PhD thesis).

I think this post is one of the most important in the blog, for obvious reasons explained above. 

I wanted to ask you how can I use your `cross_validate() `class instead of  `GridSearch(SVD, param_grid, measures=['RMSE'], verbose=0)`.

I want to set `cross_validate(whatever_algo,cv=10,n_jobs=-1)`

Thank you very much in advance!

**Comment by MauritiusKlein** [comment]
@NicolasHug i am receiving an error on the split method you used.

AttributeError: 'DatasetAutoFolds' object has no attribute 'split'

I just copied your code, do you know what that error could be?
