### ISSUE TITLE
Getting issue of TopN recommendation for specific user

### ISSUE THREAD

**Issue by elaine-peiru** [NicolasHug/Surprise#181]
Hi :)
Sorry, I know this question have been asked for lots of time but I am very new to Python and couldn't fix this issue myself.
No matter what I select the for the user, I get the same recommendation for Top 10.
Here is the example: I input user 267, 15722, etc. I always got the same list.

Very appreciate for the help!
<img width="669" alt="screen shot 2018-05-19 at 11 21 22" src="https://user-images.githubusercontent.com/28541158/40267101-463257d4-5b57-11e8-9cdc-6a3f977c0a71.png">
Update: I run the top 10 for every user, and I got very similar result. most of the list are the same. Is it  the problem of my dataset?

**Comment by NicolasHug** [comment]
That == sign looks fishy, I don't think it does what you think it does.

I would suggest starting from the example in the FAQ, and incrementally going from there, checking the results with every change.
