### ISSUE TITLE
predict user's item rate without iid parameter.

### ISSUE THREAD

**Issue by leebaro** [NicolasHug/Surprise#183]
hello.

Can I predict the ratings for all items that the user has not rated?

in below code, I have to set uid and iid for predicting.

I want to set only uid. then I expect that all item that user has not rated.

Thank you.

**Comment by NicolasHug** [comment]
There no built-in for this but you just need to call predict with all the iids that you want. You can wrap it in a function if you want to

**Comment by leebaro** [comment]
Thank you.
how can I predict for all the iids?

**Comment by leebaro** [comment]
Do I use a for loop 100,000 times, If I have 10 users and 10,000 items?

**Comment by NicolasHug** [comment]
something like

```
for iid in the_iid_list:
    algo.predict(the_uid, iid, ...)
```

**Comment by leebaro** [comment]
Thank you very much.
