### ISSUE TITLE
ValueError: could not convert string to float - Keras Library being used

### ISSUE THREAD

**Issue by pragyan03** [NicolasHug/Surprise#184]
I am working on agriculture dataset having fields:
State_Name, District_Name, Crop_year, Season, Crop

I am trying to train my Model using Python library Keras and using Sequential Model.
During the training of the model, while running the code, its showing me the following error.

i've already seen other issues related to this, but they are not helping me

`

def trainModel(data=None, epochs=20):

    batch = 256
    start = time.time()
    model = Model()

    if data is None:
        print(" Provide the Data")
        return

    x_train,x_test,y_train,y_test = data

    print(" Starting the training")

    history = model.fit(x_train[:200000],y_train[:200000],epochs = epochs,
                        batch_size=batch, validation_data = (x_train[200000:],y_train[200000:]))

    duration = time.time()-start

    print(" Time taken to train the data - ",duration)

    return model,history

train_model,train_history = [trainModel(data=[x_train,x_test,y_train,y_test],epochs=50)]
`

![aq](https://user-images.githubusercontent.com/22367945/40480043-efc89026-5f6a-11e8-8d2f-acb4ffa1f3ed.png)

 Please help.
ThankYou

**Comment by NicolasHug** [comment]
Keeping my calm...
