### ISSUE TITLE
Regularization parameter λ5 of SGD

### ISSUE THREAD

**Issue by raviraju** [NicolasHug/Surprise#185]
#### Description

As per documentation (http://surprise.readthedocs.io/en/stable/prediction_algorithms.html#similarity-measures-configuration) 
'reg': The regularization parameter of the cost function that is optimized, corresponding to λ1 and then λ5 in [Kor10].
Could not find an implementation of loss function (eq 11 in [Kor10](http://surprise.readthedocs.io/en/stable/notation_standards.html#koren-2010)) w.r.t λ5, which takes implicit preference of user

#### Versions

import platform; print(platform.platform())
Linux-4.5.0-994-generic-x86_64-with-debian-stretch-sid

import sys; print("Python", sys.version)
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0]

import surprise; print("surprise", surprise.__version__)
surprise 1.0.6

**Comment by NicolasHug** [comment]
> Could not find an implementation of loss function (eq 11 in Kor10) w.r.t λ5, which takes implicit preference of user

That's because there's no implementation of this algorithm in Surprise.

The algorithm you're linking to refers to the optimization problem at the end of page 4.

**Comment by raviraju** [comment]
In that case it would be better to update the documentation to mention only about λ1

**Comment by NicolasHug** [comment]
You're right, can you please submit a PR? I won't have my laptop this weekend.
