### ISSUE TITLE
Error while using GridSearchCv : 'Trainset' object has no attribute 'raw_ratings'

### ISSUE THREAD

**Issue by guptakvgaurav** [NicolasHug/Surprise#190]
Usage of `GridSearchCV` is resulting in `'Trainset' object has no attribute 'raw_ratings'` error.

```
from surprise.model_selection import GridSearchCV
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(df[['profile_id', 'content_id', 'rating']], reader)
trainset, testset = train_test_split(data, test_size=.25, random_state=20)


param_grid = {
              'n_factors': [30],
              'n_epochs': [5, 10, 20], 
              'lr_all': [0.002, 0.006, 0.018, 0.054, 0.10, 0.15]
             }
algo = GridSearchCV(SVDpp, param_grid, measures=['rmse', 'mae'], cv=3)
model = algo.fit(trainset)  // error occurs here
```
However, if i don't use GridSearchCV and simply fit the model, then `fit()` works fine. Correctly working snippet is below:
```
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(df[['profile_id', 'content_id', 'rating']], reader)
trainset, testset = train_test_split(data, test_size=.25, random_state=20)

algo = SVDpp(n_factors=30, 
             n_epochs=40, 
             lr_all=0.005, 
             random_state=40, 
             verbose=False, 
             init_mean=0)
model = algo.fit(trainset)

```

Stacktrace:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-371-5c21553dea1e> in <module>()
      5 #              verbose=False,
      6 #              init_mean=0)
----> 7 model = algo.fit(trainset)
      8 predictions = algo.test(testset)

/Users/ttn/anaconda/lib/python3.6/site-packages/surprise/model_selection/search.py in fit(self, data)
     84                                    self.return_train_measures)
     85             for params, (trainset, testset) in product(self.param_combinations,
---> 86                                                        cv.split(data))
     87         )
     88         out = Parallel(n_jobs=self.n_jobs,

/Users/ttn/anaconda/lib/python3.6/site-packages/surprise/model_selection/split.py in split(self, data)
     93         '''
     94 
---> 95         if self.n_splits > len(data.raw_ratings) or self.n_splits < 2:
     96             raise ValueError('Incorrect value for n_splits={0}. '
     97                              'Must be >=2 and less than the number '

AttributeError: 'Trainset' object has no attribute 'raw_ratings'

```

**Comment by NicolasHug** [comment]
You should use data in gridsearchcv.

**Comment by guptakvgaurav** [comment]
@NicolasHug Yes, i got it working but i am not sure why can't we add training set. Since `trainingset` is a subset of `data`, then ideally it should have worked. Do we need to convert `trainset` into the type in which `data` is? If yes, why do we need such behaviour.

In meanwhile i will try to discover answer by reading the source.

**Comment by NicolasHug** [comment]
>Since trainingset is a subset of data

Conceptually yes, but not in the actual implementation.

The Trainset object is a more complex object than the Dataset object. Dataset is basically only a list of (user, item, rating) tuples) with some utilities to convert it into a Trainset or a Testset. The Trainset contains various data structures and methods to make it eas to build RS.

If your goal was to keep some data untouched for some kind of validation stage, please refer to the FAQ there's an entry on that

**Comment by a4ankan** [comment]
train_data = Dataset.load_from_df(reg_train[['user', 'movie', 'rating']], **reader = reader**)### try this

# build the trainset from traindata.., It is of dataset format from surprise library..
trainset = train_data.build_full_trainset()

**Comment by a4ankan** [comment]
`train_data = Dataset.load_from_df(reg_train[['user', 'movie', 'rating']], reader = reader)**__try this__


trainset = train_data.build_full_trainset() 

param_grid = {'n_epochs': [15, 20, 25, 30, 35, 40, 45, 50],
              'n_factors': [100, 200, 300],
              'lr_all': [0.002, 0.003, 0.004, 0.005],
              'reg_all': [0.02,0.01,0.05,0.1, 0.4, 0.6]}
svd = GridSearchCV(SVD, param_grid, measures=['rmse', 'mae'], cv=3, n_jobs = -1)

svd.fit(train_data)

print("RMSE score", svd.best_score['rmse'])


print("Best Parameters", svd_mf.best_params['rmse'])```

**Comment by soumendrabagh** [comment]
> @NicolasHug Yes, i got it working but i am not sure why can't we add training set. Since `trainingset` is a subset of `data`, then ideally it should have worked. Do we need to convert `trainset` into the type in which `data` is? If yes, why do we need such behaviour.
> 
> In meanwhile i will try to discover answer by reading the source.

This was really Helpful. Here is the FAQ Link you recommended for splitting train/test data for Matrix Factorization Algorithms like SVD : 

[FAQ Link](https://surprise.readthedocs.io/en/stable/FAQ.html)

**Comment by soumendrabagh** [comment]
> > @NicolasHug Yes, i got it working but i am not sure why can't we add training set. Since `trainingset` is a subset of `data`, then ideally it should have worked. Do we need to convert `trainset` into the type in which `data` is? If yes, why do we need such behaviour.
> > In meanwhile i will try to discover answer by reading the source.
> 
> This was really Helpful. Here is the FAQ Link you recommended for splitting train/test data for Matrix Factorization Algorithms like SVD :
> 
> [Click here for FAQ Link](https://surprise.readthedocs.io/en/stable/FAQ.html)

**Comment by soumendrabagh** [comment]
> > Since trainingset is a subset of data
> 
> Conceptually yes, but not in the actual implementation.
> 
> The Trainset object is a more complex object than the Dataset object. Dataset is basically only a list of (user, item, rating) tuples) with some utilities to convert it into a Trainset or a Testset. The Trainset contains various data structures and methods to make it eas to build RS.
> 
> I agree that ideally both objects should be compatible (in scikit learn for example everything is a numpy array), but recommender systems have stronger constraints compared to classical ML problems.
> 
> If your goal was to keep some data untouched for some kind of validation stage, please refer to the FAQ there's an entry on that

This was really Helpful. Here is the FAQ Link you recommended for splitting train/test data for Matrix Factorization Algorithms like SVD : 

[Click here for FAQ Link](https://surprise.readthedocs.io/en/stable/FAQ.html)
