### ISSUE TITLE
How to draw learning curve to figure out overfitting and underfitting

### ISSUE THREAD

**Issue by guptakvgaurav** [NicolasHug/Surprise#192]
I would like to plot the learning curve to check the overfitting and under-fitting in my procedure.

Can you recommend the way to do so ?

Why i need to do so ?
 - I am getting pretty decent result result for precision and recall. Precision is around 0.99 and recall is .88.
 - RMSE obtained is nearly ~ 1 (to be precise 1.03)
But, results i got out of prediction are not convincing to me ( from practicality point of view). This situation made me think to analyse whether i am hit by bias or variance and for that i need learning curve. Can you suggest something ?

**Comment by NicolasHug** [comment]
You would have to modify the code of the fit procedure yourself... There's no other way.
It would be easy to get the train error, for the test error you'll need to pass the testset as an argument so it might get trickier from then.
