### ISSUE TITLE
Get pandas Dataframe from Surprise Dataframe

### ISSUE THREAD

**Issue by msramalho** [NicolasHug/Surprise#193]
#### Description
I would like to know if there is a way to extract the data imported into Surprise (back) into a pandas dataframe. This is because, as far as I know, surprise has no data display functionality that one can use, like `data.head()` in pandas.
An example of my code:
```python
reader = Reader(line_format='user item rating', sep=';', rating_scale=(0, 10), skip_lines=1)
df = Dataset.load_from_file('myRatings.csv', reader=reader)
# some magic here, because
print(df) # does not work as expected
# adfter magic
data.head() # or other visualization stuff
```

Thank you for your time

**Comment by guptakvgaurav** [comment]
I think this should do the job for you.
```
iterator = trainset.all_ratings()
new_df = pd.DataFrame(columns=['uid', 'iid', 'rating'])
i = 0
for (uid, iid, rating) in iterator:
    new_df.loc[i] = [uid, iid, rating]
    i = i+1

new_df.head(2)
```

**Comment by msramalho** [comment]
Thank you for your answer. I implemented and it worked (except for the fact that not for the size of my dataset). I eventually started by reading a pandas df from scratch. But again, thank you.

**Comment by miguelgfierro** [comment]
hey @msramalho maybe you don't need this anymore. I made a function that gets the df https://github.com/Microsoft/Recommenders/blob/60f246051904170dac0816d44f90739f487fc079/reco_utils/recommender/surprise/surprise_utils.py#L8

FYI @NicolasHug, in case you want to add this to the library
