### ISSUE TITLE
Use rating data in a pandas data frame

### ISSUE THREAD

**Issue by longhowlam** [NicolasHug/Surprise#20]
Hi,

Just wondering if there is a way in surprise to use rating data that is already inside a pandas data frame?

Regards,
Longhow

**Comment by NicolasHug** [comment]
Hi,

We should be able to hack our way into it, but you'll need to show me the dataframe you want to use for me to help you.

Nicolas

**Comment by longhowlam** [comment]
Basically a pandas dataframe with three columns:

userID   itemID rating
1            1           4
2            1           5
3            2           2
...
...

regards,
Longhow

**Comment by NicolasHug** [comment]
Try this and tell me how it goes

    from __future__ import (absolute_import, division, print_function,
                            unicode_literals)
    
    import pandas as pd
    
    from surprise import SVD
    from surprise import dataset
    from surprise import Reader
    from surprise import evaluate, print_perf
    
    
    # DF creation. Replace this by your own df
    ratings_dict = {'userID': [9, 32, 2, 45, 1],
                    'itemID': [1, 1, 1, 2, 2],
                    'rating': [3, 2, 4, 3, 1]}
    df = pd.DataFrame.from_dict(ratings_dict)
    
    # You'll need to create a dummy reader
    reader = Reader(line_format='user item rating', rating_scale=(1, 5))
    
    # Also, a dummy Dataset class
    class MyDataset(dataset.DatasetAutoFolds):
    
        def __init__(self, df, reader):
    
            self.raw_ratings = [(uid, iid, r, None) for (uid, iid, r) in
                                zip(df['userID'], df['itemID'], df['rating'])]
            self.reader=reader
    
    data = MyDataset(df, reader)
    
    # You should now be able to use the data object normally.
    data.split(n_folds=3)
    algo = SVD()
    perf = evaluate(algo, data, measures=['RMSE', 'MAE'])
    print_perf(perf)

Hope it helps,
Nicolas

**Comment by longhowlam** [comment]
Thanks for your example, it works. I'll use it on bigger pandas rating data later

**Comment by NicolasHug** [comment]
Great, I'll close the issue. Don't hesitate to come back to me if you you encounter any problem.

**Comment by NicolasHug** [comment]
Update on this:

I justed pushed 757c9a1 which allows to load a dataset from a pandas dataframe much more easily. This will be available in the next release (or right now if you clone the repo).

See [the latest docs](http://surprise.readthedocs.io/en/latest/getting_started.html#load-from-df-example) for an example!

Nicolas

**Comment by yustiks** [comment]
I had similar issue. 
What helped was replacing data reading in the following format:
```
reader = Reader(line_format = 'user item rating', rating_scale=(0,5))
data = Dataset.load_from_df(sample_clean [['userId', 'productId', 'Score']], reader)
```
