### ISSUE TITLE
I need to get similarity score when calling get_neighbors()

### ISSUE THREAD

**Issue by michelliming** [NicolasHug/Surprise#200]

**Comment by michelliming** [comment]
how can I get the similarity score?

**Comment by NicolasHug** [comment]
Use the self.sim attribute

**Comment by michelliming** [comment]
Can have a sample  for  using self.sim to get the similarity score?

**Comment by michelliming** [comment]
for example, get the topN similar item and the score. Best using item based cf, for each user, can get topN item and score

**Comment by NicolasHug** [comment]
Please check the faq
