### ISSUE TITLE
Train and test set sizes from train_test_split()

### ISSUE THREAD

**Issue by anargyri** [NicolasHug/Surprise#201]
#### Description
The training and test sizes obtained from `train_test_split()` are sometimes funny. This looks like a rounding issue (taking a ceil instead of round, for example).

#### Steps/Code to Reproduce

```
In [1]: from surprise import Dataset, Reader

In [2]: from surprise.model_selection import train_test_split

In [4]: import pandas as pd

In [9]: reader = Reader(rating_scale=(1,5))

In [13]: df = pd.DataFrame(
    ...:     data=[(0, 0, 4.0), (0, 1, 2.0), (1, 1, 3.0), (1, 2, 4.0), (2, 1, 1.0), (2, 2, 5.0), (2, 3, 4.0), (3, 1,
    ...:  2.0), (4, 4, 5.0), (4, 1, 1.0)],
    ...:     columns=["user", "item", "rating"])
    ...:
    ...:

In [15]: df.shape
Out[15]: (10, 3)

In [16]: data = Dataset.load_from_df(df, reader)

In [17]: data.df.shape
Out[17]: (10, 3)

In [18]: train_test_split(data, test_size=0.3)
Out[18]:
(<surprise.trainset.Trainset at 0x1e2c5f811d0>,
 [(0, 0, 4.0), (4, 1, 1.0), (2, 3, 4.0)])

In [19]: train_test_split(data, test_size=0.30000001)
Out[19]:
(<surprise.trainset.Trainset at 0x1e2c5f810b8>,
 [(1, 1, 3.0), (2, 3, 4.0), (0, 0, 4.0), (1, 2, 4.0)])
```

#### Expected Results

Out of 10 samples in `data` I would expect to have 3 samples in the test set, when the ratio is 0.30000001. 

#### Actual Results

I get 4 samples instead. 

#### Versions

Windows-10-10.0.16299-SP0
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
surprise 1.0.6

**Comment by NicolasHug** [comment]
Why would you expect 3 samples rather than 4? It seems to me that it's just a convention whether we should consider '3.0000001' samples as 3 samples or as 4 samples.

The code for splitting the dataset was strongly inspired from that of scikit-learn and they give similar results:

```
from sklearn.model_selection import train_test_split                              
import numpy as np                                                                
                                                                                  
print(train_test_split(np.arange(10), test_size=.3))                              
print(train_test_split(np.arange(10), test_size=.300000001)) 
```
```
[array([8, 9, 3, 6, 7, 2, 0]), array([5, 4, 1])]
[array([7, 5, 4, 1, 8, 0]), array([9, 2, 6, 3])]
```

**Comment by anargyri** [comment]
I see, conformity with `scikit-learn` is a good argument.

That said, I would argue that most people's intuition is that 3 out of 10 is closer to 0.3000001 than 4 out of 10 is. To put it another way, assigning the data samples into the test set with probability = 0.3000001 will give you 3 out of 10 more often than 4 out of 10. This is close to what e.g. `randomSplit()` in `pyspark` gives (which could lead to different test set sizes though).

Another reason is that you may get unexpected behavior due to rounding error. For example, 1.0 - 0.7 gives 0.30000000000000004 in my python installation and hence
```
In [10]: train_test_split(data, test_size=1.0 - 0.7)
Out[10]:
(<surprise.trainset.Trainset at 0x298af1d8278>,
 [(4, 4, 5.0), (3, 1, 2.0), (2, 3, 4.0), (1, 2, 4.0)])
```

**Comment by anargyri** [comment]
True, there is a way of getting the expected behavior:
```
In [25]: train_test_split(data, test_size=None, train_size=0.7)
Out[25]:
(<surprise.trainset.Trainset at 0x298af5c2080>,
 [(0, 0, 4.0), (1, 1, 3.0), (2, 2, 5.0)])
```

But I find some other results unexpected. I would expect these two calls to give an error (since 0.2 + 0.7 < 1):
```
In [23]: train_test_split(data, train_size=0.7)
Out[23]: (<surprise.trainset.Trainset at 0x298af557a20>, [(1, 1, 3.0), (1, 2, 4.0)])

In [29]: train_test_split(data, test_size=0.2, train_size=0.7)
Out[29]: (<surprise.trainset.Trainset at 0x298af4ae630>, [(3, 1, 2.0), (0, 0, 4.0)])
```
whereas this one should not in theory (but could in practice because of numerical error). 
```
In [24]: train_test_split(data, test_size=1.0 - 0.7, train_size=0.7)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-d985c3667102> in <module>()
----> 1 train_test_split(data, test_size=1.0 - 0.7, train_size=0.7)

~\AppData\Local\Continuum\Anaconda3\envs\airship\lib\site-packages\surprise\model_selection\split.py in train_test_split(data, test_size, train_size, random_state, shuffle)
    332     ss = ShuffleSplit(n_splits=1, test_size=test_size, train_size=train_size,
    333                       random_state=random_state, shuffle=shuffle)
--> 334     return next(ss.split(data))
    335
    336

~\AppData\Local\Continuum\Anaconda3\envs\airship\lib\site-packages\surprise\model_selection\split.py in split(self, data)
    274
    275         test_size, train_size = self.validate_train_test_sizes(
--> 276             self.test_size, self.train_size, len(data.raw_ratings))
    277         rng = get_rng(self.random_state)
    278

~\AppData\Local\Continuum\Anaconda3\envs\airship\lib\site-packages\surprise\model_selection\split.py in validate_train_test_sizes(self, test_size, train_size, n_ratings)
    258                              'should be smaller than the number of '
    259                              'ratings {1}.'.format(train_size + test_size,
--> 260                                                    n_ratings))
    261
    262         return int(train_size), int(test_size)

ValueError: The sum of train_size and test_size (11) should be smaller than the number of ratings 10.

```
The user expects a consistent behavior whenever test size + train size != 1 regardless whether it is < or > 1.

**Comment by NicolasHug** [comment]
I agree that the last example is a bit unsettling from a user point of view, but like you said it's because of floating error and there's not much we can do about it. The current API allows to  avoid those errors so I guess this is good enough.

But for the other, I think that there's no reason to force train_set_size + test_set_size to be dataset_size. If the user wants to make some experiments on a subset of their data, they should be able to do it. For example, they could want to experiment with a fixed train_set_size and test on different test_set_sizes.
