### ISSUE TITLE
Typo in docs for k-NN basic

### ISSUE THREAD

**Issue by dorukkilitcioglu** [NicolasHug/Surprise#203]
Hi,

The rating prediction equation for item-based [basic k-NN](https://surprise.readthedocs.io/en/stable/knn_inspired.html#surprise.prediction_algorithms.knns.KNNBasic) seems to have a typo in the denominator. The sum should be over the neighbors of `i`, not `j` (as it is in the numerator).

I can send a PR for it, but it is literally a single letter difference, so I thought I should open up an issue instead.

**Comment by NicolasHug** [comment]
God catch, thanks!
There's the same typo in [Knn Baseline](https://surprise.readthedocs.io/en/stable/knn_inspired.html#surprise.prediction_algorithms.knns.KNNBaseline) as well.
A PR would be welcome :)
