### ISSUE TITLE
unable to use surprise in anaconda3.6

### ISSUE THREAD

**Issue by sukalyanM** [NicolasHug/Surprise#21]
I want to use surprise..I have anaconda3.6..unable to install it through pip install surprise

**Comment by NicolasHug** [comment]
Could you please be more specific? 

Also, please read the [install guidelines](https://github.com/NicolasHug/Surprise#installation--usage) because ` pip install surprise` is not how you do it.

**Comment by sukalyanM** [comment]
I had use pip install scikit-surprise.

**Comment by NicolasHug** [comment]
Still can't help you without the error message.

**Comment by NicolasHug** [comment]
Where you able to use Surprise? If so, can I close the issue?

**Comment by esazjue** [comment]
Hi,

Similar issue here. Everytime I try to install the package with **pip install scikit-surprise**, I got this error:

  File "C:\Conda3\lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
    raise ValueError("Unknown MS Compiler version %s " % msc_ver)
ValueError: Unknown MS Compiler version 1900

I'm using latest Anaconda:  Python 3.6.1 |Anaconda custom (64-bit)| (default, Mar 22 2017, 20:11:04) [MSC v.1900 64 bit (AMD64)] on win32

Let me know if you need further information.

Thanks in advance.

**Comment by NicolasHug** [comment]
Hi esazjue,

Thanks for the error message. This is most likely an issue related to cygwin and your development environement on Windows, I'm not sure I can do change anything on Surprise to avoid it.

Have you tried to google the error message? I stumbled upon [this thread](https://bugs.python.org/issue25251), maybe that will help?

Nicolas

**Comment by sukalyanM** [comment]
Hello Nicholas.,
I got error message of Visual studio C++2014 not installed..
I think, if i download it from python tool kit.. Thn i resolve this issue.

Thanks
Sukalyan

**Comment by NicolasHug** [comment]
Hi,

Well yes you should probably install VS then...

Surprise uses [Cython](http://cython.org), which requires a C compiler to be installed on the system. This is where both of your issues come from apparently.

Nicolas

**Comment by esazjue** [comment]
Hi Nicolas,

Thanks for your quick reply, I'm sure it's not related with your package but I wondered if the error was common for others. I've checked similar webpages but the provided solution didn't work for me. I'll have a go with the one you suggested. 

Juan

**Comment by esazjue** [comment]
Hi, 

I managed to install Surprise following the instructions here https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/yLH46ilPQeo

Juan

**Comment by NicolasHug** [comment]
Fantastic, thanks for the feedback

**Comment by NicolasHug** [comment]
@sukalyanM as your problem is not related to Surprise I'll close the issue if you're OK?

**Comment by sukalyanM** [comment]
Yes.. Thnkz a lot

**Comment by oin156** [comment]
![surprise error](https://user-images.githubusercontent.com/45845851/52330936-c8edf680-2a1c-11e9-867a-a12326b70a4d.jpg)


Hi, I am facing this error while installing the surprise library. Can you help??

**Comment by aritra-2020** [comment]
![Capture](https://user-images.githubusercontent.com/66193793/83344804-657e8b00-a329-11ea-905d-7d25488ead81.JPG)
Unable to 'pip install scikit-surprise' using Anaconda Prompt(Anaconda3).

**Comment by siddarth308** [comment]
> ![Capture](https://user-images.githubusercontent.com/66193793/83344804-657e8b00-a329-11ea-905d-7d25488ead81.JPG)
> Unable to 'pip install scikit-surprise' using Anaconda Prompt(Anaconda3).

Same issue.. Need HELP!

**Comment by ajithelamkulam** [comment]
Same issue

**Comment by ajithelamkulam** [comment]
![image](https://user-images.githubusercontent.com/71301362/116789800-58849180-aace-11eb-8e1d-2f20adc3f119.png)
![image](https://user-images.githubusercontent.com/71301362/116789811-63d7bd00-aace-11eb-9652-543158b18bc4.png)

**Comment by amrohit** [comment]
You need to download vs build tool from here
https://visualstudio.microsoft.com/visual-cpp-build-tools/
and then downoad c++ libs. you can google it
