### ISSUE TITLE
RuntimeWarning:algobase.py

### ISSUE THREAD

**Issue by ngovind93** [NicolasHug/Surprise#214]
#### Description
am getting the RuntimeWarning: Invalid Value Encountered in Sqrt
algobase.py 294.   " sim = construction_func[name] (*args)"
am using the jester dataset 25k users,100 items,1.8M ratings

**Comment by ngovind93** [comment]
###

**Comment by NicolasHug** [comment]
Please provide [self-contained example code](https://stackoverflow.com/help/mcve), including imports and data (if possible), so that other contributors can just run it and reproduce your issue. Ideally your example code should be minimal.

**Comment by NicolasHug** [comment]
I don't have enough ram to run your example. I tried with half of the data and didn't get any warning (apart from the reader warning). Same with user_based=False

Can you provide a smaller dataset that reproduces the issue?

Have you got the latest version?

Friendly advice: looks like you're using python 2, you should be using Python 3

**Comment by ngovind93** [comment]
Thank you for immediate reply.
with python 3  am getting this message
Computing the pearson similarity matrix......
Killed

**Comment by ngovind93** [comment]
with python2 am getting this:

Computing the pearson similarity matrix...
/home/mc16pc06/.local/lib/python2.7/site-packages/surprise/prediction_algorithms/algo_base.py:294: RuntimeWarning: invalid value encountered in sqrt
  sim = construction_func[name] (*args)

**Comment by NicolasHug** [comment]
you killed the process yourself?

Try with less data and see if you can reproduce the issue.

**Comment by ngovind93** [comment]
I have not killed the process.
may be due to huge data it may be killed. but am not able to get anything from that.

**Comment by NicolasHug** [comment]
The way pearson similarity is computed can be numerically unstable, so maybe you're encountering one of those issues. If it's just a warning and you still get decent results, I would suggest ignoring it. You can also try another similarity measure.

That being said, you're computing a similarity matrix between 25k users, that's a matrix with 625 millions entries. Surprise isn't that scalable, and in general neighborhood approaches aren't recommended when you have a lot of data. You probably want to try other models that are much more scalable, such as SVD. Or, ss you have much less items, it could be more appropriate to use an item-based similarity.

**Comment by ngovind93** [comment]
But I need to work with only pearson similarity only. can you help by fixing this issue.

**Comment by NicolasHug** [comment]
Sorry, unless you want to investigate this issue yourself and propose a fix, I won't have time to track it down further.

**Comment by ngovind93** [comment]
it says a "RuntimeWarning: invalid value encountered in sqrt" .  what i expect is some negative values are into the sqrt function. so, i think this issue can be solved by you. 
anyhow, am running it on a server. so, no memory issues . only this issue.

**Comment by NicolasHug** [comment]
Closing this issue, I opened #216 because this may be a legit bug.

Friendly advice: please don't treat open source contributors like they're supposed to do your homework.

**Comment by ngovind93** [comment]
> 
> 
> Closing this issue, I opened #216 because this may be a legit bug.
> 
> Friendly advice: please don't treat open source contributors like they're supposed to do your homework.

sorry, if it looks like that.

**Comment by NicolasHug** [comment]
it really does, at least in you previous comment that you have now deleted

**Comment by ngovind93** [comment]
actually I don't mean that, just i thought to inform you.
