### ISSUE TITLE
[Feature Request] Recommendation strategy to recommend the items with the 10 highest estimation

### ISSUE THREAD

**Issue by adideshp** [NicolasHug/Surprise#22]
Hi Nicolas,
                I have been using the Surprise Package for a few days now. Great job +1: 
In your todo list, you have an item **"Implement some recommendation strategy (like recommend the items with the 10 highest estimation)"**. Do you have an idea as to when it will be released, approximately? Any info in regards to this would be really helpful.

What would be your basic strategy to implement this feature?

I wrote a function for SVD to return a list of top K recommendations. I follow these steps to get the list,
1. Iterate through all items for a specific user
2. Run predict function for items that don't have a rating ( Item for a user without rating)
3. Sort top K and return them as recommendations.

However, the function is returning same or almost similar 10 / 20 recommendations irrespective of the user. 

Is the above strategy wrong? Any thoughts on why I am getting almost similar recommendations?

Thanks :)

**Comment by NicolasHug** [comment]
Hi Aditya, and thanks for the feedback.

I will most likely get back to the dev in a few weeks now.

To get the Top K recommendations, I would do something like this:

  * Compute all the predictions you need and put them in a prediction list, just like one returned by the `test` method.
  * Then for a given user, find the predictions where the estimated rating is the highest.

You can also retrieve the top k predictions for all users at once. I've written a small example that does this:


    from __future__ import (absolute_import, division, print_function,
                            unicode_literals)
    from collections import defaultdict
    
    from surprise import SVD
    from surprise import Dataset
    
    
    def get_top_k(predictions, k):
        '''Return a top_k dicts where keys are user ids and values are lists of
        tuples [(item id, rating estimation) ...].
    
        Takes in a list of predictions as returned by the test method.
        '''
    
        # First map the predictions to each user.
        top_k = defaultdict(list)
        for uid, iid, true_r, est, _ in predictions:
            top_k[uid].append((iid, est))
    
        # Then sort the predictions for each user and retrieve the k highest ones.
        for uid, user_ratings in top_k.items():
            user_ratings.sort(key=lambda x:x[1], reverse=True)
            top_k[uid] = user_ratings[:k]
    
        return top_k
    
    
    data = Dataset.load_builtin('ml-100k')
    trainset = data.build_full_trainset()
    
    algo = SVD()
    algo.train(trainset)
    
    # We are here testing on the WHOLE dataset. Which means that all the ratings we
    # are predicting are already known, but it does not really matter.
    testset = data.construct_testset(raw_testset=data.raw_ratings)
    predictions = algo.test(testset)
    
    top_k = get_top_k(predictions, 10)
    
    # Print the recommended items
    for uid, user_ratings in top_k.items():
        print(uid, [iid for (iid, _) in user_ratings])
    
    
    
    # Compute the total number of recommended items.
    all_recommended_items = set(iid for (_, user_ratings) in top_k.items() for
                                (iid, _) in user_ratings)
    
    print('Number of recommended items:', len(all_recommended_items), 'over',
          len(top_k), 'users')


I obtain a total of about 420 recommended items (with k = 10), which seems fair.

I'm not sure I understand your steps correctly... Once thing is certain though: if you are predicting the ratings of some items that have not been rated by anybody (or for a user that has no rating), then SVD cannot output a prediction, so the estimation is set to the average of all the ratings. This may explain the fact that all of your recommendations are the same?

Hope this helps, don't hesitate to come back to me.

Nicolas

**Comment by adideshp** [comment]
Hi Nicolas,
                Thanks a lot for the help :) .I am unable to understand the reason behind creating a testset which is same as the trainset. I am trying to write a top K recommendation function that returns a list of movies that a user has not yet seen. 

Using your code (Thanks for the code snippet) I created a new testset generation function `create_testset(trainset, user_reverse_map, item_reverse_map)` that creates a testset from the items a user has not yet rated. 

I tested the code using this `create_testset` function. 

```
def generate_reverse_maps(trainset):
  '''Generate reverse maps i.e inner_id --> raw_id for item and user '''
    user_reverse_map ={}
    item_reverse_map = {}
    for orig_user_id in trainset._raw2inner_id_users.keys():
        user_reverse_map[trainset._raw2inner_id_users[orig_user_id]] = orig_user_id

    for orig_item_id in trainset._raw2inner_id_items.keys():
        item_reverse_map[trainset._raw2inner_id_items[orig_item_id]] = orig_item_id

    return user_reverse_map, item_reverse_map


def create_testset(trainset, user_reverse_map, item_reverse_map):
    '''Returns a list of (user, item, rating) tuples for all the items that the user has not rated
    Computes this for all the users and items in the trainset (As trainset comprises of complete data)
    '''
    testset = []
    for user in trainset.all_users():
        for item in trainset.all_items():
            item_rating_tuple = [val for val in trainset.ur[user] if val[0] == item]
            if len(item_rating_tuple) == 0:
                tuple = (user_reverse_map[user], item_reverse_map[item], trainset.global_mean)
                testset.append(tuple)
    return testset
```
After returning the recommended items, they appear similar. Here are some of the results,
- 485 [u'408', u'169', u'1449', u'483', u'318', u'513', u'114', u'64', u'603', u'178']
- 484 [u'408', u'169', u'1449', u'483', u'64', u'114', u'603', u'513', u'178', u'12']
- 483 [u'64', u'408', u'174', u'169', u'272', u'483', u'127', u'603', u'98', u'302']
- 482 [u'408', u'169', u'1449', u'483', u'318', u'64', u'114', u'603', u'513', u'178']
- 481 [u'408', u'169', u'1449', u'483', u'64', u'114', u'513', u'603', u'178', u'657']
- 480 [u'408', u'1449', u'318', u'513', u'178', u'657', u'480', u'474', u'357', u'134']
- 472 [u'302', u'474', u'98', u'515', u'427', u'480', u'479', u'272', u'483', u'408']
- 473 [u'408', u'169', u'1449', u'483', u'513', u'318', u'114', u'64', u'603', u'657']
- 470 [u'318', u'408', u'64', u'169', u'12', u'483', u'603', u'114', u'1449', u'178']
- 471 [u'408', u'318', u'169', u'64', u'483', u'12', u'603', u'1449', u'114', u'178']
- 476 [u'408', u'169', u'318', u'483', u'1449', u'64', u'114', u'603', u'513', u'12']
- 477 [u'242', u'302', u'474', u'265', u'86', u'486', u'144', u'246', u'98', u'193']
- 474 [u'408', u'169', u'1449', u'114', u'272', u'251', u'223', u'320', u'656', u'189']
- 475 [u'408', u'169', u'318', u'483', u'1449', u'64', u'114', u'603', u'513', u'178']
- 478 [u'408', u'169', u'483', u'603', u'1449', u'114', u'480', u'513', u'174', u'127']
- 479 [u'1449', u'513', u'114', u'657', u'603', u'178', u'64', u'12', u'963', u'134']

Number of recommended items: 110 over 943 users

110 items for  943 users is not diverse enough. Also the lists that looks different are essentially the same because of the minute difference in the predicted ratings.
eg: user 470 and 471 have the same items recommended. The difference between them is very minute (upto third decimal place).

I am unable to figure out how to get unique recommendations for each user using just SVD. Are these results expected? I would love to hear your thoughts on this :)

Thanks 
Aditya

**Comment by NicolasHug** [comment]
Aditya,

I'll get back to you with more feedback tomorrow, but I believe the only way to find out if 110 items is not enough would be to try some other prediction algorithms and compare them. 

One remark though, is that the SVD algorithm was not designed to produce diverse recommendation, but rather to have an excellent RMSE score. It was designed during the Netflix Prize where the goal was to have the lowest possible RMSE,and it is clear that the loss function that is optimized is engineered towards RMSE, not towards diverse recommendations.

**Comment by adideshp** [comment]
Hi Nicolas,
                 Thanks for your response. I was trying to debug this issue further and I found that for each user(u) and item(i) the pu factors and qi factors are exactly the same. 
Is this expected? I am not sure, but it feels wrong.

Please let me know what you think.

-Aditya

Trace of some values of qi and pu for SVD on MovieLens-100k dataset:
```
(Pdb) algo.qi[1]
array([ 0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978,
        0.11516978,  0.11516978,  0.11516978,  0.11516978,  0.11516978])
(Pdb) algo.qi[2]
array([ 0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209,
        0.0864209,  0.0864209,  0.0864209,  0.0864209,  0.0864209])
(Pdb) algo.pu[1]
array([ 0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986,
        0.07141986,  0.07141986,  0.07141986,  0.07141986,  0.07141986])
(Pdb) algo.pu[2]
array([ 0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515,
        0.00408515,  0.00408515,  0.00408515,  0.00408515,  0.00408515])
```

**Comment by NicolasHug** [comment]
Well in fact this is both wrong and right (but mostly wrong)...

It comes from the fact that all the factors are initialized with the same value `0.1`. This is what was recommended by Funk in [his post](http://sifter.org/~simon/journal/20061211.html) so I followed it, but the fact is that Funk's algorithm is slightly different than what is referred to now as 'SVD'. In the current version, if all factors are initialized at the same value then the update rule will be such that they will stay the same for each user and item.

You are right that this feels wrong, the factors should be randomly initialized here. I will fix this first time tomorrow, as this is quite a bad issue. I'll also take a look at your previous post.

Thank you for pointing that out!
Nicolas

**Comment by NicolasHug** [comment]
Hi Aditya, 

Coming back to you on this. 

> I am unable to understand the reason behind creating a testset which is same as the trainset

No particular reason, it was just easier to do it this way to test the `get_top_k` function. Your scenario using `create_testset` is much more meaningful obviously. I've checked your code and as far as I can tell it is correct.

I've just changed the SVD and SVD++ initialization, and pushed it to the repo (see the [latest doc](http://surprise.readthedocs.io/en/latest/matrix_factorization.html#surprise.prediction_algorithms.matrix_factorization.SVD)).

I now obtain about 290 recommended items using SVD. When using the previous initialization scheme (`init_mean = 0.1`, `init_std_dev=10E-10`), I also get about 110 item so our result are consistent.

I also tested other algorithms:

 * The `BaselineOnly` algorithm has absolutely **no** recommendation (due to its nature), and I get about 70 recommended items.
 * The `KNNBaseline` algorithm (using pearson similarity), which should have a good recommendation power, and I also get about 290 recommended items. So SVD's score is probably not that bad (now that it has been corrected ;) )


As a side note, I don't know if you encountered a problem related to this but the [current doc](http://surprise.readthedocs.io/en/v1.0.2/predictions_module.html#surprise.prediction_algorithms.predictions.Prediction) about the `Prediction` object is incorrect: user and item ids are **raw** ids, and not inner ids as mentioned. It has been corrected in the [latest version](http://surprise.readthedocs.io/en/latest/predictions_module.html).

Nicolas

**Comment by adideshp** [comment]
Hi Nicolas,
                Thanks a lot for looking into the code and a responding quickly :)
I am wondering If the random initialization fixes the problem. Randomizing would add a random offset to the feature values and this offset would then be carried till the end. Before the fix, all the feature values were same, for a user. Now they would differ by a random number, but shouldn't the update 
be a true representation of where a user lies in the n dimensional space of factors. I mean, Shouldn't these factors be independent of their initialization?

I verified this by initializing all the factors with the function below in the SVD algorithm,

These functions add 0.1 to every factor incrementally, for user and item
```
       for u in trainset.all_users():
            step = 0.1
            increment = 0.1
            for f in range(self.n_factors):
                pu[u,f] = increment
                increment +=step

        for i in trainset.all_items():
            step = 0.1
            increment = 0.1
            for f in range(self.n_factors):
                qi[i,f] = increment
                increment +=step
```
The results is as below,
```
algo.pu[0]
array([ 0.00508238,  0.01016475,  0.01524713,  0.02032951,  0.02541189,
        0.03049426,  0.03557664,  0.04065902,  0.0457414 ,  0.05082377,
        0.05590615,  0.06098853,  0.0660709 ,  0.07115328,  0.07623566,
        0.08131804,  0.08640041,  0.09148279,  0.09656517,  0.10164755])
(Pdb) algo.qi[0]
array([ 0.07762173,  0.15524347,  0.2328652 ,  0.31048694,  0.38810867,
        0.46573041,  0.54335214,  0.62097387,  0.69859561,  0.77621734,
        0.85383908,  0.93146081,  1.00908254,  1.08670428,  1.16432601,
        1.24194775,  1.31956948,  1.39719122,  1.47481295,  1.55243468])
```

As you can see here, there is a linear difference between each factor here. I didn't find any article or paper that explains how these factors would be computed independent of the initialization. Is this a drawback of SGD based SVD (Funk SVD)? 

I would like to hear your thoughts on this :)

**Comment by NicolasHug** [comment]
Hi Aditya,

Yes indeed, for a given user (or item) the difference between its factors will be the same before **and** after the SGD procedure.

I never really thought of this TBH, but it does seem like a weird thing. I may have completely screwed up the implementation of the algorithm, but I think I stricktly followed what is explained in the papers of the BellKor team (see the refs on the doc). To my knowledge, this is never discussed in any paper.

When I was coding the algorithm, I made  a quick note in the [source code](https://github.com/NicolasHug/Surprise/blob/master/surprise/prediction_algorithms/matrix_factorization.pyx#L140) about the different techniques. In his [initial post](http://sifter.org/~simon/journal/20061211.html), Funk iteratively fits the factors one by one, so his algorithm should not have this issue.

**Comment by adideshp** [comment]
Hi Nicolas,
                 I am trying to debug the code using pydev on eclipse but I am unable to step into matrix_factorization.pyx files. Are you aware of or have you used any debugger to debug the .pyx code?

-Aditya

**Comment by adideshp** [comment]
Or do you have a uncythonized version of the code

Thanks :)

**Comment by NicolasHug** [comment]
Hi Aditya,

I've never used it but there's apparently [a way](http://cython.readthedocs.io/en/latest/src/userguide/debugging.html) to debug the Cython code. 

Iif you need to *decythonize* the code, you can do it very easily I think: just remove all the variable declarations (stuff like `cdef foo`), and put the algorithm in another file.

Are you looking for something in particular in the code? BTW if you find anything suspicious please tell me ;)!

**Comment by NicolasHug** [comment]
Hi Aditya,

I just released a new version of Surprise. Retrieving the Top-N recommendations is now much easier, and I wrote a small [FAQ entry](http://surprise.readthedocs.io/en/stable/FAQ.html#how-to-get-the-top-n-recommendations-for-each-user) about this.

This is still not a built-in feature but I believe it does the job. I don't want to 'officially' implement evaluation measures related to Top-N recommendation (like precision, recall, AUC etc.) because I will soon work on implicit datasets and those things may change a lot.

Can I close this issue?

Also, have you found something interesting about SVD when debugging the Cython code?

Thanks!
Nicolas

**Comment by adideshp** [comment]
Hi Nicolas,
                  Yes, I will close the issue :) I implemented the Funk's version of SVD, with factor calculation loop at the beginning for testing. I wanted to debug the implementation and hence needed a way to debug the cython code. 

Thanks a lot for your help :)

**Comment by vietvudanh** [comment]
@NicolasHug I have read about this in FAQ and sample code, but I have problem with larger dataset : n_users=5000, n_items=8000, ratings=60000, that mean testset is a 46M list.

Is there any built in or quick way to do this? Since running the `algo.test(testset)` easily occupy all my memory and took a hell of time (I had to cancel it since took too  much time)

If not, then I will need to batch the test set into smaller batch and maybe using `multiprocessing`?
