### ISSUE TITLE
Customize dataset without rating

### ISSUE THREAD

**Issue by navy-xie** [NicolasHug/Surprise#220]
Hi Hug,

Thanks for your great job, and I learned a lot from your project.
I am wondering if it is possible to custom dataset without rating data.

I read your doc carefully about how to use my custom dataset, https://surprise.readthedocs.io/en/stable/getting_started.html#use-a-custom-dataset, however my dataset does not contain rating data. I also tried to add a new column as rating with all 5, but the fitting and testing are all 0.

Did I miss any info to use your lib correctly?

Thanks a lot!
Navy

**Comment by NicolasHug** [comment]
Surprise only supports explicit ratings, not implicit ratings. Try looking at other libraries like LightFM or implicit.

**Comment by navy-xie** [comment]
On Oct 22, 2018, at 9:12 PM, Nicolas Hug <notifications@github.com> wrote:

Surprise only supports explicit ratings, not implicit ratings. Try looking at other libraries like LightFM or implicit.

Got it. Thank you very much for your reply.
