### ISSUE TITLE
Unable to get the correct similarity Values

### ISSUE THREAD

**Issue by ngovind93** [NicolasHug/Surprise#224]
am using the code below and using the dataset https://github.com/ngovind93/Recommender/blob/master/toydataset.txt

This is example dataset from c.aggarwal book pg.no 34 table 2.1. the pearson similarity values are not matching when I run.

a slight modification done in knns.py to view the similarity values, in def estimate(self,u,i)

details = {'actual_k': actual_k,'neigh':k_neighbors}

```
from surprise import KNNBasic
from surprise import Dataset
 from surprise import Reader
import os
file_path = os.path.expanduser('toydataset.txt')
reader = Reader(line_format='user item rating ', sep=' ',rating_scale=(1,10))
data = Dataset.load_from_file(file_path, reader=reader)
trainset = data.build_full_trainset()
sim_options={'name':'pearson','min_support':1,'user_based':True}
algo = KNNBasic(sim_options=sim_options,verbose=True)
algo.fit(trainset)
uid=str(3)
iid=str(6)
pred = algo.predict(uid,iid , r_ui=None, verbose=True)

```

am getting this result:

Computing the pearson similarity matrix...
Done computing similarity matrix.

user: 3          item: 6          r_ui = None   est = 4.00   {u'actual_k': 2, u'was_impossible': False, u'neigh': [(0.9707253433941511, 4.0), (0.8944271909999159, 4.0), (-0.8660254037844387, 3.0), (-1.0, 3.0)]}

**Comment by NicolasHug** [comment]
Hi,
What are the expected values and what is the formula that is used in the book? There are a lot of different versions of similarity metrics when it comes to recommender systems

**Comment by NicolasHug** [comment]
Also in your file 4 6 3 should be 4 6 4 (there might be other errors that I didn't spot)

**Comment by ngovind93** [comment]
Hi NicolasHug,
thanks for the immediate reply.

the expected values and formula use are here
https://github.com/ngovind93/Recommender/blob/master/example%202.1.png
https://github.com/ngovind93/Recommender/blob/master/pearson%20example.png

**Comment by NicolasHug** [comment]
The .8944271909999159 value seems correct.

Have you fixed your data and checked again?

**Comment by ngovind93** [comment]
yes, I fixed the data and tried. Getting the same values as above. anyhow 4 is not chosen due to -ve value.

one value you mentioned is correct.

**Comment by NicolasHug** [comment]
Sorry, due to what?

**Comment by ngovind93** [comment]
negative similarity value.

**Comment by NicolasHug** [comment]
I've re-written (hacky) the pearson computation with the way it's done in surprise (see [here](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#For_a_sample) for details) and with the *standard* formula.

Both are equivalent, up to numerical instability. With the standard method I get values close to that of the book, and with the other one I get values close to that of surprise. Unfortunately the *standard* formula is very slow to compute compared to the other one.

So I believe the discrepancies we're observing come from the numerical instability of the used formula. My take is that even if it's not as accurate, the respective order of the similarities will be kept intact, which is what ultimately matters.

Thanks for bringing this to my attention. There's already an issue for the numerical instability in pearson (#216) so if you don't mind I'll close this one.

```python
import os

import numpy as np
from surprise import KNNBasic
from surprise import Dataset
from surprise import Reader

file_path = os.path.expanduser('toydataset.txt')
reader = Reader(line_format='user item rating ', sep=' ',rating_scale=(1,7))
data = Dataset.load_from_file(file_path, reader=reader)
trainset = data.build_full_trainset()
sim_options={'name':'pearson','min_support':1,'user_based':True}
algo = KNNBasic(sim_options=sim_options,verbose=True)
algo.fit(trainset)

def rating(u, i):
    # return r_ui
    return next(r for (j, r) in trainset.ur[u] if j == i)

def pearson_like_surprise(u, v):
    # computation like in surprise

    items_u = {i for (i,_ ) in trainset.ur[u]}
    items_v = {i for (i,_ ) in trainset.ur[v]}
    common = items_u & items_v
    n = len(common)

    sum_u = sum(rating(u, i) for i in common)
    sum_v = sum(rating(v, i) for i in common)

    num = n * sum(rating(u, i) * rating(v, i) for i in common)
    num -= sum_u * sum_v
    a = n * sum(rating(u, i)**2 for i in common) - sum_u**2
    b = n * sum(rating(v, i)**2 for i in common) - sum_v**2
    denum = np.sqrt(a) * np.sqrt(b)
    return num / denum

def pearson_std_formula(u, v):
    # standard formula
    mu = {}
    for user, ratings in trainset.ur.items():
        mu[user] = np.mean([r for (_, r) in ratings])

    items_u = {i for (i,_ ) in trainset.ur[u]}
    items_v = {i for (i,_ ) in trainset.ur[v]}
    common = items_u & items_v

    num = sum((rating(u, i) - mu[u]) * (rating(v, i) - mu[v])
              for i in common)
    a = sum((rating(u, i) - mu[u])**2 for i in common)
    b = sum((rating(v, i) - mu[v])**2 for i in common)
    denum = np.sqrt(a) * np.sqrt(b)
    return num / denum

three = trainset.to_inner_uid(str(3))
for other in range(1, 6):
    other = trainset.to_inner_uid(str(other))
    print(algo.sim[three, other])
    print(pearson_like_surprise(three, other))
    print(pearson_std_formula(three, other))
    print('-')
```

output:

```
0.8944271909999159
0.8944271909999159
0.8944271909999159
-
0.9707253433941511
0.9707253433941511
0.9384742644069303
-
1.0
1.0
1.0
-
-1.0
-1.0
-1.0
-
-0.8660254037844387
-0.8660254037844387
-0.8164965809277259

```

data:
<details>
```
1 1 7
1 2 6
1 3 7
1 4 4
1 5 5
1 6 4
2 1 6
2 2 7
2 4 4
2 5 3
2 6 4
3 2 3
3 3 3
3 4 1
3 5 1
4 1 1
4 2 2
4 3 2
4 4 3
4 5 3
4 6 4
5 1 1
5 3 1
5 4 2
5 5 3
5 6 3

```
</details>

**Comment by ngovind93** [comment]
Hi NicolasHug,
thank you for quick response and clear explanation.

**Comment by NicolasHug** [comment]
You'll need to change the similarity.pyx file, among other things. Though I would not recommend this as this is Cython code and requires a little bit of experience.

Maybe the best way to go would be to compute the `sim` matrix yourself and plug it back when you want to do the predictions

**Comment by ngovind93** [comment]
Hi NicolasHug,
my one more request is can you give Cython code of standard Pearson similarity for me. 
Thak you

**Comment by NicolasHug** [comment]
Same comment as in https://github.com/NicolasHug/Surprise/issues/214#issuecomment-429682159, friend.

Also, please don't delete your comments. If you now think your behavior in #214 was inappropriate (and it was!) then instead of hiding it you should probably just not do the exact same thing again here. 

Closing.

**Comment by ngovind93** [comment]
> Maybe the best way to go would be to compute the `sim` matrix yourself and plug it back when you want to do the predictions

I have not got this point. can please explain

**Comment by NicolasHug** [comment]
The similarity matrix is the `sim` attribute of the predictor object.
If you don't want to use Cython, you can compute this matrix wherever you want (in the `train` method for example). You can the set

`algo.sim = your_custom_matrix_computation()`

and run the other steps seemlessly.
