### ISSUE TITLE
Problem in building the training set when data where load from panda's dataframe

### ISSUE THREAD

**Issue by GiovanniGabbolini** [NicolasHug/Surprise#228]
#### Description
There's a problem in building the training set to pass to function fit when it is load from a panda's df. I've built the training set as shown below but I've noticed that, when `training_set.all_ratings()` is called by optimization methods (in my case `sgd` of class `SVDpp`) then the tuples (user, item, rating) do not correspond to my training set. In particular, say user 0 had rated 150, 200 and user 1 had rated 101, 23, 70 then I find in `training_set.all_ratings()` the tuples:

(0, 0, score)
(0, 1, score)
(0, 2, score)
(1, 3, score)
(1, 4, score)
(1, 5, score)

and so on.

#### Steps/Code to Reproduce
```
df = pd.DataFrame(d) # just a dataframe
df.columns = ['userID', 'itemID', 'rating']
reader = Reader()
data = Dataset.load_from_df(df[['userID', 'itemID', 'rating']], reader)
trainset = data.build_full_trainset()

for u, i, r in trainset.all_ratings():
    print((u, i, r)) # notice mistake from here
```

### Proposed fix
I managed to get in `trainset.all_ratings()` the rights ratings by updating function construct_dataset in dataset.py this way:

your version:
..
```
ur[uid].append((iid, r))
ir[iid].append((uid, r))
```
..

my version
..
```
ur[urid].append((irid, r))
ir[irid].append((urid, r))
```
..

The remaining part of the code was left unchanged.

#### Versions
Linux-4.15.0-20-generic-x86_64-with-debian-buster-sid
Python 3.7.1 (default, Oct 23 2018, 19:19:42) 
[GCC 7.3.0]
surprise 1.0.6

Let me know if the fix does anything wrong and I hope my suggesting will be appreciated.

**Comment by NicolasHug** [comment]
I think you're confusing inner IDs and raw IDs. As explained in the docs of all_ratings, those are inner IDs. The ones in you dataframe are raw IDs.

**Comment by NicolasHug** [comment]
>iterating over the same structure but with the movielens dataset

I'm not sure what you mean by that.


If you have different results when using `load_from_df` vs `load_from_file` (or similar) **on the exact same data**, then there's something wrong with surprise, and I would appreciate a minimal reproducing example so I can track the bug down.

Else, as far as the tests go, the current code looks good to me.
