### ISSUE TITLE
ALS 

### ISSUE THREAD

**Issue by datadj28** [NicolasHug/Surprise#230]
#### Description
Hi,

From your documentation, I see that if I use AlgoBase which is a base under the "surprise.prediction_algorithms.matrix_factorization.SVD" class, I can incorporate "als" as an estimator. Using the movie lens data set I attempted to do this. I used the layout from the documentation and the error came from trying to fit the testset (which is in bold under the Code section of this post). 

Here is the original dataframe:
![image](https://user-images.githubusercontent.com/36797114/48806347-07aac500-ece8-11e8-8aa5-0773eedeb692.png)

This worked fine when I didn't add the bls_options to the SVD algorithm. Does the package not support ALS estimators using this approach? Or am I not including a piece of code?

Thank you!

##### Load Reader library
reader = Reader()

##### Load ratings dataset with Dataset library
data = Dataset.load_from_df(df[['user', 'item', 'rating']], reader)

print('Using ALS')
bsl_options = {'method': 'als',
               'n_epochs': 20,
               'reg_u': 12,
               'reg_i': 5
               }

##### Use the SVD algorithm with ALS.
algo = AlgoBase(bsl_options=bsl_options)

##### Train/test set
trainset = data.build_full_trainset()
algo.fit(trainset)
testset = trainset.build_testset()

**predictions = algo.test(testset)**

![image](https://user-images.githubusercontent.com/36797114/48806444-535d6e80-ece8-11e8-97c6-aa38ba0e8524.png)

#### Expected Results
I expected that the predictions would be calculated.
#### Actual Results
An error was thrown stating that 'AlgoBase' object has no attribute 'estimate'.

**Comment by NicolasHug** [comment]
You should never instantiate `AlgoBase`, this will never work. Always use the child classes. If there's a place in the doc where you saw such a thing, please tell me where because this is wrong and I need to fix it.
