### ISSUE TITLE
ValueError: could not convert string to float when using pandas df

### ISSUE THREAD

**Issue by misaelzapata** [NicolasHug/Surprise#233]
#### Description
I am trying to make a similar code to this example: [https://github.com/NicolasHug/Surprise/blob/master/examples/k_nearest_neighbors.py](url)
using a dataframe created from a mongo collection
Example of df:
`
      id                                              name normal_price         sku
0      0     LED SMART TV HISENSE 55 4K Mod: HLE-5517RTUXI        18999        7325
1      1                        LED SMART TV TCL 32 L-32S6         7499        7282
2      2           LED SMART TV 4K  43 HISENSE HLE-4317RTU        13999        7447
3      3                LED SMART 55 TCL UHD L-55P6 SILVER        19999        7283
4      4          LED SMART TV PHILIPS 49'' 49-PFG-5102/77        15999        6947
5      5          LED SMART TV PHILIPS 50'' 50-PUG-6102/77        18999        6945
6      6          LED SMART TV PHILIPS 55'' 55-PUG-6212/77        27999        7001
170  170              Smart TV LG 43 " Full HD 43LK5700PSC     17999.00  d25a2b92af
171  171             Smart TV Philips 32 " HD 32PHG5833/77     10999.00  604a13f989
172  172       Smart TV Philips 43 " Ultra HD 43PUG6102/77     17999.00  bbe7905324
173  173              Smart TV LG 43 " Full HD 43LJ5500-SA     13999.00  7c505300c9

`
I get an error with the sku saying: 
> ValueError: could not convert string to float: 'bee9b9fb91'

#### Steps/Code to Reproduce
`def read_item_names():
	"""Read the u.item file from MovieLens 100-k dataset and return two
    mappings to convert raw ids into movie names and movie names into raw ids.
	"""
	for p in _products:
		_ = {}
		_['id'] = p['id']
		_['name'] = p['name']
		rid_to_name[_['id']] = _['name']
		name_to_rid[_['name']] = _['id']
	return rid_to_name, name_to_rid

import pandas as pd
df = pd.DataFrame(_p)
print(df)
reader = Reader()

data = Dataset.load_from_df(df[['id','name', 'sku']],reader=reader,)
trainset = data.build_full_trainset()

from surprise import KNNBaseline
sim_options = {'name': 'pearson_baseline', 'user_based': False}
algo = KNNBaseline(sim_options=sim_options)
algo.fit(trainset)
rid_to_name, name_to_rid = read_item_names()
toy_story_inner_id = algo.trainset.to_inner_iid('Smart TV Philips 43 " Ultra HD 43PUG6102/77')
`

**Comment by NicolasHug** [comment]
What exactly are you trying to do?

Surprise is a library for collaborative filtering algorithms.
You need to have a dataset with users, items, and ratings.

Your dataset is made of products with names, ids, and sku, and you're trying to map those into users, items and ratings. How is it supposed to work?

**Comment by misaelzapata** [comment]
Hi @NicolasHug, my mistake, I am very sorry. I needed to add a TfidfVectorizer to analyze and create a vector to get the rating of the words. Sorry for wasting your time and thank you very much for your help.
