### ISSUE TITLE
validation set and testset

### ISSUE THREAD

**Issue by lampda** [NicolasHug/Surprise#235]
how can i use separate datasets to validate the trained model, and test its performance (P, R, AUC, etc)?

**Comment by lampda** [comment]
to be specifically, I plan to use the data from Jan to June as trainset, then July for validation while August for test. How can I do that?

**Comment by NicolasHug** [comment]
is this what you're looking for? 
https://surprise.readthedocs.io/en/stable/FAQ.html#how-to-save-some-data-for-unbiased-accuracy-estimation

**Comment by lampda** [comment]
Thanks for the link. It is what I wanted.
