### ISSUE TITLE
Mermory Error in Computing Similarities

### ISSUE THREAD

**Issue by Aryanr64x** [NicolasHug/Surprise#236]
I am using the [Anime Dataset](https://www.kaggle.com/CooperUnion/anime-recommendations-database)
for creating my recommender system using KNNBasic Algorithm.It has about 7..6 million ratings.In the following line of code
`ratings = AnimeDataSet.load_ratings_dataset()
trainset = ratings.build_full_trainset()
alogorithm = KNNBasic(sim_options={
    'name': 'cosine',
    'user_based': True
})

alogorithm.fit(trainset)

similarities = alogorithm.compute_similarities()`

 I get the following error 

**Traceback (most recent call last):
  File "main.py", line 37, in <module>
    alogorithm.fit(trainset)
  File "E:\AI\RecSys\lib\site-packages\surprise\prediction_algorithms\knns.py", line 99, in fit
    self.sim = self.compute_similarities()
  File "E:\AI\RecSys\lib\site-packages\surprise\prediction_algorithms\algo_base.py", line 293, in compute_similarities
    sim = construction_func[name](*args)
  File "surprise/similarities.pyx", line 73, in surprise.similarities.cosine
    freq = np.zeros((n_x, n_x), np.int)
MemoryError**

I tried to reduce the size of the dataset file (which i should not.) and removed 7 million ratings from it
Even then I get the same error.
It even failed in google Collaboratory.
Thats too expensive of a memory work and I am clueless on how to escape it .

**Comment by NicolasHug** [comment]
It's not the number of ratings that's really important here but the number of users and/or items.

There isn't much you can do about memory issues except:
- get more RAM
- use another algo

**Comment by NicolasHug** [comment]
Also note that in general surprise isn't designed to be extremely scalable to big amounts of data.

**Comment by Aryanr64x** [comment]
I think its because the main aim of this library is to evaluate a particular algorithm.Thanks FOR HELP.This issue can now be closed

**Comment by morenoh149** [comment]
@Aryanr64x in the future you can close issues you own yourself.
