### ISSUE TITLE
The experimental result may not stable enough, how can I do it?  

### ISSUE THREAD

**Issue by s1162276945** [NicolasHug/Surprise#238]
#### Description

The experimental result may not stable enough, how can I do it? 
when I run PMF on Linux with python36:
~$ python3 BaselineMF.py --biased False RMSE: 1.0459
~$ python3 BaselineMF.py --biased False RMSE: 1.0571

#### Expected Results
Expect the experimental result to be stable.

**Comment by NicolasHug** [comment]
Have you tried setting the random seed?

**Comment by s1162276945** [comment]
I only have Visual Studio 2017, but surprise need Microsoft Visual C++ 14.0 environment. 
[https://stackoverflow.com/questions/29846087/microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat](url)

**Comment by NicolasHug** [comment]
You need to set the random seed to have reproducible experiments.

This is not related at all to your environment. I assume from your previous comment that I can close the issue?
