### ISSUE TITLE
"Surprise" module not recognized in Jupyter notebook

### ISSUE THREAD

**Issue by balajikalluri** [NicolasHug/Surprise#24]
Dear Nicolas,

I'm a newbie to recommender systems and found your package to kickstart with basic examples.

![image](https://cloud.githubusercontent.com/assets/7898603/25523336/dbce5f4e-2c38-11e7-860d-fe275705e88f.png)

Your kind help in helping me resolving this issue presented in the snapshot will be appreciated. 

Thanks.
Bala

**Comment by NicolasHug** [comment]
Well it seems like you haven't installed the packaged for Python 3.

**Comment by NicolasHug** [comment]
Bala,

Have you managed to install Surprise? If so, can I close this issue?

Thanks,
Nicolas

**Comment by balajikalluri** [comment]
Hi Nicolas,

Thanks for promptly helping me. I haven't tried it but I am sure that i
have installed Python 3.6 through Anaconda package.

Can there by any other issue in your opinion ?

Thanks.

Bala

**Comment by NicolasHug** [comment]
Bala,

You already have Python 3.6, that's for sure. What you need is to install Surprise, by following the installation guidelines on the webpage or on the readme.

**Comment by balajikalluri** [comment]
Hi Nicolas,

Yes. I was trying that and possibly would have encountered something wrong
there.

Gimme sometime before you could close this issue, I can only check on
Tuesday once again on my office PC. Unfortunately, a long weekend here.

Wish you a happy long weekend too

Cheers,
Bala

**Comment by balajikalluri** [comment]
Hi Nicolas,

Yes. I tried reinstalling both NUMPY and SURPRISE using pip as given in the installation guide. 

Below is the complete response while installing SURPRISE. It FAILED while "building wheel for scikit-surpise". 

![image](https://cloud.githubusercontent.com/assets/7898603/25602730/cdfa1c58-2f28-11e7-843e-0389f89ab8e5.png)

![image](https://cloud.githubusercontent.com/assets/7898603/25602741/e97911aa-2f28-11e7-9ade-6984192a48fd.png)

![image](https://cloud.githubusercontent.com/assets/7898603/25602757/fa4f46fc-2f28-11e7-8e78-067d30a2502e.png)


Thanks in anticipation. 

Best,
Bala

**Comment by balajikalluri** [comment]
Hello Nicolas,

I had to install Microsoft Visual Studio++ as stated in some relevant blogs from previous issues reported here and installing SURPRISE package was successful. 

![image](https://cloud.githubusercontent.com/assets/7898603/25604516/713a45ac-2f36-11e7-97d6-8ccfb8595446.png)

Cheers,
Bala

**Comment by balajikalluri** [comment]
Well ! congratulations :) 
I have successfully run my first example in surprise with movie lens dataset, 
You can close this issue now. 

cheers,
bala

**Comment by venkatkrish12345** [comment]
I have the same issue like balajikalluri but have visual studio c++ 2015 also,i Can't able to import surprise

**Comment by DharmaPredicts** [comment]
Sneha610 your solution worked !! 
Thank You!
