### ISSUE TITLE
unable to install by pip3

### ISSUE THREAD

**Issue by HenryPaik1** [NicolasHug/Surprise#242]
#### Steps/Code to Reproduce

Hi, I have some issues when installing(1)  and importing surprise(2)

1. when using git clone & python setup.py:

```
x86_64-linux-gnu-gcc: error: surprise/similarities.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
2. when pip3 install surprise and import it
```
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'

```

I am looking forward your help.
Thanks.

#### Versions
Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

**Comment by NicolasHug** [comment]
Please follow the installation instructions in the README.

Use

`pip install -e .` after cloning

Also it should be

`pip install scikit-surprise`

Using pip3 works fine on my machine.

**Comment by HenryPaik1** [comment]
Got it.
I installed it on my pyenv, cuz still cannot properly install it on global env.
Anyway it works well.
Many Thanks.
