### ISSUE TITLE
Threshold tuning on precision recall

### ISSUE THREAD

**Issue by sa1as** [NicolasHug/Surprise#244]
I am not sure if this is the right place to ask so apologies in advance if its not.

I am using the precision recall example from the FAQ  and I was wondering how to tune the threshold so that my results are meaningful. A the moment with a high threshold i get very high precision since there are no a lot of item with high rating. The data global mean is very skewed with a global mean of 1.5. Is there a guideline bast on the data set that could give me some insight?

thanks in advance!

**Comment by NicolasHug** [comment]
It's very hard to tell from a general perspective, as it really depends on your prediction algorithm. Note also that most of the algorithms in surprise are designed to minimize RMSE, which does not have a direct correlation to rank based metrics

**Comment by sa1as** [comment]
Thanks for the quick reply.

Well my current flow at the moment is to do a grid search and choose the best algorithm/parameters based on the RMSE. After that I want to use the precision/recall example to compare different models (collaborative filters , content base etc.). My main issue is to define "relevant" items which is a rating based decision.

So I am thinking of combining the user specific mean true rating (as the relevance threshold) and user specific estimated rating (for the recommendation threshold). 

Any comment is welcome.
