### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by solovictor** [NicolasHug/Surprise#248]

**Comment by NicolasHug** [comment]
>Where to get info how to run this module?

don't run it directly, the similarity matrix is computed when calling `fit()`. the matrix is then available as the `sim` attribute

> a) Can it provide similarities using user's embedded matrix or only user-items matrix?

only user-user or item-item

>b) Any example of code to compute distance matrix between users (with described input/output parameters?) using this cosine module or compute_similarities() module?

yes, please see the user guide

>Also, do you have examples how get left U matrix and right V matrix after using SVD algorithm as
algo = SVD() in surprise package?

yes please see previous issues

**Comment by solovictor** [comment]
Thank you very much, I am thinking to try the package not for ranking but
for generating distances between patients with some disease (users) where
their gene expression values (items). It might be good to use
user-user distances ) to make subpopulations of patients.

It would be nice if Surprise has SVD with embedding variant  (to make
ranking using reduced dimension space) a la
https://towardsdatascience.com/collaborative-filtering-and-embeddings-part-2-919da17ecefb

https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/:
Data with a large number of features, such as more features (columns) than
observations (rows) may be reduced to a smaller subset of features that are
most relevant to the prediction problem. The result is a matrix with a
lower rank that is said to approximate the original matrix. To do this we
can perform an SVD operation on the original data and select the top k
largest singular values in Sigma. These columns can be selected from Sigma
and the rows selected from V^T.
Best Regards, Victor

**Comment by NicolasHug** [comment]
Would you have a ref for the *SVD with embedding variant*?

(I'm really not saying I want to do it, I'm just curious about what you mean)
