### ISSUE TITLE
Own dataset - RAM usage problem.

### ISSUE THREAD

**Issue by Siemko** [NicolasHug/Surprise#249]
Hello!
#### Description
I am implementing recommendation system for online shop. I am collecting items that user is watching, adding to cart and pays for. Currently I have 65k items "rated" by users. I have a problem with high RAM usage during computing similarity matrix. I tried using different similarity measures, but RAM usage is always high. Too high for my machine, therefore I get memory errors.

I tired chunking my input data:
```
tp = read_csv("all.csv", iterator=True, chunksize=1000)
df = concat(tp, ignore_index=True)
data = Dataset.load_from_df(df, reader=reader)
trainset = data.build_full_trainset()
sim_options = {'name': 'cosine', 'user_based': False}
global _, algo
start_time = time.time()
algo = KNNBaseline(sim_options=sim_options)
algo.fit(trainset)
```
but the problem is with `algo.fit(trainset)`.

Can it be optimised in any way? 

I saw an issue #208, where partial fitting is proposed, could this help in any way?

Or is there any way to make it work good on 4GB of RAM?

#### Versions
```
Windows-10-10.0.17763-SP0
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
surprise 1.0.6
```

**Comment by NicolasHug** [comment]
Please see the various [past issues](https://github.com/NicolasHug/Surprise/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+memory) about this

**Comment by morenoh149** [comment]
Should ballpark figures for dataset set sizes and algorithms that will work with those along with vm ram sizes be added to the FAQ? https://surprise.readthedocs.io/en/stable/FAQ.html That answer itself could be used to close these types of issues and aggregate knowledge around this question.

**Comment by NicolasHug** [comment]
Not sure about ram size, but along these lines I think that big-O indications for time and memory usage of each algorithm / similarity would be an interesting addition
