### ISSUE TITLE
Estimates on unseen user or item

### ISSUE THREAD

**Issue by kenoung** [NicolasHug/Surprise#25]
When producing an estimate for a known user but unknown item, would it be helpful to provide  self.trainset.global_mean+ self.bu[u] instead? Similarly, we can provide self.trainset.global_mean+ self.bi[i] when the user is unknown but the item is known. I believe the current implementation returns self.trainset.global_mean when PredictionImpossible is raised.

https://github.com/NicolasHug/Surprise/blob/master/surprise/prediction_algorithms/matrix_factorization.pyx#L244
```
    def estimate(self, u, i):
        # Should we cythonize this as well?

        est = self.trainset.global_mean if self.biased else 0

        if self.trainset.knows_user(u):
            est += self.bu[u]

        if self.trainset.knows_item(i):
            est += self.bi[i]

        if self.trainset.knows_user(u) and self.trainset.knows_item(i):
            est += np.dot(self.qi[i], self.pu[u])
        else:
            raise PredictionImpossible

        return est
```

As a side note, if we're checking for both user and item anyways, why not do it in one step? i.e.
```
    def estimate(self, u, i):
        # Should we cythonize this as well?

        est = self.trainset.global_mean if self.biased else 0

        if self.trainset.knows_user(u) and self.trainset.knows_item(i):
            est += self.bu[u] + self.bi[i] + np.dot(self.qi[i], self.pu[u])
        else:
            raise PredictionImpossible

        return est
```

**Comment by NicolasHug** [comment]
Hi

> When producing an estimate for a known user but unknown item, would it be helpful to provide self.trainset.global_mean+ self.bu[u] instead? Similarly, we can provide self.trainset.global_mean+ self.bi[i] when the user is unknown but the item is known.

That's exactly what is currently done.

> I believe the current implementation returns self.trainset.global_mean when PredictionImpossible is raised.

No, `PredictionImpossible` is only raised when both the user **and** the item are unknown.

The version you propose does not allow to do what you wanted in the first place (i.e. predict `self.trainset.global_mean+ self.bu[u]` if only the item is unknown).

Unrelated (but still a bit related), the line 

        else:
            raise PredictionImpossible

is only useful when `self.biased` is `False`.

**Comment by kenoung** [comment]
Hi Nicolas,

I'm not sure if I follow. 

> No, PredictionImpossible is only raised when both the user and the item are unknown.

My understanding is that PredictionImpossible will be raised if either of them is unknown.

```
        if self.trainset.knows_user(u) and self.trainset.knows_item(i):
            est += np.dot(self.qi[i], self.pu[u])
        else:
            raise PredictionImpossible
```

The if clause is entered if the trainset knows the user **and** knows the item. If the trainset only knows one of them, it should enter the else clause and raise an Exception.

Ken

**Comment by NicolasHug** [comment]
Ha, you are right! Rookie mistake from me...

It should be

        if self.trainset.knows_user(u) and self.trainset.knows_item(i):
            est += np.dot(self.qi[i], self.pu[u])
        elif not self.biased:
            raise PredictionImpossible


I changed the code a bit to make it clearer:

    def estimate(self, u, i):                                                  
        # Should we cythonize this as well?                                    
                                                                               
        known_user = self.trainset.knows_user(u)                               
        known_item = self.trainset.knows_item(i)                               
                                                                               
        if self.biased:                                                        
            est = self.trainset.global_mean                                    
                                                                               
            if known_user:                                                     
                est += self.bu[u]                                              
                                                                               
            if known_item:                                                     
                est += self.bi[i]                                              
                                                                               
            if known_user and known_item:                                      
                est += np.dot(self.qi[i], self.pu[u])                          
                                                                               
        else:                                                                  
            if known_user and known_item:                                      
                est = np.dot(self.qi[i], self.pu[u])                           
            else:                                                              
                raise PredictionImpossible('User and item are unkown.')        
                                                                               
        return est   


Does it seem better to you?

Thanks for pointing out my mistake!

Nicolas

**Comment by kenoung** [comment]
Yup looks good! Thanks for the quick response and great work on the library!
