### ISSUE TITLE
How to display the iterative process of ['RMSE']

### ISSUE THREAD

**Issue by kyolxs** [NicolasHug/Surprise#251]
I want to draw an iterative graph of ['RMSE']. The x-axis is the number of iterations, but the reference example simply outputs the final value directly. Do you know how to display the iterative process of ['RMSE']?

We'll use the famous SVD algorithm.
algo = SVD()
algo = KNNBasic()
Run 5-fold cross-validation and print results
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

**Comment by NicolasHug** [comment]
There's no way to do that unfortunately. You'll have to modify the algorithm if you want to compute the training loss for every iteration.

**Comment by kyolxs** [comment]
> There's no way to do that unfortunately. You'll have to modify the algorithm if you want to compute the training loss for every iteration.

Understand, thank you for your reply.
