### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

### ISSUE THREAD

**Issue by Abdulbarr1** [NicolasHug/Surprise#252]
Hi,
I'm trying to install surprise and have checked all options including 'pip install scikit-surprise', 'pip install --user scikit-surprise', etc. but I'm facing the same issue every time even after installing Microsoft Visual C++ Build Tools.
here is the full stack of error

C:\Users\hmabd>pip install --user scikit-surprise
Collecting scikit-surprise
  Using cached https://files.pythonhosted.org/packages/4d/fc/cd4210b247d1dca421c25994740cbbf03c5e980e31881f10eaddf45fdab0/scikit-surprise-1.0.6.tar.gz
Requirement already satisfied: joblib>=0.11 in c:\users\hmabd\appdata\roaming\python\python37\site-packages (from scikit-surprise) (0.13.2)
Requirement already satisfied: numpy>=1.11.2 in c:\users\hmabd\appdata\roaming\python\python37\site-packages (from scikit-surprise) (1.16.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\hmabd\appdata\roaming\python\python37\site-packages (from scikit-surprise) (1.2.1)
Requirement already satisfied: six>=1.10.0 in c:\users\hmabd\appdata\roaming\python\python37\site-packages (from scikit-surprise) (1.12.0)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... error
  Complete output from command "c:\program files\python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\hmabd\\AppData\\Local\\Temp\\pip-install-lb5rhfvw\\scikit-surprise\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\hmabd\AppData\Local\Temp\pip-wheel-t60q84fe --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\surprise
  copying surprise\accuracy.py -> build\lib.win-amd64-3.7\surprise
  copying surprise\builtin_datasets.py -> build\lib.win-amd64-3.7\surprise
  copying surprise\dataset.py -> build\lib.win-amd64-3.7\surprise
  copying surprise\dump.py -> build\lib.win-amd64-3.7\surprise
  copying surprise\evaluate.py -> build\lib.win-amd64-3.7\surprise
  copying surprise\reader.py -> build\lib.win-amd64-3.7\surprise
  copying surprise\trainset.py -> build\lib.win-amd64-3.7\surprise
  copying surprise\utils.py -> build\lib.win-amd64-3.7\surprise
  copying surprise\__init__.py -> build\lib.win-amd64-3.7\surprise
  copying surprise\__main__.py -> build\lib.win-amd64-3.7\surprise
  creating build\lib.win-amd64-3.7\surprise\model_selection
  copying surprise\model_selection\search.py -> build\lib.win-amd64-3.7\surprise\model_selection
  copying surprise\model_selection\split.py -> build\lib.win-amd64-3.7\surprise\model_selection
  copying surprise\model_selection\validation.py -> build\lib.win-amd64-3.7\surprise\model_selection
  copying surprise\model_selection\__init__.py -> build\lib.win-amd64-3.7\surprise\model_selection
  creating build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\algo_base.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\baseline_only.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\knns.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\predictions.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\random_pred.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\__init__.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  running egg_info
  writing scikit_surprise.egg-info\PKG-INFO
  writing dependency_links to scikit_surprise.egg-info\dependency_links.txt
  writing entry points to scikit_surprise.egg-info\entry_points.txt
  writing requirements to scikit_surprise.egg-info\requires.txt
  writing top-level names to scikit_surprise.egg-info\top_level.txt
  reading manifest file 'scikit_surprise.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'scikit_surprise.egg-info\SOURCES.txt'
  copying surprise\similarities.c -> build\lib.win-amd64-3.7\surprise
  copying surprise\similarities.pyx -> build\lib.win-amd64-3.7\surprise
  copying surprise\prediction_algorithms\co_clustering.c -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\matrix_factorization.c -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\optimize_baselines.c -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\slope_one.c -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\co_clustering.pyx -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\matrix_factorization.pyx -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\optimize_baselines.pyx -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  copying surprise\prediction_algorithms\slope_one.pyx -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
  running build_ext
  building 'surprise.similarities' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

  ----------------------------------------
  Failed building wheel for scikit-surprise
  Running setup.py clean for scikit-surprise
Failed to build scikit-surprise
Installing collected packages: scikit-surprise
  Running setup.py install for scikit-surprise ... error
    Complete output from command "c:\program files\python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\hmabd\\AppData\\Local\\Temp\\pip-install-lb5rhfvw\\scikit-surprise\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\hmabd\AppData\Local\Temp\pip-record-i0l5bm81\install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\surprise
    copying surprise\accuracy.py -> build\lib.win-amd64-3.7\surprise
    copying surprise\builtin_datasets.py -> build\lib.win-amd64-3.7\surprise
    copying surprise\dataset.py -> build\lib.win-amd64-3.7\surprise
    copying surprise\dump.py -> build\lib.win-amd64-3.7\surprise
    copying surprise\evaluate.py -> build\lib.win-amd64-3.7\surprise
    copying surprise\reader.py -> build\lib.win-amd64-3.7\surprise
    copying surprise\trainset.py -> build\lib.win-amd64-3.7\surprise
    copying surprise\utils.py -> build\lib.win-amd64-3.7\surprise
    copying surprise\__init__.py -> build\lib.win-amd64-3.7\surprise
    copying surprise\__main__.py -> build\lib.win-amd64-3.7\surprise
    creating build\lib.win-amd64-3.7\surprise\model_selection
    copying surprise\model_selection\search.py -> build\lib.win-amd64-3.7\surprise\model_selection
    copying surprise\model_selection\split.py -> build\lib.win-amd64-3.7\surprise\model_selection
    copying surprise\model_selection\validation.py -> build\lib.win-amd64-3.7\surprise\model_selection
    copying surprise\model_selection\__init__.py -> build\lib.win-amd64-3.7\surprise\model_selection
    creating build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\algo_base.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\baseline_only.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\knns.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\predictions.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\random_pred.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\__init__.py -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    running egg_info
    writing scikit_surprise.egg-info\PKG-INFO
    writing dependency_links to scikit_surprise.egg-info\dependency_links.txt
    writing entry points to scikit_surprise.egg-info\entry_points.txt
    writing requirements to scikit_surprise.egg-info\requires.txt
    writing top-level names to scikit_surprise.egg-info\top_level.txt
    reading manifest file 'scikit_surprise.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'scikit_surprise.egg-info\SOURCES.txt'
    copying surprise\similarities.c -> build\lib.win-amd64-3.7\surprise
    copying surprise\similarities.pyx -> build\lib.win-amd64-3.7\surprise
    copying surprise\prediction_algorithms\co_clustering.c -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\matrix_factorization.c -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\optimize_baselines.c -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\slope_one.c -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\co_clustering.pyx -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\matrix_factorization.pyx -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\optimize_baselines.pyx -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    copying surprise\prediction_algorithms\slope_one.pyx -> build\lib.win-amd64-3.7\surprise\prediction_algorithms
    running build_ext
    building 'surprise.similarities' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command ""c:\program files\python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\hmabd\\AppData\\Local\\Temp\\pip-install-lb5rhfvw\\scikit-surprise\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\hmabd\AppData\Local\Temp\pip-record-i0l5bm81\install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in C:\Users\hmabd\AppData\Local\Temp\pip-install-lb5rhfvw\scikit-surprise\

Is there anyone who could assist me to fix this bug?

**Comment by NicolasHug** [comment]
Try using conda?

**Comment by Abdulbarr1** [comment]
> Try using conda?

I've installed it with conda but with conda I'm unable to use it outside Jupyter or Spyder.
Basically, I've to use this library in Sublime, that's why I intend to install it with pip

**Comment by NicolasHug** [comment]
you can use it from anywhere with conda as long as you're using the right environment

**Comment by Abdulbarr1** [comment]
> you can use it from anywhere with conda as long as you're using the right environment

I got your point, with conda it works well. Although, you should also consider about the above error to fix it.

**Comment by NicolasHug** [comment]
The error message says that MS C++ isn't installed (maybe you have but it can't find it?).
This is not an error to be fixed on surprise's side

**Comment by matevzpesek** [comment]
The error still persists on environments with installed c++ tools (even VS professional).

**Comment by matevzpesek** [comment]
I managed to bypass this by finding an old link to download the 14.0 version. It seems this version is hardcoded in the surprise requirement (I had 14.6 and 16.0 already installed).

**Comment by NicolasHug** [comment]
No compiler version is hardcoded

**Comment by therealabhishek** [comment]
Could you please provide the link for the 14.0 version?
thanks.

**Comment by therealabhishek** [comment]
> I managed to bypass this by finding an old link to download the 14.0 version. It seems this version is hardcoded in the surprise requirement (I had 14.6 and 16.0 already installed).

could you please provide the link for the 14.0 version?
thanks.

**Comment by matevzpesek** [comment]
@NicolasHug howcome it does not work with the 14.6 and newer versions then?

@therealabhishek here it is: https://download.visualstudio.microsoft.com/download/pr/e48a4988-6941-44cd-b10d-869ae6e5a6e4/ebb9b691a4ac5916171f319a7863d5a5/vs_buildtools.exe

**Comment by shenhe-zhang** [comment]
> @NicolasHug howcome it does not work with the 14.6 and newer versions then?
> 
> @therealabhishek here it is: https://download.visualstudio.microsoft.com/download/pr/e48a4988-6941-44cd-b10d-869ae6e5a6e4/ebb9b691a4ac5916171f319a7863d5a5/vs_buildtools.exe

Very Helpful!

**Comment by mutified** [comment]
I had a similar "error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools":"
The length of the error messages are sometimes daunting. I took the response and fed it to chatGBT, which quickly identified rc.exe as not being found and suggested installing Windows SDK or checking that the path to rc.exe was in the environmental variables.

This worked and scikit-surprise easily installed.
