### ISSUE TITLE
Prediction matrix

### ISSUE THREAD

**Issue by tgeorgiop** [NicolasHug/Surprise#253]
Hello. Is it possible to have the whole prediction matrix after fitting the data without calling predict function for every user-item? I am interested in the matrix R, which it has users as rows and items as columns. The values of the matrix are the predictions.

More specifically, I call

`predictions = algo.fit(trainset)`

Is it possible to have the full prediction matrix without calling

`algo.predict(i,j)`

for each i(user)-j(item)?

**Comment by NicolasHug** [comment]
You can only use the predict method
