### ISSUE TITLE
How to get dataset details or convert Dataset to DataFrame structure?

### ISSUE THREAD

**Issue by ybdesire** [NicolasHug/Surprise#254]
It is easy to load dataset by surprise as below

```
from surprise import Dataset
data = Dataset.load_builtin('ml-100k')
```

But I want to check more detailed properties about the dataset, such as shape, column name, and data descriptions. How can i print the data details ? (as below for example)

```
	user_id	item_id	rating	timestamp
0	196	242	3	881250949
1	186	302	3	891717742
2	22	377	1	878887116
3	244	51	2	880606923
4	166	346	1	886397596
```

Or can wen convert the data to pandas DataFrame structure ? So we can do many statistical analysis on the loaded dataset.

**Comment by NicolasHug** [comment]
Surprise isn't designed for this. I would suggest using pandas

**Comment by ybdesire** [comment]
Got. Thanks @NicolasHug for the update.

**Comment by huangzixun123** [comment]
hello.  I want to know how the m1-100k dataset was converted to DatasetAutoFolds?
could me tell me?  Thank you

**Comment by lymereJ** [comment]
For future references, with `pandas`:
```
from surprise import Dataset
import pandas as pd
data = Dataset.load_builtin('ml-100k')
pd.DataFrame(data.__dict__['raw_ratings'], columns=['user_id','item_id','rating','timestamp'])
```
