### ISSUE TITLE
Is it the user rating error ?

### ISSUE THREAD

**Issue by ybdesire** [NicolasHug/Surprise#255]
Load the local dataset of ml-100k as below

```
import pandas as pd
header = ['user_id','item_id','rating','timestamp']
src_data = pd.read_csv('ml-100k/u.data',sep = '\t',names = header)
src_data.head() 
```

And it display the data as below

```

user_id | item_id | rating | timestamp
-- | -- | -- | --
196 | 242 | 3 | 881250949
186 | 302 | 3 | 891717742
22 | 377 | 1 | 878887116
244 | 51 | 2 | 880606923
166 | 346 | 1 | 886397596
```

So, we got that user-196 gave item-242 rating 3.

Then, load the same data by surprise

```
import os
from surprise import Dataset, Reader
file_path = os.path.expanduser('ml-100k/u.data')
reader = Reader(line_format='user item rating timestamp', sep='\t')
data2 = Dataset.load_from_file(file_path, reader=reader)
```

and check the rating result of user-196 to item-242 as below

```
trainset2 = data2.build_full_trainset()
for (item, result) in trainset.ur[196]:
    if(item==242):
        print(result)
```

And got nothing, it seems there is no result for user-196 to item-242. But from first part of code block as above, we believe that user-196 gave item-242 rating 3 points.

Why we cannot get the rating information correctly by surprise ?

**Comment by NicolasHug** [comment]
you likely need to use strings as users and items ids. Please see the FAQ entry about raw and inner ids.
