### ISSUE TITLE
What is the r_ui_trans in testset?

### ISSUE THREAD

**Issue by ybdesire** [NicolasHug/Surprise#256]
I trained SVD as blow

```
algo = SVD()
algo.fit(trainset)
```

Then, I constructed test data set as below and do prediction 

```
testset = [
    ('5','1'),# want to know user-5 rating item-1
    ('5','4'),
    ('5','5'),
]
predictions = algo.test(testset)
```

But got error

```
--> 212                        for (uid, iid, r_ui_trans) in testset]
    213         return predictions
ValueError: not enough values to unpack (expected 3, got 2)

```

If i modified test data set as below (set all r_ui_trans` in test data set to zero ), the result is correct.

```
testset = [
    ('5','1',0),# want to know user-5 rating item-1
    ('5','4',0),
    ('5','5',0),
]
predictions = algo.test(testset)
```

So, my question is what is the `r_ui_trans` in test data set?

Is it correct to set all r_ui_trans` in test data set to zero as my code above?

**Comment by NicolasHug** [comment]
`r_ui_trans` is the ground truth rating of user u for item i. (It might be translated so that all ratings are positive, if your rating scale crosses 0).

You can set it at 0, but then your `predictions` object will have an incorrect `r_ui` field and your accuracy computed with e.g. `rmse` will be wrong

**Comment by NicolasHug** [comment]
If all you want is to predict ratings for which you don't know the ground truth rating, I would suggest using `predict` in a for loop instead of using test.

**Comment by ybdesire** [comment]
Got that. Thanks @NicolasHug for the details.
