### ISSUE TITLE
Why surprise doesn't work if the rating is decimal ?

### ISSUE THREAD

**Issue by cuilongyin** [NicolasHug/Surprise#257]
Hi dear Dr.Hug:

I've done a bit pre-processing to the ratings, which causes the ratings to be decimal numbers e.g. 2.534, 4.752 etc. I realize the ratings have to be integers or of 0.5 precision in order for surprise to work. It is true? Is there anyway to make surprise also working with long decimal ratings? Is it because of the classification/regression model thingy in the algorithm?

(Since this is kind of a general question I didn't attach my code, but if you want to see it I can post it for you.)

Thank you very much for the time!!
LC

**Comment by NicolasHug** [comment]
I don't understand, it should work with float as ratings

**Comment by cuilongyin** [comment]
I am so sorry, please ignore it, it's a bug I made.
On Mar 21, 2019, 6:59 PM -0400, Nicolas Hug <notifications@github.com>, wrote:

I don't understand, it should work with float as ratings
