### ISSUE TITLE
Selection of Candidates.

### ISSUE THREAD

**Issue by vicencarlos** [NicolasHug/Surprise#258]
I'm testing many recommendation libraries in python, and  i think Surprise probably is the most promising at this moment. 
But i found in another libraries a funcionality that i don't found in Surprise.
In some libraries when calculate the recommendations yo can pass a candidate function that limits what items are eligible for certain users. f.e you can use items in the recomendation engine that the user doesn't have permission to see or are not available in that moment.

Is that funcionality in the roadmap?

Thanks

**Comment by NicolasHug** [comment]
Sorry no, this is not in the roadmap
