### ISSUE TITLE
Explicit vs Implicit Feedback

### ISSUE THREAD

**Issue by mgcdanny** [NicolasHug/Surprise#26]
Is there an option available to account for "implicit" feedback (purchases, clicks) instead of "explicit" feedback ("ratings") ? 

Some more information is here:
https://spark.apache.org/docs/2.1.0/mllib-collaborative-filtering.html#explicit-vs-implicit-feedback

Thanks!

Great package by-the-way.

**Comment by NicolasHug** [comment]
Hi, and thanks!

Algorithms for implicit feedback are not supported yet, but I'm working on it at the moment so it should come soon!

Nicolas

**Comment by NicolasHug** [comment]
Yes, it is supported.

**Comment by mayank1806** [comment]
How can I dump my predictions ? When I am using  "dump.dump('./dump_file', predictions, algo)". its throwing an **AttributeError: 'function' object has no attribute 'dump'**. How to solve it?

**Comment by NicolasHug** [comment]
Please open a new issue and show me your full code there (as well as your version of surprise).

@mgcdanny I'll close the issue BTW if you don't mind?

**Comment by phsimon** [comment]
Hi,

I'd like to make a test with implicit feedback (in fact I have in logs only couple (user,item))
May I use SVD++ by setting all ratings at '1' or shall I additionnaly add some negative ratings ('0') randomly choosen ?

Best regards.

**Comment by alimirferdos** [comment]
> Hi,
> 
> I'd like to make a test with implicit feedback (in fact I have in logs only couple (user,item))
> May I use SVD++ by setting all ratings at '1' or shall I additionnaly add some negative ratings ('0') randomly choosen ?
> 
> Best regards.

Any idea on this?
