### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by shmilyoyo** [NicolasHug/Surprise#261]
https://github.com/NicolasHug/Surprise/blob/711fb80748140c44e0ed870e573c735307e6c3cc/examples/top_n_recommendations.py#L50

When I tried to get top n recommendations based on the large dataset(10,000 users and 100,000 items, the rating matrix is very sparse) by using the example from examples/top_n_recommendations.py, the job was killed by system since it is out of memory.

Are there any ways to get predictions from part of anti_testset at each time? Thanks.

**Comment by shmilyoyo** [comment]
I think it could be solved by using multiple processing to test on test set batch.
```py
test_set = train_set.build_anti_testset()
test_set_batches = util.get_batches(test_set)
with mp.Manager() as manager:
    predictions = manager.list()
    process = [
                mp.Process(
                    target=self._predict,
                    args = [model, test_set_batch, predictions]
                ) for test_set_batch in test_set_batches
            ]
    for p in process:
        p.start()
    for p in process:
        p.join()
    print('all tasks finished')
    predictions = predictions._getvalue()
```

**Comment by shmilyoyo** [comment]
It is still out of memory. Is it possible to make train_set.build_anti_testset() return a generator instead of list? Or is it possible to generate test set by batch?

**Comment by NicolasHug** [comment]
You can only do this manually by excluding users or items from the trainset

**Comment by shmilyoyo** [comment]
@NicolasHug Thanks.
