### ISSUE TITLE
Knn question

### ISSUE THREAD

**Issue by wil0u** [NicolasHug/Surprise#262]
Hello, I would like to know what happens in this special case with KNN type of algorithm : 
Let's say that k = 1 and that we want to predict the rating of u1 (user1) for i3 (item3) and it happens that there exist 2 users : u2 and u3 that have the highest possible similarity with user1 : let's say that sim(u1,u2) = sim(u1,u3) = 1. What happen here ? Is the user with the smallest index is taken into account ? It seems that it is what's happening in my configuration but I would like a confirmation as I can't really find it within the documentation. 

Thanks in advance,

I hope this question hasn't been already answered in here or in the doc, sorry if it is the case.. 

Willeme

**Comment by NicolasHug** [comment]
I guess it's undefined. We feed `heapq.nlargest` in the order of increasing id so I suppose that yes, the smallest index will be returned but that depends on their implementation. We could force it by passing the ids as the comparison key

**Comment by wil0u** [comment]
Thank you for your anwser which was really quick btw !
So my ids are numericals, for instance here are some examples of rows from my input csv file (user,item,rating) :

- 1,1,5 
- 1,2,4
- 1,4,1
- 2,4,3
... 
In that case, you would say that the smallest index is chosen ?

**Comment by NicolasHug** [comment]
Well, the ids in the case are the inner ids. inners ids are from 0 to n_users - 1 (or n_items - 1). First user in the file has id 0, second has id 1, etc...

So it really depends on the order in which they appear in the file / dataframe

**Comment by wil0u** [comment]
Perfect, thank you for you answer !
