### ISSUE TITLE
About online update or delta training of model

### ISSUE THREAD

**Issue by FrancisFok** [NicolasHug/Surprise#263]
#### Description

Suppose a model have been trained by a dataset D, could it be possible to re-train the model by a dataset (D + D') where D' is a new records such that starting all weights from the previous model?

I have read the 'algo_base.py' and 'matrix_factorization.pyx' (SVD class). I think the initialization was only done in AlgoBase.fit . Is it logical correct to skip the initialization by controlling flag?

**Comment by NicolasHug** [comment]
If you retrain on D + D' there's no need to reuse the weights. Just start from scratch and use more iterations. If you retrain on just D' then yes it would make sense. Please see #208

**Comment by FrancisFok** [comment]
Get your point. Thank you.

**Comment by FrancisFok** [comment]
Sorry that continue discussion on closed issue.

**Comment by NicolasHug** [comment]
yes, since surprise does not support warm starting / partial fit, you will need to retrain on D + D'

**Comment by FrancisFok** [comment]
thank you, your code is easy to follow. Such behavior is easy to find in
studying your code before implementation.

在 2019年4月18日週四 19:43，Nicolas Hug <notifications@github.com> 寫道：

**Comment by vibl** [comment]
[river](https://github.com/online-ml/river) seems to do that.
