### ISSUE TITLE
Extract prods and freq from similarities.pyx

### ISSUE THREAD

**Issue by TamTSE2301** [NicolasHug/Surprise#264]
Hi,

I'm trying to apply interpolation weight from this literature ("http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.129.4662&rep=rep1&type=pdf")

So I need to extract the matrix **prods** and **freq** which you have defined in *similarities.pyx*.  I have tried:
- Changing the out put from *return sim* to *return sim, freq, prods*
- In the *algo_base.py* file, I change:
`sim, freq, prods = construction_func[name](*args)
`
- In the *knns.py*, I change:
```
    def fit(self, trainset):

        SymmetricAlgo.fit(self, trainset)
        #self.sim = self.compute_similarities(verbose=self.verbose)
       #Extract sims, freq and prods
        self.sim, self.freq, self.prods = self.compute_similarities(verbose=self.verbose) 

        return self
```
However it's still not working. Could you help me with this? Thank you very much.

**Comment by NicolasHug** [comment]
What is your error message? Have you also changed the output of compute_similarity?
Have your properly compiled the cython code?

**Comment by TamTSE2301** [comment]
Sorry. I have not compiled the adjusted cython code.

But for the output of compute_similarity, are you refering to this?:

```
        try:
            if verbose:
                print('Computing the {0} similarity matrix...'.format(name))
            sim, freq, prods = construction_func[name](*args)
            if verbose:
                print('Done computing similarity matrix.')
            return sim, freq, prods
```

**Comment by NicolasHug** [comment]
yes i was referring to this

**Comment by NicolasHug** [comment]
can I close the issue?

**Comment by TamTSE2301** [comment]
Yes. Thank you so much
