### ISSUE TITLE
Working with non-numeric datasets

### ISSUE THREAD

**Issue by palak311094** [NicolasHug/Surprise#265]
I want to work with a small data set but it has non-numeric values. So how should I work with such kind of data set using surprise. I have attached the csv file(in ZIP)
[myfile_1.zip](https://github.com/NicolasHug/Surprise/files/3098946/myfile_1.zip)
 of the data set I intend to use

.

**Comment by NicolasHug** [comment]
surprise is a library for collaborative filtering with explicit (numeric) ratings.
