### ISSUE TITLE
Denominators in NMF are sometimes zero, causing NaNs in estimates. Use the solution from sklearn for this.

### ISSUE THREAD

**Issue by doctorpangloss** [NicolasHug/Surprise#268]
https://github.com/NicolasHug/Surprise/blob/2efa8840ac2719050178d836c1d6904f9431f3c6/surprise/prediction_algorithms/matrix_factorization.pyx#L695

A simple fix is something like `user_denom[u, f] += max(qi[i, f] * est, EPSILON)`.

**Comment by NicolasHug** [comment]
would you have a reproducing example? NMF is supposed to only ever produce positive weights so it might be a bug

**Comment by doctorpangloss** [comment]
Yep, give me some time to make it while I finish other tasks next week. Appreciate the hard work you’ve put in!
