### ISSUE TITLE
Read in dataframe instead of file

### ISSUE THREAD

**Issue by kenoung** [NicolasHug/Surprise#27]
Hi!

Are there any plans to allow reading in pandas dataframes or numpy matrices or even strings instead of files?

Thanks!
Ken

**Comment by NicolasHug** [comment]
Hi Ken,

I provided an example to read ratings from a pandas dataframe in a previous issue #20.

If there is a strong need to read ratings from different inputs I can try to work on that. May I ask how such use-cases would be useful to you? Also, what would reading ratings from still look like?

Thanks,
Nicolas

**Comment by kenoung** [comment]
Hi thanks for the link. 

I'm currently using a custom dataset that takes a random split, then trains the SVD on it. To do this, I'm getting the relevant columns then writing them to disk before providing the file path to the reader. The workflow would be slightly smoother without having to write the data to disk.

I'm currently using a pandas dataframe, so maybe a method where we could load_from_df? I'm not sure what others are using though.

Thanks for the quick response. I'm not desperate for this right now. Just pointing it out as a possible feature request.

**Comment by NicolasHug** [comment]
I see. I will add an entry to the FAQ following the main lines of #20 to build a dataset from a dataframe. As you can see it all boils down to building the raw_ratings attribute. The dummy reader object is only here to specify the rating scale.

Have you been able to work out a solution for your specific case?

Don't hesitate to come back if you need help.
Nicolas

**Comment by kenoung** [comment]
Yup it's working now. Thanks! 

Ken
