### ISSUE TITLE
Recommendations based on different attributes

### ISSUE THREAD

**Issue by Amit0191** [NicolasHug/Surprise#273]
Hi,
So currently the input should be of the format user_id| item_id | ratings |timestamp(optional).

How can I add further relevant attributes which might effect recommendations like age,location of the user, etc (young audience might prefer different things from older audience) or genre of the movie.

Thank you.

**Comment by NicolasHug** [comment]
You can't.
Surprise supports collaborative filtering based on explicit ratings

**Comment by Amit0191** [comment]
Thank you for the reply . If I had to fork the repository can you offer any insights on how I can go about adding this functionality?
