### ISSUE TITLE
FEATURE REQUEST: implement skopt's BayesSearchCV

### ISSUE THREAD

**Issue by nicodds** [NicolasHug/Surprise#274]
Dear all, 
thank you for the wonderful package!

I would like to know if there is any plan to implement skopt's BayesSearchCV.

In case you have no time for this, with a few hints on the path to follow, I may try an implementation.

All the best,
Nico

**Comment by NicolasHug** [comment]
There's no plan for implementing bayesian parameter optimization.

I've been having fun with successive halving recently (https://github.com/scikit-learn/scikit-learn/pull/13900), and it seems to get better results than Bayesians approaches, so you  might want to consider this one instead?

**Comment by nicodds** [comment]
Never eard about that. I'm documenting and I'll come back in a while
