### ISSUE TITLE
Problems with the inner and raw ids when loading dataset from a pandas Dataframe

### ISSUE THREAD

**Issue by drosaslin** [NicolasHug/Surprise#276]
#### Description

Hi. I'm basically trying to run the same code that is shown in the documentation's FAQ about how to get the top n neighbors of a user or item but with a dataset loaded from a pandas' dataframe. I'm getting an error when trying to get the inner_iid from a movie's raw_id. This problem only occurs when the dataset is loaded from a pandas' dataframe. I have ran the same piece of code but loading the dataset directly from the local file and the code runs with no problem.

#### Steps/Code to Reproduce

```
r_cols = ['userId', 'movieId', 'rating', 'timestamp']
df = pd.read_csv('ml-100k/ratings.csv', sep=',', names=r_cols, encoding='latin-1')
reader = Reader(rating_scale=(1, 5))

data = Dataset.load_from_df(df=df[['userId', 'movieId', 'rating']], reader=reader)
trainset = data.build_full_trainset()

rid_to_name, name_to_rid = read_item_names()

sim_options = {'name': 'pearson_baseline', 'user_based': False}
algo = KNNBaseline(sim_options=sim_options)
algo.fit(trainset)

movie_raw_id = name_to_rid['Interstellar (2014)']
movie_inner_id = algo.trainset.to_inner_iid(movie_raw_id)
```

#### Expected Results
movie_inner_id value

#### Actual Results
ValueError: Item 1060 is not part of the trainset.

#### Versions

Windows-10-10.0.17134-SP0
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
surprise 1.0.6

**Comment by NicolasHug** [comment]
https://surprise.readthedocs.io/en/stable/FAQ.html#what-are-raw-and-inner-ids
