### ISSUE TITLE
Execution Issue in Train/Test split method of surprise\model_selection\split.py

### ISSUE THREAD

**Issue by snehaltamhane** [NicolasHug/Surprise#278]
#### Description

Description
Hello,
I just started playing with Surprise and I think it has the potential to be great. So far I found one issue. I will keep checking if I find more.
So in train-test split method, it throws and error message sometimes saying : 'DataFrame' object has no attribute 'raw_ratings'

trainset, testset = train_test_split(data, test_size=.25)

Thansks

**Comment by snehaltamhane** [comment]
My data has 3 columns, user,item and decile value all integers.

**Comment by NicolasHug** [comment]
you can't use a df with train_test_split. You need to load your df, get a dataset object, and then pass it to train_test_split. Please refer to the example in the docs
