### ISSUE TITLE
calculate rating by using embedding matrix and bias matrix

### ISSUE THREAD

**Issue by huipingfang** [NicolasHug/Surprise#284]
Hi Nicolas, 

I am using svd to build a recommender. I was able to use the predict method to get estimated rating for user/item pair. I saw some weird results so I wanted to manually verify the ratings by calculating from dot product of the embedding vectors plus bias vectors. 

The number from predict method was quite different from my manually calculation. 

For example:

In [278]: svd.predict(trainset.to_raw_uid(100), trainset.to_raw_iid(100), 0, verbose = True)
user: 5c5f75febe029b0035cceece item: ec000000000000000412913d r_ui = 0.00   est = 0.34   {'was_impossible': False}
Out[278]: Prediction(uid='5c5f75febe029b0035cceece', iid='ec000000000000000412913d', r_ui=0, est=0.33821807567055817, details={'was_impossible': False})

In [280]: np.dot(svd.pu[100], svd.qi[100])+svd.bu[100]+svd.bi[100]
Out[280]: -0.45484041755349003

I also looked the issue #25 here (https://github.com/NicolasHug/Surprise/issues/25) and included global_mean in the calculation but it was still not quite right. 
In [306]: est = svd.trainset.global_mean                                                                                                                                                             
     ...: est += svd.bu[100]                                                                                               
     ...: est += svd.bi[100]                                              
     ...: est += np.dot(svd.qi[100], svd.pu[100])

In [307]: est
Out[307]: 0.9207664410417417

If you can quickly spot what I did wrong, it is greatly appreciated! 

#### Versions

Windows-10-10.0.17763-SP0
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 18:50:55) [MSC v.1915 64 bit (AMD64)]
surprise 1.0.6

**Comment by NicolasHug** [comment]
`predict` accepts raw ids but the arrays bu bi pu pi accept inner ids.

**Comment by NicolasHug** [comment]
Oh you're convering properly sorry.

What version are you using? There used to be an offset in the predictions to make them always positive. It's been removed but I don't remember if it made it into the latest release or not.

Your computation (with the mean) looks correct

**Comment by huipingfang** [comment]
Thanks Nicolas.

> Oh you're convering properly sorry.

> What version are you using? 
**Versions
Windows-10-10.0.17763-SP0
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 18:50:55) [MSC v.1915 64 bit (AMD64)]
surprise 1.0.6**

> There used to be an offset in the predictions to make them always positive. It's been removed but I don't remember if it made it into the latest release or not.
**It seems that my estimated ratings are still within the range (mine is (0,1])**

> Your computation (with the mean) looks correct
**But I am still not getting the same value of rating from predict method. :( 
And all my ratings from the data is between 0 and 1, the global mean is 1.37 - that can't be right...
In [291]: trainset.global_mean
Out[291]: 1.3754024217865013**

**Comment by NicolasHug** [comment]
Right, so I removed this offset thing but it's still present in 1.0.6

The predictions you get from `predict` should be correct, but the predictions that you "manually" compute have an offset (for technical reason I needed all the ratings to be strictly postive)

The offset is calculated as

```py
            lower_bound, higher_bound = rating_scale
            self.offset = -lower_bound + 1 if lower_bound <= 0 else 0
```

**Comment by huipingfang** [comment]
> Right, so I removed this offset thing but it's still present in 1.0.6
**Sorry I am still a little confused. Why you decided to remove offset if you have to keep all ratings to be strictly positive? Is this "trainset.offset" the offset you are talking about? (in my dataset it is 1)**

> The predictions you get from `predict` should be correct, but the predictions that you "manually" compute have an offset (for technical reason I needed all the ratings to be strictly postive)
**I also believe the rating from `predict` is correct. But I observed that one particular item has been scored high (as top item recommended) to many different users in my case so I want to get to the bottom of it... 
Is there still a way now to "manually" compute the ratings using bu bi pu and qi (and offset) in this current version?**

> The offset is calculated as
> 
> ```python
>             lower_bound, higher_bound = rating_scale
>             self.offset = -lower_bound + 1 if lower_bound <= 0 else 0
> ```
> **Is this 1 in the second line a constant or the upper limit of the ratings?**

**Comment by NicolasHug** [comment]
>Why you decided to remove offset

We don't need it anymore

>Is this "trainset.offset" the offset you are talking about?

Yes 

>Is there still a way now to "manually" compute the ratings using bu bi pu and qi (and offset) in this current version?

Yes, exactly the same

>  Is this 1 in the second line a constant

It is a constant.

**Comment by huipingfang** [comment]
Thanks again. I tried the movie dataset (where the trainset offset is 0) and i was able to compute ratings manually with the global mean. 

So when offset is nonzero, don't I need to incorporate offset (non-zero) somewhere in the calculation? and how is global_mean calculated? The global_mean i am getting is greater than the upper bound of ratings in my input data.

**Comment by NicolasHug** [comment]
>  don't I need to incorporate offset (non-zero) somewhere in the calculation?

yes, you need to subtract the offset

The global mean is the mean of the offseted trainset.

(The code isn't that big, feel free to take a look at it)

**Comment by NicolasHug** [comment]
>  don't I need to incorporate offset (non-zero) somewhere in the calculation?

yes, you need to subtract the offset

The global mean is the mean of the offseted trainset.

(The code isn't that big, feel free to take a look at it)

**Comment by huipingfang** [comment]
Thanks Nicolas for your detailed explanation! 
I reran everything again today and had exact estimated ratings from both predict method and manual calculation like this. (yay!) We can close this track. Thanks again!

**np.dot(svd.pu[m], svd.qi[n])+svd.bu[m]+svd.bi[n]+trainset.global_mean - trainset.offset**

**Comment by NicolasHug** [comment]
Cool, thanks for reporting back!
