### ISSUE TITLE
Not Really an Issue: Curiosity about not directly initializing pu and qi 

### ISSUE THREAD

**Issue by Babas10** [NicolasHug/Surprise#288]
I am trying to build a recommender system with a dataset that will be growing over time. Normally I will get new users with new recommendations. Instead of running everything again, I thought that when using an algorithm like SVD or NMF it would be interesting to keep the movie coefficients qi. However, after a check in the source code, you only initialize those variables when the fit function is called. Is there a reason to do so and not initialize pu and qi when creating the algorithm? I tried to modify the source code and compile the package but I'm getting a lot of trouble with Cython. I also tried to clone the git repository and use python3 setup.py build but again I have problems with the .pyx files. I am not willing you to help me with those problems but rather I would like to know why pu and qi are not initialized when the algorithm is instantiated. 

Best.

**Comment by NicolasHug** [comment]
>  I would like to know why pu and qi are not initialized when the algorithm is instantiated.

because when the algorithm is instanciated we don't know the size of the data (number of users and number of items) so we cannot allocate the arrays.

**Comment by Babas10** [comment]
Thank you Nicolas, I didn't think about.

Congratulation for you Suprise it's really useful.

Best,

Babas.

**Comment by NicolasHug** [comment]
Thanks!
