### ISSUE TITLE
Command line error, "name 'reader' is not defined"

### ISSUE THREAD

**Issue by yokebtc** [NicolasHug/Surprise#289]
Install the centos7 command and run

> surprise -algo SVD -params "{'n_epochs': 5, 'verbose': True}" -load-custom ~/u.data -reader "Reader(line_format='user item rating timestamp',sep='\t')" -n-folds 3

Control display error

 

> Traceback (most recent call last):
  File "/usr/local/bin/surprise", line 11, in <module>
    load_entry_point('scikit-surprise==1.0.6', 'console_scripts', 'surprise')()
  File "/usr/local/lib64/python3.6/site-packages/surprise/__main__.py", line 175, in main
    reader = eval(args.reader)
  File "<string>", line 1, in <module>
NameError: name 'Reader' is not defined

**Comment by NicolasHug** [comment]
Thanks for the report, I can reproduce.

It should be fix now in the master branch: https://github.com/NicolasHug/Surprise/commit/89fb7a243755c45d54570a441b644f37cde1cc46

**Comment by NicolasHug** [comment]
Issue is fixed as far as I can tell, so I'll close
