### ISSUE TITLE
Can we load data using pandas data frame? 

### ISSUE THREAD

**Issue by dilipbobby** [NicolasHug/Surprise#29]
Hi,
In the code example, Input data is taken from a file.

file_path = os.path.expanduser('~/.surprise_data/ml-100k/ml-100k/u.data')

reader = Reader(line_format='user item rating timestamp', sep='\t')

data = Dataset.load_from_file(file_path, reader=reader)

can we load pandas data frame in the place of file-Input ? please share a code snippet if yes .

**Comment by NicolasHug** [comment]
Hi, this has already been answered in two previous issues so please refer to these.
Nicolas
