### ISSUE TITLE
A problem about sparse_matrix

### ISSUE THREAD

**Issue by zhouhaoUCAS** [NicolasHug/Surprise#290]
######
svd_matrix=sparse.load_npz(config.save_data_folder+'user_item_matrix.npz')
reader=Reader()
data=Dataset.load_from_file(config.save_data_folder+'user_item_matrix.npz',reader=None)
data.split(n_folds=5)
#######
Due to the limited computer memory, I used sparse_matrix.But I don't know how to input Dataset

**Comment by NicolasHug** [comment]
You can only load a dataset from a file or from a pandas dataframe, as explained in the docs.
