### ISSUE TITLE
Feature Request: Factorization Matrix with custom categorical data.

### ISSUE THREAD

**Issue by Sajades** [NicolasHug/Surprise#291]
Hi
Sometimes for the recommender systems we need to use categorical data as input for matrix factorization method for instance: age,gender, tags, watch lists, country, ... .
In the document it emphases we just allowed to use (item,user,rating) data as input.
It would be great if there be this feature in this package.
Thank you so much

**Comment by NicolasHug** [comment]
As mentionned multiple times already, that's not in the roadmap.
