### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by JunweiSUN** [NicolasHug/Surprise#293]
Hi, thanks for building this project. It helps a lot.

I have 2 questions:
First, I have a large dataset (around 1,000,000 users), so after I run these lines

train_data = Dataset.load_from_file(train_file_path, reader=train_reader)
train_set = train_data.build_full_trainset()

I nearly run out of my memory. So can I release "train_data" (by "del train_data") to free some memory after "train_set" is generated?

Second, is there any way to parallel my code so that I can accelerate the computation process?

Looking forward to your reply!

**Comment by NicolasHug** [comment]
> So can I release "train_data" (by "del train_data") to free some memory after "train_set" is generated?

Have you tried? It it works, you can.


> Second, is there any way to parallel my code so that I can accelerate the computation process?

The prediction algorithms aren't parallel, but the grid search and CV tools are (using joblib).
