### ISSUE TITLE
Installation error - Could not find entry point

### ISSUE THREAD

**Issue by Kshitij-N-Kulkarni** [NicolasHug/Surprise#295]
#### Description

I am just trying to install scikit-surprise, no code yet. When I try to run conda install -c conda-forge scikit-surprise and then press y, I get the following error:

The procedure entry point OPENSSL_sk_new_reserve could not be located in the dynamic link library libcrypto-1_1-x64.dll.

I am installing it in the same directory where I have successfully install all my other python packages. Please help! Thank you.

#### Versions
Windows-7-6.1.7601-SP1
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Traceback (most recent call last):

  File "<ipython-input-16-2650e1758aa9>", line 3, in <module>
    import surprise; print("surprise", surprise.__version__)

ModuleNotFoundError: No module named 'surprise'

![image](https://user-images.githubusercontent.com/7242095/63201857-e0491480-c03b-11e9-9b8d-ec2810a2bfb0.png)

**Comment by J-A-Gray** [comment]
What version of Anconda are you on?

[Try this!](https://github.com/conda/conda/issues/9003#issuecomment-516499958)

**Comment by Kshitij-N-Kulkarni** [comment]
Anaconda Version: 2019.07 Python 3.7

**Comment by NicolasHug** [comment]
Thanks for the help @J-A-Gray 	!

@Kshitij-N-Kulkarni 	, did that solve your issue?

I would suggest trying to solve the `OPENSSL_sk_new_reserve` issue first. That might be what is causing the issue with surprise.

**Comment by Kshitij-N-Kulkarni** [comment]
Hi,
Reinstalling worked for me. The files were, in fact saved at different dates. Thank you @J-A-Gray @NicolasHug

**Comment by Devaharsha-TheProgrammer** [comment]
I had the same issue.

As **SimonCarozza** told, 
follow the following steps,
It works great.

The  libssl-1_1-x64 dlls in Anaconda/DLLS     and
Anaconda/Library/bin 
being installed at different dates, 
So, Copy the one in Anaconda/DLLS and replace that in Anaconda/Library/bin

Conda must start working again, and you should be able to install new packages again.

Hope it helps

**Comment by sankethv** [comment]
It worked. copied the libssl-1_1-x64.dll in Anaconda/DLLS and replaced that in Anaconda/Library/bin

**Comment by richdevboston** [comment]
This fix by Simon Carozza no longer works without introducing another error.  I copied the DLL as required : copies "libssl-1_1-x64.dll" in "Anaconda/DLLS" to "Anaconda/Library/bin```.  Now when I use conda 4.8.5 to install or update packages, conda actually works, but the installation throws an error "[WinError 127] The specified procedure could not be found" for every package that conda installs.  It works, but APPEARS not to work.  When I check the version of the package at the command line, e.g., ```>>> git --version``` it gives me the correct answer for version or location

```
# git --version
git version 2.23.0.windows.1

# conda list git
# packages in environment at C:\ProgramData\Anaconda3\envs\widgets-jcon20:
#
# Name                    Version                   Build  Channel
m2w64-libwinpthread-git   5.0.0.4634.697f757               2

```

I still get the annoying pop-up `The procedure entry point OPENSSL_sk_new_reserve could not be located in the dynamic link library libcrypto-1_1-x64.dll`

**Comment by richdevboston** [comment]
When I followed the post here:  https://demon-data.blogspot.com/2019/05/anaconda-ssl-install-issue.html it recommended copying several DLLs, 

libcrypto-1_1-x64.dll
libcrypto-1_1-x64.pdb
libssl-1_1-x64.dll
libssl-1_1-x64.pdb

After I copied them the DLLs `libcrypto` and `libssl` files, conda started working again.

**Comment by rhurley46** [comment]
> I had the same issue.
> 
> As **SimonCarozza** told,
> follow the following steps,
> It works great.
> 
> The libssl-1_1-x64 dlls in Anaconda/DLLS and
> Anaconda/Library/bin
> being installed at different dates,
> So, Copy the one in Anaconda/DLLS and replace that in Anaconda/Library/bin
> 
> Conda must start working again, and you should be able to install new packages again.
> 
> Hope it helps

Thank you for this. It has worked - key point being the same date and time of installation.
