### ISSUE TITLE
Unable to retrieve Adjacency Matrix after applying, or to test Recommendation manually

### ISSUE THREAD

**Issue by RohitJacob** [NicolasHug/Surprise#30]
If i have a M x N features, I want to be able to conver this into M x M matrix to be useful

**Comment by NicolasHug** [comment]
Hi,

I don't understand at all what you need.

Nicolas

**Comment by RohitJacob** [comment]
@NicolasHug instead of using
 `perf = evaluate(algo, data, measures=['RMSE', 'MAE'])`
I want to get a output matrix Movies x Movies, where the values inside are the distance/similarity between two Movies.

**Comment by NicolasHug** [comment]
Ho sure, you'll just have to read the docs then.
