### ISSUE TITLE
Importing a Computed Similarity Matrix

### ISSUE THREAD

**Issue by cuilongyin** [NicolasHug/Surprise#300]
#### Description

Hi, dear Nicolas:

Is there a way for me to import a similarity matrix? I have precomputed a similarity matrix using a pretty bizarre algorithm to do some research. I want to replace the similarity function call with a result number. So instead of computing sim(u,v), I want to directly copy the value from the similarity matrix that I have pre-computed.

Thank you very much...

#### Versions

Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
surprise 1.0.6

**Comment by NicolasHug** [comment]
you could just inherit from whichever algorithm you want and override `fit` and set the `self.sim` attribute there.

for example `KNNBasic.fit` is just:

```py
  6     def fit(self, trainset):                                                   
  5                                                                                
  4         SymmetricAlgo.fit(self, trainset)                                      
  3         self.sim = self.compute_similarities()                                 
  2                                                                                
  1         return self 
```

So just hard set `self.sim` instead of calling `self.compute_similarities()`                                 
`

**Comment by cuilongyin** [comment]
Got it

Thank you very much
Best,

Longyin Cui
Computer Science, University of Kentucky
Davis Marksbury Building
Email: lcu225@uky.edu
Phone: 740-704-7169
On Sep 24, 2019, 3:36 PM -0400, Nicolas Hug <notifications@github.com>, wrote:

you could just inherit from whichever algorithm you want and override fit and set the self.sim attribute there.

for example KNNBasic.fit is just:

  6     def fit(self, trainset):
  5
  4         SymmetricAlgo.fit(self, trainset)
  3         self.sim = self.compute_similarities()
  2
  1         return self

So just hard set self.sim instead of calling self.compute_similarities()
`
