### ISSUE TITLE
Training specific users in the whole trainset for KNN based algorithms.

### ISSUE THREAD

**Issue by Babas10** [NicolasHug/Surprise#306]
--> Hey Nicolas, first I wanted to congratulate you, for the amazing job you have done with this library. Thank you for sharing your work with the community.

The situation is the following, I have two sources of data, one from Kaggle and one from my website. In order, to overcome the cold start problem, what I did is to merge both datasets so that I directly have a lot of ratings.

As far I understood, when we use the build_full_trainset() function for a KNN based algorithm, the algorithm basically calculates the similarity between all the users or between the items. Then this similarity is used to predict the ratings.

My questions: Is there a way to train only one user, i.e (in my understanding) calculate only the similarities between a user x and all the other users, without calculating all the remaining similarities. In other words, is there a way to calculate the similarity of a user from the dataset of my website with all the users from the kaggle dataset without calculating the similarity within the kaggle users.

I hope you will be able to give me a response.

Have a nice weekend.

Babas

**Comment by NicolasHug** [comment]
Hi Babas,

> Is there a way to train only one user, i.e (in my understanding) calculate only the similarities between a user x and all the other users, without calculating all the remaining similarities

No, unfortunately this is not possible. The similarity computation will always be `n*n` where `n` is the number of items, or users. There is no way to compute the similarity of a single user/item with the rest of the dataset.

**Comment by Babas10** [comment]
Hi Nicolas,

Thank you for you answer! Then Will have to proceed differently.

Have a nice day.

Babas.
