### ISSUE TITLE
''MyOwnAlgorithm' object has no attribute 'verbose'' occurred after running `with_baselines_or_sim.py`.

### ISSUE THREAD

**Issue by biomchen** [NicolasHug/Surprise#308]
#### Description
Dear Nicolas, 

I have run \building_custom_algorithms\with_baselines_or_sim.py, then the error occurs. So I have check the errors and find a temporary solution (see below). 

I wonder if my solution is right? If not, would you please fix it?

Thank you.

#### Steps/Code to Reproduce
Same codes without no modification. 

#### Expected Results
Expect return the first three most similar iuds and calculated bsl.

#### Actual Results
''MyOwnAlgorithm' object has no attribute 'verbose''

#### Solutions
I have added 'self.verbose = True' in the def__init__(self, **kwargs) of the ago_base.py. Hopefully, my temporary solution is right.

#### Versions
Darwin-18.7.0-x86_64-i386-64bit
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
surprise 1.0.6

**Comment by NicolasHug** [comment]
Thanks for the report, it should have been fixed by https://github.com/NicolasHug/Surprise/commit/f92e54d04b8d1b6fdf96aab107212c2beafc6cb3 already

You should update surprise version to 1.1.0

**Comment by biomchen** [comment]
Thank you for your feedback. I will update mine.
