### ISSUE TITLE
what should be the Format of predefined Testset and Trainset

### ISSUE THREAD

**Issue by kirtigroover** [NicolasHug/Surprise#309]
Hello,

I am trying to use the predefined train and test folds using cross validation. My train and test set is a CSV file with userid, itemid and ratings. 

Could you help me identify the correct format, so that I can create my file in correct format. 

files_dir_train = os.path.expanduser('~/Recommendation_System/Training_strategy/train_output_duplicate.csv')
files_dir_test = os.path.expanduser('~/Recommendation_System/Training_strategy/test_output_duplicate.csv')
train_file = files_dir_train
test_file = files_dir_test
folds_files = [(train_file,test_file)]
reader = Reader(line_format='user item rating', sep='\t')
data = Dataset.load_from_folds(folds_files, reader=reader)
pkf = PredefinedKFold()
for trainset, testset in pkf.split(data):
algo.fit(trainset)
predictions= algo.test(testset)

Error : Impossible to parse line. Check the line_format and sep parameters.

**Comment by NicolasHug** [comment]
I can't unless you show me what your file looks like

**Comment by kirtigroover** [comment]
My file looks like this, its a CSV file, 


  | User_id | Item_id | Score
-- | -- | -- | --
0 | 303 | 103 | 0
1 | 303 | 104 | 0
2 | 303 | 105 | 1
3 | 303 | 106 | 0
4 | 303 | 116 | 0
5 | 303 | 119 | 0
6 | 303 | 120 | 1
7 | 303 | 121 | 1
8 | 303 | 122 | 0
9 | 303 | 123 | 1
10 | 303 | 128 | 0
11 | 303 | 130 | 1
12 | 303 | 131 | 1
13 | 303 | 133 | 1
14 | 303 | 134 | 1
15 | 303 | 139 | 1
16 | 303 | 141 | 1
17 | 303 | 142 | 0

**Comment by NicolasHug** [comment]
Can you please copy/paste some actual lines from your files? If there are `|` and `--` in your file, this is not actually a CSV

**Comment by kirtigroover** [comment]
my bad, 

I corrected my code to be and updated sep as " , "

reader = Reader(line_format='user item rating', sep=',')

,band_id,influencer_id,Groover_Score
0,303,103,0.0
1,303,104,0.0
2,303,105,1.0
3,303,106,0.0

Now error is : 

----> 8 for trainset, testset in pkf.split(data):
      9 
     10     # train and test algorithm.

~/.local/lib/python3.7/site-packages/surprise/model_selection/split.py in split(self, data)
    432         for train_file, test_file in data.folds_files:
    433 
--> 434             raw_trainset = data.read_ratings(train_file)
    435             raw_testset = data.read_ratings(test_file)
    436             trainset = data.construct_trainset(raw_trainset)

~/.local/lib/python3.7/site-packages/surprise/dataset.py in read_ratings(self, file_name)
    172         with open(os.path.expanduser(file_name)) as f:
    173             raw_ratings = [self.reader.parse_line(line) for line in
--> 174                            itertools.islice(f, self.reader.skip_lines, None)]
    175         return raw_ratings
    176 

~/.local/lib/python3.7/site-packages/surprise/dataset.py in <listcomp>(.0)
    171 
    172         with open(os.path.expanduser(file_name)) as f:
--> 173             raw_ratings = [self.reader.parse_line(line) for line in
    174                            itertools.islice(f, self.reader.skip_lines, None)]
    175         return raw_ratings

~/.local/lib/python3.7/site-packages/surprise/reader.py in parse_line(self, line)
    102                              ' and sep parameters.')
    103 
--> 104         return uid, iid, float(r) + self.offset, timestamp

ValueError: could not convert string to float:

**Comment by NicolasHug** [comment]
Is that line at the top of your file?

`,band_id,influencer_id,Groover_Score`

if yes, please read the docs and use `skip_lines`.


Another option is to just load your data into pandas and use the dataframe

**Comment by kirtigroover** [comment]
I tried below mentioned approach earlier but it didn't work for user defined train_data and test_data

reader = Reader(rating_scale=(1,10)) 

# for test_data
test_data = Dataset.load_from_df(test_input[['user_id' , 'item_id' , 'Score' ]], reader)

# for train_data
train_data = Dataset.load_from_df(train_input[['user_id' , 'item_id' , 'Score' ]], reader)

algo = SVD() 

I am aware that I cannot pass my train_data and test_data directly to algo.fit or algo.test, but I don't know the step which will transform these 2 sets and make them suitable for the operation directly. 

algo.fit(train_data)     
predictions = algo.test(test_data) 

Thanks for your help !!!

**Comment by kirtigroover** [comment]
Conclusion : you can use folds when trying to use user defined train and test data. 
Just remember the format of your file, its as mentioned below, remember to not include header or Index in your file. 
Userid, ItemID, rating, timestamp

**Comment by NicolasHug** [comment]
Can I close the issue?

**Comment by kirtigroover** [comment]
yes, I am able to work with my customer datasets now, Thanks for the help!!
