### ISSUE TITLE
Error with 'mse' measure in GridSearchCV

### ISSUE THREAD

**Issue by shreygarg** [NicolasHug/Surprise#311]
The following code works fine when the similarity measure used is 'rmse' but gives an error when the measure used is 'mse'. Can you please have a look and let me know what the issue is?

`
param_grid = {'n_factors': [2], 'lr_all': [0.1,0.01,0.001,0.04], 'reg_all': [.1]}
gs = surprise.model_selection.GridSearchCV(surprise.SVDpp, param_grid, measures= ['mse'], cv=5, joblib_verbose=10,n_jobs=-2)
gs.fit(data)
`

Error:

<ipython-input-11-90c4fab37610> in <module>
      6 param_grid = {'n_factors': [1], 'lr_all': [0.1,0.01,0.001,0.04], 'reg_all': [.1]}  
      7 gs = surprise.model_selection.GridSearchCV(surprise.SVDpp, param_grid, measures= ['mse'], cv=5, joblib_verbose=10)
----> 8 gs.fit(data)
      9 print("model trained")
     10 print(gs.best_params['mse'])

~\Anaconda3\lib\site-packages\surprise\model_selection\search.py in fit(self, data)
    153             elif m in ('fcp',):
    154                 best_index[m] = mean_test_measures.argmax()
--> 155             best_params[m] = self.param_combinations[best_index[m]]
    156             best_score[m] = mean_test_measures[best_index[m]]
    157             best_estimator[m] = self.algo_class(**best_params[m])

KeyError: 'mse'

**Comment by NicolasHug** [comment]
Thanks, I can reproduce.

Should be fixed in https://github.com/NicolasHug/Surprise/pull/313.

Meanwhile I would just suggest to use the rmse and square it. The best parameter combinations are the same, only the scores differ
