### ISSUE TITLE
Can we do GridSearchCV for dataset loaded from folds_files ?

### ISSUE THREAD

**Issue by kirtigroover** [NicolasHug/Surprise#315]
combined_data = Dataset.load_from_folds(folds_files, reader=reader) --> this is going to give us combined data for test and train set

gs = GridSearchCV(CoClustering, param_grid, measures=['rmse','mae'], cv=3)
gs.fit(combined_data)

Error : 'DatasetUserFolds' object has no attribute 'raw_ratings'

Is it possible to perform Gridserach when I am using load_from_folds to load my custom train and testset? I saw below mentioned text on the tutorial, it appears I cant , can you please confirm?

refit (bool or str) – If True, refit the algorithm on the whole dataset using the set of parameters that gave the best average performance for the first measure of measures. Other measures can be used by passing a string (corresponding to the measure name). Then, you can use the test() and predict() methods. refit can only be used if the data parameter given to fit() hasn’t been loaded with load_from_folds(). Default is False.

Thanks in advance!

**Comment by NicolasHug** [comment]
You should be using https://surprise.readthedocs.io/en/stable/model_selection.html#surprise.model_selection.split.PredefinedKFold

**Comment by kirtigroover** [comment]
I have been using the function mentioned below and have been able to make predictions successfully. 

pkf = PredefinedKFold()

algo = SVD()

for trainset, testset in pkf.split(data):

    # train and test algorithm.
    algo.fit(trainset)
    predictions = algo.test(testset)

    # Compute and print Root Mean Squared Error
    accuracy.rmse(predictions, verbose=True)

My Issue is different, I want to Tune my algorithm parameters with GridSearchCV, but I am not sure if we can do gridsearch when we have loaded the data using folds_files. Right now when i use it I get an error message as mentioned. 

gs = GridSearchCV(CoClustering, param_grid, measures=['rmse','mae'], cv=3)
gs.fit(combined_data)

Error : 'DatasetUserFolds' object has no attribute 'raw_ratings'

**Comment by NicolasHug** [comment]
You should change `cv=` to use a predifinedKFold as explained in the docs

**Comment by NicolasHug** [comment]
Please LMK if it doesn't work. If it does, please close the issue

**Comment by kirtigroover** [comment]
> You should change `cv=` to use a predifinedKFold as explained in the docs

I tried changing CV value to 1, as my data is 1 fold, but even that doesnt resolve the issue, still getting the same error.

 I went through the documentation but I wasnt able to find any mention of how to use GridSearchCV function while  using Dataset.load_from_folds. 

AttributeError                            Traceback (most recent call last)
<ipython-input-59-0dc0dd0b74be> in <module>
      2 
      3 gs = GridSearchCV(CoClustering, param_grid, measures=['rmse','mae'], cv=1)
----> 4 gs.fit(combined_data)
      5 print("Best predictions for optimum RMSE in Coclustering Algo on Groover data")
      6 print("score")

~/.local/lib/python3.7/site-packages/surprise/model_selection/search.py in fit(self, data)
     84                                    self.return_train_measures)
     85             for params, (trainset, testset) in product(self.param_combinations,
---> 86                                                        cv.split(data))
     87         )
     88         out = Parallel(n_jobs=self.n_jobs,

~/.local/lib/python3.7/site-packages/surprise/model_selection/split.py in split(self, data)
     93         '''
     94 
---> 95         if self.n_splits > len(data.raw_ratings) or self.n_splits < 2:
     96             raise ValueError('Incorrect value for n_splits={0}. '
     97                              'Must be >=2 and less than the number '

AttributeError: 'DatasetUserFolds' object has no attribute 'raw_ratings'

**Comment by NicolasHug** [comment]
You need to pass `cv=PredefinedKFold()`

**Comment by kirtigroover** [comment]
Thanks for your reply! I am no longer getting an error.
