### ISSUE TITLE
'BaselineOnly' object is not callable

### ISSUE THREAD

**Issue by dewangsatyam** [NicolasHug/Surprise#318]
reader = Reader(rating_scale=(1,5))
train_data = Dataset.load_from_df(reg_train[['user', 'movie', 'rating']], reader)
trainset = train_data.build_full_trainset() 

from surprise import BaselineOnly
from surprise.model_selection.search import GridSearchCV

bsl_algo = BaselineOnly()

param_grid = {'bsl_options': {'method': ['sgd'],'learning_rate': [0.01, 0.1]}}
grid_cfl = GridSearchCV(bsl_algo, param_grid , measures=['rmse'], cv=3,n_jobs=-1, joblib_verbose= 10)

grid_cfl.fit(train_data)

print (grid_cfl.best_params_)

---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
    795             try:
--> 796                 tasks = self._ready_batches.get(block=False)
    797             except queue.Empty:

/usr/lib/python3.5/queue.py in get(self, block, timeout)
    160                 if not self._qsize():
--> 161                     raise Empty
    162             elif timeout is None:

Empty: 

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-44-72c222ffd45b> in <module>
      7 grid_cfl = GridSearchCV(bsl_algo, param_grid , measures=['rmse'], cv=3,n_jobs=-1, joblib_verbose= 10)
      8 
----> 9 grid_cfl.fit(train_data)
     10 
     11 # combination of parameters that gave the best RMSE score

/usr/local/lib/python3.5/dist-packages/surprise/model_selection/search.py in fit(self, data)
     88         out = Parallel(n_jobs=self.n_jobs,
     89                        pre_dispatch=self.pre_dispatch,
---> 90                        verbose=self.joblib_verbose)(delayed_list)
     91 
     92         (test_measures_dicts,

/usr/local/lib/python3.5/dist-packages/joblib/parallel.py in __call__(self, iterable)
   1001             # remaining jobs.
   1002             self._iterating = False
-> 1003             if self.dispatch_one_batch(iterator):
   1004                 self._iterating = self._original_iterator is not None
   1005 

/usr/local/lib/python3.5/dist-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
    805                 big_batch_size = batch_size * n_jobs
    806 
--> 807                 islice = list(itertools.islice(iterator, big_batch_size))
    808                 if len(islice) == 0:
    809                     return False

/usr/local/lib/python3.5/dist-packages/surprise/model_selection/search.py in <genexpr>(.0)
     83                                    testset, self.measures,
     84                                    self.return_train_measures)
---> 85             for params, (trainset, testset) in product(self.param_combinations,
     86                                                        cv.split(data))
     87         )

TypeError: 'BaselineOnly' object is not callable

**Comment by NicolasHug** [comment]
You need to pass a class, not an instance

**Comment by dewangsatyam** [comment]
This worked!!!
Thanks for the reply.
