### ISSUE TITLE
Install Surprise on Datalabs

### ISSUE THREAD

**Issue by sfessi** [NicolasHug/Surprise#32]
Hi there,

I'm trying to install Surprise on Datalabs directly in a script using the command:
%%bash
pip install scikit-surprise

I use Windows.

Getting the following error:
Collecting scikit-surprise
  Using cached scikit-surprise-1.0.3.tar.gz
Requirement already satisfied: numpy>=1.11.2 in /usr/local/lib/python2.7/dist-packages (from scikit-surprise)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from scikit-surprise)
Building wheels for collected packages: scikit-surprise
  Running setup.py bdist_wheel for scikit-surprise: started
  Running setup.py bdist_wheel for scikit-surprise: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9Dmyhg/scikit-surprise/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpSd64VXpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/surprise
  copying surprise/accuracy.py -> build/lib.linux-x86_64-2.7/surprise
  copying surprise/dataset.py -> build/lib.linux-x86_64-2.7/surprise
  copying surprise/dump.py -> build/lib.linux-x86_64-2.7/surprise
  copying surprise/__init__.py -> build/lib.linux-x86_64-2.7/surprise
  copying surprise/__main__.py -> build/lib.linux-x86_64-2.7/surprise
  copying surprise/evaluate.py -> build/lib.linux-x86_64-2.7/surprise
  creating build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/random_pred.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/predictions.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/baseline_only.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/__init__.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/algo_base.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/knns.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  running egg_info
  writing requirements to scikit_surprise.egg-info/requires.txt
  writing scikit_surprise.egg-info/PKG-INFO
  writing top-level names to scikit_surprise.egg-info/top_level.txt
  writing dependency_links to scikit_surprise.egg-info/dependency_links.txt
  writing entry points to scikit_surprise.egg-info/entry_points.txt
  reading manifest file 'scikit_surprise.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'scikit_surprise.egg-info/SOURCES.txt'
  copying surprise/similarities.c -> build/lib.linux-x86_64-2.7/surprise
  copying surprise/similarities.pyx -> build/lib.linux-x86_64-2.7/surprise
  copying surprise/prediction_algorithms/co_clustering.c -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/co_clustering.pyx -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/matrix_factorization.c -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/matrix_factorization.pyx -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/optimize_baselines.c -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/optimize_baselines.pyx -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/slope_one.c -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  copying surprise/prediction_algorithms/slope_one.pyx -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
  running build_ext
  building 'surprise.similarities' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/surprise
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c surprise/similarities.c -o build/temp.linux-x86_64-2.7/surprise/similarities.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for scikit-surprise
Failed to build scikit-surprise
Installing collected packages: scikit-surprise
  Running setup.py install for scikit-surprise: started
    Running setup.py install for scikit-surprise: finished with status 'error'
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9Dmyhg/scikit-surprise/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ulJEFx-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/surprise
    copying surprise/accuracy.py -> build/lib.linux-x86_64-2.7/surprise
    copying surprise/dataset.py -> build/lib.linux-x86_64-2.7/surprise
    copying surprise/dump.py -> build/lib.linux-x86_64-2.7/surprise
    copying surprise/__init__.py -> build/lib.linux-x86_64-2.7/surprise
    copying surprise/__main__.py -> build/lib.linux-x86_64-2.7/surprise
    copying surprise/evaluate.py -> build/lib.linux-x86_64-2.7/surprise
    creating build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/random_pred.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/predictions.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/baseline_only.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/__init__.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/algo_base.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/knns.py -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    running egg_info
    writing requirements to scikit_surprise.egg-info/requires.txt
    writing scikit_surprise.egg-info/PKG-INFO
    writing top-level names to scikit_surprise.egg-info/top_level.txt
    writing dependency_links to scikit_surprise.egg-info/dependency_links.txt
    writing entry points to scikit_surprise.egg-info/entry_points.txt
    reading manifest file 'scikit_surprise.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'scikit_surprise.egg-info/SOURCES.txt'
    copying surprise/similarities.c -> build/lib.linux-x86_64-2.7/surprise
    copying surprise/similarities.pyx -> build/lib.linux-x86_64-2.7/surprise
    copying surprise/prediction_algorithms/co_clustering.c -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/co_clustering.pyx -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/matrix_factorization.c -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/matrix_factorization.pyx -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/optimize_baselines.c -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/optimize_baselines.pyx -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/slope_one.c -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    copying surprise/prediction_algorithms/slope_one.pyx -> build/lib.linux-x86_64-2.7/surprise/prediction_algorithms
    running build_ext
    building 'surprise.similarities' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/surprise
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c surprise/similarities.c -o build/temp.linux-x86_64-2.7/surprise/similarities.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------

Any idea what's going on? I'm a simple statistician with average IT experience/knowledge, looking for an easy fix.

Cheers!

**Comment by NicolasHug** [comment]
Hi,

It seems that the machine you are using (the Datalabs machine) does not have a C compiler, hence the error 

    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Unfortunately I have absolutely zero experience with Datalabs, so I'll have a hard time helping you here.

**Comment by sfessi** [comment]
ok thank you!

**Comment by NicolasHug** [comment]
I stumbled upon [this post](https://stackoverflow.com/questions/42054259/cant-install-basemap-package-in-datalab-notebook) which suggest that you should be able to install gcc (a C compiler) on datalabs. Maybe that would fix your issue?
