### ISSUE TITLE
Fail to fit large training dataset

### ISSUE THREAD

**Issue by xuezhaokun** [NicolasHug/Surprise#320]
Hi,
I tried to load my own Pandas dataframe data into Dataset as described in the documentation. My dataframe size is (7234568 X 3). I tired to apply my data SVD and SVDPP() algorithms. It looks like my code just failed after the fit() function finished. I then tested it on a smaller data size, it succeed. I am wondering whether it is the library limitation for handling such large data size. Here is my code:
```df = pd.DataFrame(ratings_dict)
reader = Reader(rating_scale=(0, 1))
data = Dataset.load_from_df(df[['userID', 'itemID', 'rating']], reader)
trainset = data.build_full_trainset()
algo = SVD()
algo.fit(trainset)
// try to make prediction for a given user and item
pred = algo.predict(username, item_id,  verbose=False)
```
My code just terminates after calling fit(), when I use the large dataset. But everything works fine on smaller dataset. Do you have any suggestion on how to fix it? Thanks so much!

**Comment by NicolasHug** [comment]
Surprise wasn't necessarily built to be very memory efficient

Unfortunately i'm afraid the only answer is get more ram, or use a library that is more memory friendly and scalable

If you're only interested in SVD maybe lightfm would do, it's a factorization model too

**Comment by xuezhaokun** [comment]
Thanks for the quick reply. It might be that I do not have enough ram on my machine. I will take a look at lightfm. Thanks!
