### ISSUE TITLE
Can I access my Trainset User_ID and Item_ID

### ISSUE THREAD

**Issue by Kirti42** [NicolasHug/Surprise#322]
trainset, testset = train_test_split(data, test_size=.20)

I can access testset data using 
for row in testset:
    print(row[0], row[1],row[3])

but when I try same for trainset data its throwing an error : 'Trainset' object is not iterable

for row in trainset:
    print(row)
TypeError: 'Trainset' object is not iterable

I want to perform some metric calculation on metric function defined by me, for that I need to know what all user and item data I have in my trainset. 

Please let me know if there is any way to access trainset users and items?
Thanks in advance for your help!

**Comment by NicolasHug** [comment]
https://surprise.readthedocs.io/en/stable/trainset.html
