### ISSUE TITLE
This package sucks!!!

### ISSUE THREAD

**Issue by LiuHao-THU** [NicolasHug/Surprise#325]

**Comment by Kirti42** [comment]
If you will go through the document you will find out the ways to use surprise library to predict ratings which are not there in testset. If you have any question or doubt you must ask questions, rather than making an arrogant comment. 
It servers no purpose. your statement doesnt tell us where you are stuck, neither it tells us what you want to achive. nothing about your dataset. 
This library is availble for free, you have a community of people who repond, especially Nicolas. 
If you dont like it, please create a new library and share it with all of us. I would very much appriciate it.

**Comment by LiuHao-THU** [comment]
thanks for the reply, and I must apologize for making arrogant comment.   I will delete this issue soon!

**Comment by NicolasHug** [comment]
Ah, that gave me a good chuckle!

Thanks @Kirti42 for taking the time. Closing

**Comment by williamwei2** [comment]
Hi, I feel stuck in the installing process of using surprise pakage under Colab.google.research framewrok, the details is going like this:

**_1. copy the repository_**

**INPUT:** 
!git clone https://github.com/NicolasHug/surprise.git
**OUTPUT:**
Cloning into 'surprise'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 4257 (delta 10), reused 14 (delta 6), pack-reused 4221
Receiving objects: 100% (4257/4257), 6.36 MiB | 5.03 MiB/s, done.
Resolving deltas: 100% (2964/2964), done.

_**2. locate the corresondig file**_ 
**INPUT:** 
cd surprise
**OUTPUT:**
/content/surprise

**_3.Install_** 
**INPUT**
!python setup.py install
**OUTPUT**
(TOO LONG , SO IGNORE  DESCRIPITION ABOUT ADDING FILES)

**_4.import package_**
INPUT:
import pandas as pd
from surprise import Reader
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise import NormalPredictor
from surprise import KNNBasic
from surprise import KNNWithMeans
from surprise import KNNWithZScore
from surprise import KNNBaseline
from surprise import SVD
from surprise import BaselineOnly
from surprise import SVDpp
from surprise import NMF
from surprise import SlopeOne
from surprise import CoClustering
from surprise.accuracy import rmse
from surprise import accuracy
from surprise.model_selection import train_test_split

**OUTPUT**
ImportError                               Traceback (most recent call last)
<ipython-input-20-bc06588669df> in <module>()
      1 import pandas as pd
----> 2 from surprise import Reader
      3 from surprise import Dataset
      4 from surprise.model_selection import cross_validate
      5 from surprise import NormalPredictor

2 frames
/content/surprise/surprise/prediction_algorithms/algo_base.py in <module>()
      8                         unicode_literals)
      9 
---> 10 from .. import similarities as sims
     11 from .predictions import PredictionImpossible
     12 from .predictions import Prediction

ImportError: cannot import name 'similarities'

ANYONE COULD HELP THIS ? 

THANKS IN  ADVANCE
