### ISSUE TITLE
Suggestions for data with no ratings?

### ISSUE THREAD

**Issue by soliverc** [NicolasHug/Surprise#327]
I have data with purchases at the store level (no product info).

for example:

```
John Smith    MCDonalds    $4
John Smith    Burger King    $0
Mary Jones   Burger King     $10
Mary Jones   Sports Shop    $50
etc
etc
```
I noticed that all the tutorials are for data with products (i.e. "explicit rating data" according to the docs)

Is it possible to use this library to recommend stores based on purchase history? Has anybody tried this before? Could purchases be used as a rating perhaps? I was thinking of using average or median spend per store as a rating, but some stores could be car dealers etc. so "ratings" could range from 5 to 50,000. Which seems impractical. 

And if it's not recommended to use this library for my dataset, any suggestions on where to look? I guess my data is more "implicit"?

Thanks

**Comment by NicolasHug** [comment]
Please take some time to look at the numerous previous issues asking the same question.

Short answer is no.

**Comment by SSMK-wq** [comment]
@soliverc - did you find any solution to your problem? I am also experiencing a similar issue where my data has no explicit rating column. My data is exactly like yours where we have product id, frequency of purchases, user id, monetary value of purchases etc
