### ISSUE TITLE
How can i use another metric similarity in KNN

### ISSUE THREAD

**Issue by BillySurya** [NicolasHug/Surprise#33]
I have tried to make the euclidean and another metric and put them in similarities.pyx. But it doesnt work. How can i use the another metric for KNN?

Thanks,

**Comment by NicolasHug** [comment]
Hi,

What have you tried and what does not work?

**Comment by BillySurya** [comment]
Error: Wrong sim name euclidean. Allowed values are msd, pearson_baseline, cosine, pearson.  

I already add euclidean sim in algo.base.py   

construction_func = {'cosine': sims.cosine,
                             'msd': sims.msd,
                             'pearson': sims.pearson,
                             'pearson_baseline': sims.pearson_baseline
			     'euclidean':sims.euclidean}

but still doesnt work

**Comment by NicolasHug** [comment]
There's a missing comma in your dict but I suppose your code is correct, else you would have gotten an error there?

You seem to have done it correctly, so my guess would be that you are not using your custom version of surprise but rather the one that you have installed from PyPI? Maybe try a dirty `print('BLABLA')` in your code and see if it's printed?
 
Also, have you installed it locally in dev mode with `pip install -e .`? The `-e` is very important. In addition, as you have modified a Cython file, you will need to reinstall the package at each change.

**Comment by BillySurya** [comment]
Ok thanks, i have recorrect the coma. But it still doesnt work. I create euclidean metric is base in surprise lib. I only change the calculation
Cosine:
denum = np.sqrt(sqi[xi, xj] * sqj[xi, xj])
sim[xi, xj] = prods[xi, xj] / denum

sim[xj, xi] = sim[xi, xj]

To:
sim[xi, xj] = (proda[xi, xj] - prods[xi, xj])**2
sim[xi, xj] = np.sqrt(sim[xi, xj])

sim[xj, xi] = sim[xi, xj]

which proda[] already defined above

**Comment by NicolasHug** [comment]
Are you sure you are running the code that you have modified?

**Comment by BillySurya** [comment]
i need to install cython to run them?
i run it again with python give me an error in " cdef "

**Comment by BillySurya** [comment]
im really sorry, i just unfamiliar with Linux

**Comment by NicolasHug** [comment]
Yes you will need Cython and a C compiler.

Cython will compile the .pyx files into C code, and the C compiler will compile C code into an external extension / module.

You  may be interesting in checking the [contribution guidelines](https://github.com/NicolasHug/Surprise/blob/master/CONTRIBUTING.md) (you can forget coding style guidelines if you're not planning on a pull request)

**Comment by BillySurya** [comment]
Now i got the error.
similarities.c:4:20: fatal error: Python.h: No such file or directory

**Comment by NicolasHug** [comment]
Try Googling this, it is a known issue (also it is not related to Surprise).

**Comment by BillySurya** [comment]
i already compile it from pyx/pyc and c. for similarities and algo.base. But the error still popping around.
There is no other way to create other similarity metric for KNN?

**Comment by NicolasHug** [comment]
Well another way of doing this would be to extent the k-NN class and to redefine your own train() method, where you would compute the similarities here.

This is dirty but it would work. Note though that you would note be able to use the classic workflow for defining the similarity options.
