### ISSUE TITLE
Typo in the reason message in Prediction 

### ISSUE THREAD

**Issue by jpthirumalai** [NicolasHug/Surprise#330]
#### Description

There is some typo in the KNNWithMeans algorithm test method

#### Steps/Code to Reproduce

algo = KNNWithMeans(k=50, sim_options={'name': 'pearson_baseline', 'user_based': False})
algo.fit(trainset)
test_pred = algo.test(testset)

#### Expected Results
few lines in the reason message in Prediction 
Prediction(uid='A2MR696ZU17F12', iid='B003XRD9UA', r_ui=5.0, est=4.262492837848899, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
#### Actual Results
spelling mistake in 'unknown' - instead it is displaying 'unkown' 

Prediction(uid='A2MR696ZU17F12', iid='B003XRD9UA', r_ui=5.0, est=4.262492837848899, details={'was_impossible': True, 'reason': 'User and/or item is unkown.'}),
#### Versions

Darwin-18.2.0-x86_64-i386-64bit
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
surprise 1.1.0

**Comment by NicolasHug** [comment]
Indeed, thanks

fixed by https://github.com/NicolasHug/Surprise/commit/59e6886495bf9ec337b843a9a7394c83d0602449
