### ISSUE TITLE
reimplementations of other algorithms in Librec

### ISSUE THREAD

**Issue by DonaldTsang** [NicolasHug/Surprise#333]
#### Description
This is more of a question regarding the abundance on the number of algorithms in Librec when compared to Surprise, in a Python-only setting.
In the list of
- https://www.librec.net/doc/librec-v2.0/net/librec/recommender/Recommender.html
- https://www.librec.net/dokuwiki/doku.php?id=Recommender#algorithms
- https://www.librec.net/dokuwiki/doku.php?id=AlgorithmList

there are 60+ algorithms compared to about a dozen algorithms in:
- https://surprise.readthedocs.io/en/stable/basic_algorithms.html
- https://surprise.readthedocs.io/en/stable/knn_inspired.html
- https://surprise.readthedocs.io/en/stable/matrix_factorization.html

Is it possible to evaluate which algorithms could be added to Surprise to make the code base more diverse?

**Comment by NicolasHug** [comment]
Unfortunately I'm not planning on adding more features to surprise.

**Comment by DonaldTsang** [comment]
@NicolasHug could this be an open questions for potential volunteers to fill in on as part of long-term planning?

**Comment by NicolasHug** [comment]
unfortunately no, I can only consider bug-fixes at this point, but no more additional features
