### ISSUE TITLE
Question regarding surprise use for E-Commerce Domain for Cross Sell

### ISSUE THREAD

**Issue by skagrawal10** [NicolasHug/Surprise#334]
Hi, 

I have checked some articles and they have mentioned that, we can use this library for Cross Sell as well. So for this, if customer has bought product, we will assign rating as "1" otherwise, we will assign as rating as "0". 
Is this correct?

When I have run this on my data, then, I found out that with SVD, even real rating is 1 but, est is like .20 for most of the products. Is this expected behavior where as KNN is providing expected rating as 1 where real rating is 1. 

Why SVD is so off? Am I doing something wrong here? Or we can not use this package in my scenario. 

Any thoughts?

**Comment by NicolasHug** [comment]
Try using a library that handles implicit ratings. Surprise is focused on explicit ratings.
