### ISSUE TITLE
How can I retrieve the raw id of items from similarity matrix?

### ISSUE THREAD

**Issue by itsoum** [NicolasHug/Surprise#338]
First I run the code below in order to train a KNNBaseline across whole dataset.

```
#train KNN recommender 
algo = KNNBaseline(sim_options=sim_options_pear)
full_data = data.build_full_trainset()
train=algo.fit(full_data)
```

After that I retrieve the pearson similarity matrix using

`pearson_cor = train.sim`

And I take the expected items x items similarity matrix.

![image](https://user-images.githubusercontent.com/9675299/75824990-28980c00-5dad-11ea-8b62-b2c23cb91dc0.png)

The number on the cell is mapped somehow in the inner or the raw id?
For example, the value in the above cell 0,2 is 0.10646484013036764.  Is this value the similarity measurment between item with id=0 and item with id=2? Is this raw id?

**Comment by NicolasHug** [comment]
the indices used to index the `sim` matrix are inner ids. You can map from and to raw/inner ids using the trainset object. Take a look at the doc and the FAQ.

**Comment by itsoum** [comment]
Thank you for the lightning reply.
For validation, as it is depicted in the image below the the real (raw) pair of ids of the above example are 1,6?
![image](https://user-images.githubusercontent.com/9675299/75827011-64cd6b80-5db1-11ea-8448-b3aec657b734.png)

**Comment by NicolasHug** [comment]
If you have computed an item-based similarity matrix then yes

Otherwise you should be using to_raw_uid ;)

**Comment by itsoum** [comment]
Yes, it's an item-based similarity. Thank you again for the help.
A minor suggestion, maybe you should add in the documentation if something uses inner id as in our case with `sim `or `compute_similarities()` in order someone is able to identify it directly from documentation.
