### ISSUE TITLE
How to calculate confusion matrix, precise and recall

### ISSUE THREAD

**Issue by BillySurya** [NicolasHug/Surprise#34]
Hello,

This library is amazing. So i really interested with this lib. Now i tried to build rec. system with collaborative filtering. I use some of library in there to build a model. Then i need to calculate performance of algorithm that I used for. Is it possible to get confusion matrix to calculate precise and recall?

Thank you,

**Comment by NicolasHug** [comment]
Hi, and thanks!

Precision and recall do not evaluate rating predictions but rather the recommendations. For now, the algorithms in Surprise predict rating values, not recommendations (or ranks). If you want to transform a rating into a recommendation, you'll have to set a threshold (e.g. recommend item if the rating is greater than 4).

Doing this, you will be to easily compute recall and precision for each user (or the global averages). You just need to use the `Prediction` list that is returned by the `test` method. Check out how RMSE is computed to get an idea, you'll quickly find out how to do it.

Nicolas

**Comment by BillySurya** [comment]
Thanks for your reply,

Oh okay i will try that. Thank you

Billy
