### ISSUE TITLE
Representing missing/sparse data in dataset

### ISSUE THREAD

**Issue by jmc-bbk** [NicolasHug/Surprise#340]
Hi Nicolas & Community,

I read your fantastic blog post http://nicolas-hug.com/blog/matrix_facto_3 on SVD and I'm now looking at using Surprise with my dataset.

Sorry that this is a basic question, but I'm a bit confused about representing sparse/missing data.

I load data as shown in the docs `data = Dataset.load_from_df(df[['userID', 'itemID', 'rating']], reader)`.

My question is - in the examples shown the dataset is often complete. For example:

userID, itemID, rating
1, 1, 5
1, 2, 3
2, 1, 4,
2, 2, 5

However, from your blog post, I understand that SVD with SGD works with matrices that contain missing ? values. For example, user 2 hasn't rated item 2.

userID, itemID, rating
1, 1, 5
1, 2, 3
2, 1, 4,
2, 2, ?

Therefore, when I load data - how do I represent record `2, 2, ?`. Is this record removed from the dataset? Or is it stored as `2, 2, np.nan`?

I was under the impression that if we had complete data, we could use standard SVD algorithm without SGD. However, I can see that SGD is implemented in Surprise.

Sorry for this low-level question. I couldn't find an answer elsewhere. Otherwise, I'm very much enjoying using Surprise.

Thanks!
James

**Comment by NicolasHug** [comment]
Hi James,

> Therefore, when I load data - how do I represent record 2, 2, ?

You don't, you should only specify known ratings

> I was under the impression that if we had complete data, we could use standard SVD algorithm without SGD.

Yes, if you don't have missing entries, use a dense SVD solver like the scipy one instead

> However, I can see that SGD is implemented in Surprise.

Yes, SGD is the optimization procedure used when approximating the SVD of the matrix, when there are missing values

**Comment by jmc-bbk** [comment]
Amazing, thank you so much for your speedy answer Nicolas!
