### ISSUE TITLE
implement own prediction model (like a keras based model_

### ISSUE THREAD

**Issue by jpainam** [NicolasHug/Surprise#341]
In the example, we can use the `SVD` and call its fit method and pass the trainset. What if i have my tensorflow model and would like to use the output prediction to compute metrics such as the hitrate.

How can I use trainSet class with a keras based model?
Thank you

**Comment by NicolasHug** [comment]
I'm not sure what you mean, but you can define a custom prediction algorithm (please refer to the docs) and use keras under the hood if you wish.

If you're asking about direct interaction with TF/keras without some glue code, then no this won't work
