### ISSUE TITLE
Some context in Scikit-Surprise

### ISSUE THREAD

**Issue by Mad425** [NicolasHug/Surprise#342]
Hi, 

I plan to design a recommendation system, especially with Scikit-Surprise. 
A bit of background: I want to recommend products to shop. Here, the user is the shop and the items are products (water, chocolate, cheese,...).
So to create the scores and the rating matrix, I use a quota calculation that I normalize to get a score between 0 and 1, where 1 means that the store is the biggest 
seller of this product(in percentage) (all proportion kept).
First question : is it a good scoring ? is it a good idea to have a rating between 0 and 1 ?

Second question, I want my system to take into account the time of year. For example it recommends more chocolate at Christmas.
How can I do that ? I have an idea where I do "post-filtering", (at the end, when I already compute SVD or system like this). So in thgis idea, I try to modify the rating of 
a product according to the period of the year and according to the evolution of the sales of this product on the sales history. So if the product is very well sold, 
for example 35% more than the average at this time of year, I increase the score by 35%.
Do you think this is a good idea? Do you have any suggestions for doing this? Does Scikit-Surprise have any features to help me do this?

I alrerady some research to take into account the time and I saw some Context Aware Recommender System, do Scikit-Surprise have option do do that ?

Thaks for your reading and... stay at home!

**Comment by NicolasHug** [comment]
>  is it a good idea to have a rating between 0 and 1 ?

Should be OK. Try using the `SVD` algorithm.

For the rest: there's no support for timestamps in surprise (at some point I thought I would, but ended up not doing it). Also no, there's no option for context aware nor content-based recommendation
