### ISSUE TITLE
Time- and/or User-based Cross-Validation

### ISSUE THREAD

**Issue by rnowling** [NicolasHug/Surprise#343]
#### Description
First off,  I want to thank you for your work on surprise.  This is a very cool library with a lot of potential.  Thank you for your time and effort!

I was looking over the provided tools for cross-validation.  They do not seem to be aware of the time of the ratings or how ratings are associated with users.  In my real-world contexts, you are going to deploy a recommendation system that uses past data to predict future events.  E.g., generate predictions for users based on all data available to the system prior to today.  Further, you may want to train and evaluate on different subsets of users.  I think that expanding the available options for cross-validation would help users perform more realistic experiments.

That said, I understand that Rome wasn't built in a day!  I think you've done an awesome job of establishing a strong foundation for the code base, documentation, etc.  I look forward to seeing how this library evolves and even using it in my classes as it matures.

(I worked on recommendation systems for online advertising in industry and am now a  professor at a small college.)

**Comment by NicolasHug** [comment]
Hi @rnowling , time-aware models or CV aren't implemented (and won't be). At some  point I considered it but this is out of the picture now.

I think you can still define your own time-aware CV object though. You can check out the code to see how it could be done.
