### ISSUE TITLE
Build_anti_test_set=500

### ISSUE THREAD

**Issue by aparna700** [NicolasHug/Surprise#344]
Hi Nicolas,

I see the below definition for build_anti_test function in your documentation.

"Return a list of ratings that can be used as a testset in the test() method.The ratings are all the ratings that are not in the trainset, i.e. all the ratings rui where the user u is known, the item i is known, but the rating rui is not in the trainset. As rui is unknown, it is either replaced by the fill value or assumed to be equal to the mean of all ratings global_mean."

I am not sure if i understand this function correctly. Can you pl clarify?

Say, the trainset has 100 unique customerids & 10 unique productids. Then there should be 1000 ideal no of ratings. But in real life scenario, a customer doesn't usually buy/rate all 10 products. So lets imagine that there are 500 ratings in trainset. Then, I assume that build_anti_test_set is actually 1000 (ideal no of ratings)-500 (actual no of ratings in trainset) =500 user*item combos which has no ratings. Is this right?

**Comment by NicolasHug** [comment]
that's correct!

**Comment by aparna700** [comment]
woah! thats a very quick reply. thanks mate:)
