### ISSUE TITLE
help with predictions

### ISSUE THREAD

**Issue by Jinb2** [NicolasHug/Surprise#345]
#### Description

The predict() method keeps telling me :
"details={'was_impossible': True, 'reason': 'User and/or item is unkown.'})"

That is my dataframe, it has the comments so I am not sure why I
![image](https://user-images.githubusercontent.com/36316652/77836801-cc1bd880-712f-11ea-9c2f-1c9b3915d94e.png)

#### Steps/Code to Reproduce

I followed the documentation, so I do not know why it says user/item/ is unknown
https://colab.research.google.com/drive/1aZwvHWGti_r1T6iOWmFiCUW_8f6TR54H

#### Versions
Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
surprise 1.1.0

**Comment by NicolasHug** [comment]
I can't access your drive. Please copy/paste here a *minimal* reproducible example.

It's likely that the userid column is treated as strings instead of ints.

**Comment by Jinb2** [comment]
Hi sorry for that, I updated the permission settings so it should work now. 

I use cross-validation on my data:
![image](https://user-images.githubusercontent.com/36316652/77851923-ccf15080-71a9-11ea-914f-90f051105ecf.png)


These are the predictions that it returns:
![image](https://user-images.githubusercontent.com/36316652/77852070-9d8f1380-71aa-11ea-9931-0ae29efc379d.png)

Could it be the name column?

**Comment by NicolasHug** [comment]
Are they all marked as impossible? What are the dataset dimensions (number of ratings, number of users, number of items)? What's the avg number of ratings for each users?

If each user has very few ratings then it can be expected that the users in the trainset are not present in the testset.

**Comment by Jinb2** [comment]
Yes they were all marked as impossible. The dimension is (15647, 4).  So I think the problem might be that each user has very few ratings (in my dataset its one user rating for every item).

**Comment by NicolasHug** [comment]
are you sure about (15647, 4)?

What is 4? Is see more than 4 users and more than 4 items in your screenshot.

**Comment by Jinb2** [comment]
My bad. To clarify, there is 15647 users and items.  There is 15647 rating one rating for each item from each user.

**Comment by Jinb2** [comment]
Should I switch to a different dataset then?

**Comment by NicolasHug** [comment]
I'm sorry, I don't understand this:

> there is 15647 users and items. There is 15647 rating one rating for each item from each user

How many users, how many items, and how many ratings are there?

**Comment by Jinb2** [comment]
There are 15647 users, 15647 items, and  15647 ratings

**Comment by NicolasHug** [comment]
OK. Then yeah, I'm afraid there is not much you can do with collaborative filtering with this dataset unfortunately

**Comment by Jinb2** [comment]
OK. So I need to find a dataset with more than one rating per item?

**Comment by NicolasHug** [comment]
yes and also with more than one rating per users
