### ISSUE TITLE
Zeros in prediction data 

### ISSUE THREAD

**Issue by nadaa** [NicolasHug/Surprise#346]
Hi,
I applied SVD algorithm to movielens dataset,
after fitting the data and test. I saved the predictions into dataframe, why there are some zeros?

`
    reader = Reader(rating_scale=(1,5))
    ratings_df = pd.read_csv('./ratings.csv')
    ratings_df = ratings_df.iloc[:,:3]
    data = Dataset.load_from_df(ratings_df, reader)
    trainset = data.build_full_trainset()
    model = SVD()
    model.fit(trainset)
    testset = trainset.build_anti_testset()
    predictions = model.test(testset)

`

**Comment by NicolasHug** [comment]
zeros where?

**Comment by nadaa** [comment]
> zeros where?

In the predictions, i convert it into dataframe

**Comment by NicolasHug** [comment]
are the predicted values all zeros?

Sorry, I can't really help you with so few details. Please provide a minimal reproducible example with code, data, and results

**Comment by nadaa** [comment]
> are the predicted values all zeros?
> 
> Sorry, I can't really help you with so few details. Please provide a minimal reproducible example with code, data, and results

Not all, few, I guess that are the data from the training as I build a dataframe of all users and  items

**Comment by NicolasHug** [comment]
Sorry, again I would need a minimal reproducible example with code, data and results.

Closing until then.
