### ISSUE TITLE
Help with item based vs user based collaborative filtering 

### ISSUE THREAD

**Issue by Jayden995050** [NicolasHug/Surprise#348]
Im a student trying to compare user based and item based collaborative filtering in reccomending users different movies however i am struggling to find the neccessary code for both algorithms that will allow me to carry out this experiment any help you can give would be much appreciated.

**Comment by NicolasHug** [comment]
Please read the doc.

And please don't ask me to do your homework.

And please don't send me emails nor linkedin messages.
