### ISSUE TITLE
possible tiny typo in predict function documentation

### ISSUE THREAD

**Issue by bobbyinfj** [NicolasHug/Surprise#350]
#### Description

Possibly a tiny typo: 
The returns section of the predict function lists "The true rating r_ui (r^ui).
The estimated rating (r^ui). "
 
#### Steps/Code to Reproduce

Visiting https://surprise.readthedocs.io/en/stable/algobase.html

![image](https://user-images.githubusercontent.com/3271618/79289047-27163500-7e7d-11ea-964b-8f2ceaa841d8.png)

#### Expected Results
I think the true rating does not have a hat, right?
#### Versions

p.s. I am really enjoying learning this package. Thank you!

**Comment by NicolasHug** [comment]
Indeed the true rating should not have a hat. Thanks for noting! do you want to submit a PR?

**Comment by bobbyinfj** [comment]
Yes, I just submitted (my first ever). Thank you for the encouragement!
