### ISSUE TITLE
get_top_n() function not working on train_test_split data

### ISSUE THREAD

**Issue by rizkygusna** [NicolasHug/Surprise#353]
#### Description

So i decided to use your example [here](https://github.com/NicolasHug/Surprise/blob/master/examples/top_n_recommendations.py) on my code. but some user doesn't get as much as n recommendation.

#### Steps/Code to Reproduce

This is my code
```
data = Dataset.load_builtin('ml-100k')
trainset, testset = train_test_split(data, test_size=.20)
algo = NMF()
algo.fit(trainset)

predictions = algo.test(testset)

top_n = get_top_n(predictions, n=10)

for uid, user_ratings in top_n.items():
    print(uid, [iid for (iid, _) in user_ratings])

```
#### Expected Results

> 196 ['1293', '1500', '1642', '1599', '64', '963', '1158', '899', '318', '1467']
> 186 ['813', '57', '927', '853', '320', '913', '1192', '1427', '1591', '1512']
> 22 ['408', '169', '114', '530', '1368', '1449', '1536', '1643', '320', '480']

All users got the top n

#### Actual Results
>907 ['173', '813', '144', '172', '647', '185', '98', '317', '202', '79']
>371 ['175', '55', '186', '210', '746', '237', '97', '431']
>218 ['654', '12', '762', '789', '47', '42', '164', '209', '695']
>829 ['408', '190', '276', '124', '198', '116', '170', '151', '213', '639']
>733 ['1085', '515', '471', '922', '1', '14', '1129', '762', '13', '245']
>363 ['652', '174', '169', '1007', '1512', '79', '180', '187', '181', '100']
>193 ['100', '182', '127', '210', '487', '237', '96', '56', '82', '195']
>808 ['313', '262', '300', '312', '346', '327', '875', '872', '325']
>557 ['50', '198', '150', '271', '1244', '682']

Some user got less

#### Versions

> Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
> Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
> [GCC 8.3.0]
> surprise 1.1.0

**Comment by NicolasHug** [comment]
it's probably because some users have less than 10 predictions?

**Comment by rizkygusna** [comment]
> it's probably because some users have less than 10 predictions?

is that normal or all user supposed to get exactly n recommendation?

**Comment by NicolasHug** [comment]
yes. you can look at your training and testing data. The vast majority of ratings aren't known
