### ISSUE TITLE
Prediction with k=1 --> predicting person is picked as his nearest neighbor

### ISSUE THREAD

**Issue by Trungmaster5** [NicolasHug/Surprise#356]
Hi, 
Thank you for this great package. 

 I have tried the KNNWithMeans function of Surprise for a little while.
And I found that when k=1, the predicting person is chosen as his nearest neighbor. Let say I wanted to find nearest neighbor for “subj_A", the result I got was “subj_A" himself. 
(It is reasonable because indeed the correlation between subj_A and himself is always 1)

I think the prediction should exclude the person who is being predicted from similarity matrix 
(For example, make his correlation to be 0). 

What do you think ?

**Comment by NicolasHug** [comment]
I've had this disucussion in https://github.com/NicolasHug/Surprise/issues/134

The fact that 1nn(x) == x is expected and normal.
So it's also normal that x belongs to knn(x)

See also in scikit-learn:

```py
from sklearn.neighbors import KNeighborsClassifier

X = [[1], [2], [3]]
y = [1, 2, 3]

print(KNeighborsClassifier(n_neighbors=1).fit(X, y).predict(X))  # 1 2 3
print(KNeighborsClassifier(n_neighbors=3).fit(X, y).predict(X))  # 1 1 1
```

from the first line it's clear that 1nn(x) == x
and from the second it's clear that x is in 3nn(x), as we can see with the first sample.

**Comment by Trungmaster5** [comment]
Oh, sorry I missed that one. 

I see your points in #134 but I still don't think you should include x in knn(x) for the recommender system (in particularly). Because at the start of prediction, x is expected to be a newly added subject/user/item. 

Thank you for the clarification, I close this issue here.
