### ISSUE TITLE
how can I build contextaware recommender systems using Surprise?

### ISSUE THREAD

**Issue by ajoeajoe** [NicolasHug/Surprise#36]
how can I build contextaware recommender systems using Surprise?
can you give me some tips?

**Comment by NicolasHug** [comment]
I have absolutely no idea.

Surprise is a library for predicting ratings on the basis of a rating history. Contextual information is not taken into account. I guess you could, but you will have to change the data workflow a bit.

**Comment by ajoeajoe** [comment]
thx
