### ISSUE TITLE
Grid/RandomSearchCV stratified folds

### ISSUE THREAD

**Issue by Harpreet-Paul** [NicolasHug/Surprise#362]
#### Description
Hey Nicholas! Firstly, thank you for creating this library. It's been a massive help for me. My question is regarding the GridSearchCV and/or RandomizedSearchCV classes. Are the folds that are produced stratified? I know the docs say these classes are analogous to the Scikit-Learn ones, but the Scikit-Learn docs mention that stratified folds are only made when the algorithm/model instance passed into Grid/RandomizedSearchCV is a classifier.

**Comment by NicolasHug** [comment]
Hi,

No the folds aren't stratified
