### ISSUE TITLE
make predictions only for few items for all users

### ISSUE THREAD

**Issue by colobizm** [NicolasHug/Surprise#369]
I have been using the Surpriselib library (which by the way, is amazing) and have managed to develop a model based on the SVD algorithm. My dataframe has user/item/rating columns.

```
trainset = data.build_full_trainset()
algo = SVD()
algo.fit(trainset)
```

I have managed to apply this algorithm to all the combinations of users / items by this code:

```
testset = trainset.build_anti_testset()
predictions = algo.test(testset)
```

.... but this is very CPU and memory demanding.

My question is if I can make predictions for all users but for only some items ? and if this is how I should do it ?

thanks in advance!

**Comment by NicolasHug** [comment]
you can just call algo.predict() n some specific users and items. Please make sure to check the docs https://surprise.readthedocs.io/en/stable/getting_started.html#train-on-a-whole-trainset-and-the-predict-method
