### ISSUE TITLE
Train-test split / Select a % by user

### ISSUE THREAD

**Issue by pbarreirosalgado** [NicolasHug/Surprise#371]
#### Description
Hi Nicolas,

My goal is to randomly select 80% of the ratings by user and leave the remaining 20% for testing. What I understand from the documentation is that the train-test split method randomly selects a % of the data but it does not necessarily mean that it selects % if the ratings by user.

Is there an easy way to do that? Or maybe I can do it by using another method that I didn't find in the documentation?

Many thanks for your help!

Pablo

**Comment by NicolasHug** [comment]
> What I understand from the documentation is that the train-test split method randomly selects a % of the data but it does not necessarily mean that it selects % if the ratings by user.

Yes you're correct. Though I think we can still say that users have 80% of their ratings in the trainset, on expectation. I don't expect your strategy to yield significantly different results and it's not the standard as far as I know.

> Is there an easy way to do that? Or maybe I can do it by using another method that I didn't find in the documentation?

It's not implemented, but it should be reasonably easy to implement your own class. You can check out how e.g. KFold is currently implemented

**Comment by pbarreirosalgado** [comment]
Thanks Nicolas! Very nice library btw
