### ISSUE TITLE
Error using SVDpp with parameters

### ISSUE THREAD

**Issue by pbarreirosalgado** [NicolasHug/Surprise#374]
#### Description
 Hi Nicolas,

I love your library, it is so helpful.

When I fit the BaselineOnly algorithm I don't have any problem but when I use a similar syntax for the SVDpp it is throwing me an error.

_from surprise import accuracy
BaselineOnly with tuned parameters
blo = BaselineOnly({"n_epochs": 3, "reg_i": 4, "reg_u": 5})
blo.fit(data.build_full_trainset())

test_set = test_data.build_full_trainset()
predictions = blo.test(test_set.build_testset())
accuracy.rmse(predictions)__

_from surprise import accuracy

SVDpp with tuned parameters

svd = SVDpp({'n_factors': 15, 'n_epochs': 16, 'lr_all': 0.015, 'reg_all': 0.15})
svd.fit(data.build_full_trainset())

test_set = test_data.build_full_trainset()
predictions = svd.test(test_set.build_testset())
accuracy.rmse(predictions)_

error messages--> TypeError: 'dict' object cannot be interpreted as an integer

Many thanks!

Pablo

**Comment by NicolasHug** [comment]
It's because the first parameter of BaselineOnly is a dict, but SVDpp excepts a regular set of parameter. Use `svd = SVDpp(**{'n_factors': 15, 'n_epochs': 16, 'lr_all': 0.015, 'reg_all': 0.15})` or better, just pass parameters as normal: `SVDpp(n_factors=15, n_epochs=16, ...)`

**Comment by pbarreirosalgado** [comment]
Thanks Nicolas.

svd = SVDpp(n_factors=15, n_epochs=16, lr_all=0.015, reg_all=0.15)
svd.fit(data.build_full_trainset())

test_set = test_data.build_full_trainset()
predictions = svd.test(test_set.build_testset())
accuracy.rmse(predictions)

Now I am getting this error: 
AttributeError                            Traceback (most recent call last)
<ipython-input-149-7407cdd0f537> in <module>
      4 
      5 svd = SVDpp(n_factors=15, n_epochs=16, lr_all=0.015, reg_all=0.15)
----> 6 svd.fit(data.build_full_trainset())
      7 
      8 test_set = test_data.build_full_trainset()

AttributeError: 'list' object has no attribute 'build_full_trainset'

Do you know why?

Thanks again

Pablo
