### ISSUE TITLE
How to Save The Trained Model

### ISSUE THREAD

**Issue by toppylawz** [NicolasHug/Surprise#375]
I know how to save normal machine learning, deep learning model and use it for web application, however, I really don't know how to save surprise-based trained model and even proceed to use it for recommendation in web application. Please how can I do the saving of trained model in surprise library.

**Comment by NicolasHug** [comment]
There's the `dump` module (https://surprise.readthedocs.io/en/stable/dump.html) but I don't really recommend using it, it's just a basic wrapper around pickle. I'd just use pickle instead (it's a Python builtin)

**Comment by toppylawz** [comment]
Wow, thanks a lot NicolasHug
