### ISSUE TITLE
Cold-Start problem

### ISSUE THREAD

**Issue by ljnozz** [NicolasHug/Surprise#38]
Hi Nicolas.

I'm thinking to use the Surprise Library for my thesis, but, I need to attack the cold-start problem because it's one of the main topic's of my thesis. For that, I'm working on taxonomic user profiling. Can the Surprise library be modified to support these approch? 
How do you address the cold-start problem with the Surprise library?

Many thanks.

**Comment by NicolasHug** [comment]
Hi,

Yes you could modify surprise to handle content-based features (is that what you call taxonomic user profile?), but that would require a bit of work.

If I'm not mistaken, LightFM can handle cold start using content-based features, so maybe it would be more useful for you?

Nicolas

**Comment by ljnozz** [comment]
I'm going to use an approach to solve the cold start problem using taxonomys and implicit feedback, but I'm going to use the Suprise Library too for those users who have many explicit raitings and a quantity of 30 or 40 neighbors.

Thanks Nicolas.
