### ISSUE TITLE
A quick inquiring about the link for papers. 

### ISSUE THREAD

**Issue by cuilongyin** [NicolasHug/Surprise#380]
#### Description

HI dear Nicolas,
    I read the document often and as I was reading the document page recently I notice that all the links for papers are not working anymore. I remember some time ago, by clicking them I can directly find the source of certain equations and functions. I can still find the original papers by the abbreviations, just wondering if it is because of my browsers. 

   Also, there is an article you wrote several years ago. I remember reading it and the equations were shown clearly, but recently I think they are not working anymore, and the equations look like some latex source code. I just want to let you be aware of that (it is a very informative article).  http://nicolas-hug.com/blog/matrix_facto_3

#### Steps/Code to Reproduce

For example, if you go to this link: https://surprise.readthedocs.io/en/stable/matrix_factorization.html
If you want to click here "For details, see equation (5) from [Koren:2009]. See also [Ricci:2010], section 5.3.1."
I remember there should be a link, and it leads you to the source.

#### Expected Results

I hope it is an easy fix, if not ... well luckily I read them already.

**Comment by NicolasHug** [comment]
Hi @cuilongyin , thanks for the feedback. I've fixed the latex renderring, and also the docs refs in https://github.com/NicolasHug/Surprise/pull/423. The fixes should be up soonish. Thanks!
