### ISSUE TITLE
Is this only working with ml-100k? And if I want to use manipulated ml-100k dataset, how?

### ISSUE THREAD

**Issue by Rowing0914** [NicolasHug/Surprise#386]

**Comment by tomfbush** [comment]
You can read in custom datasets according to https://surprise.readthedocs.io/en/stable/getting_started.html#use-a-custom-dataset.

This requires the use of the `Reader` class: https://surprise.readthedocs.io/en/stable/reader.html#surprise.reader.Reader

The fields in no particular order are `user ; item ; rating ; [timestamp]` -- you can set the order, along with the separator used.

If by "manipulated" you mean "with additional features" you may be out of luck.

Does that help?

**Comment by tomfbush** [comment]
To confirm, from the homepage:

> "Please note that surprise does not support implicit ratings or content-based information"

**Comment by Rowing0914** [comment]
> You can read in custom datasets according to https://surprise.readthedocs.io/en/stable/getting_started.html#use-a-custom-dataset.
> 
> This requires the use of the `Reader` class: https://surprise.readthedocs.io/en/stable/reader.html#surprise.reader.Reader
> 
> The fields in no particular order are `user ; item ; rating ; [timestamp]` -- you can set the order, along with the separator used.
> 
> If by "manipulated" you mean "with additional features" you may be out of luck.
> 
> Does that help?

Thank you for your help!!
I will look into those materials that you shared!!
