### ISSUE TITLE
Implementing social recommendation algorithms

### ISSUE THREAD

**Issue by ha0x7c7** [NicolasHug/Surprise#39]
Hi
First of all thanks for this awesome tool, I wanted to know how should I use Surprise to implement recommender algorithms that require social data? Algorithms like SocialMF, TrustMF ,SoRec, SoReg and ...?

**Comment by murdonson** [comment]
reer to librec another java  implementation of recsys

**Comment by murdonson** [comment]
refer to

**Comment by ha0x7c7** [comment]
Thanks for your comment, I have one difficulty with librec library and I don't know when my model has converged ! or how many iterations should I use for my algorithm, I have opened another issue in there too but with no reply.
https://github.com/guoguibing/librec/issues/141

**Comment by NicolasHug** [comment]
Hi, and thanks!

I have only glanced over the related papers but as I understand it, you would only need to manage the handling of social data.

I think it depends on whether or not you want to also split the social data for cross validation. If you don't, then a quick and easy way would be to load the social data in the `train()` method of the algortihm, for example. If you do need to split the social data, then it's probably going to be a little bit more tricky.

Nicolas
