### ISSUE TITLE
Rapids.ai 

### ISSUE THREAD

**Issue by pavo-tusker** [NicolasHug/Surprise#394]
Hi Surprise Team,

We are using surprise for recommendations and rapids.ai based libraries to leverage GPU.

Is it possible to support Nvidia GPU / Rapids framework ?

**Comment by NicolasHug** [comment]
Hi,

No, surprise doesn't support GPU. I'd recommend checking out libraries implemented on top of pytorch or tensorflow, like https://www.tensorflow.org/recommenders
