### ISSUE TITLE
feature request clustering vs prediction

### ISSUE THREAD

**Issue by priamai** [NicolasHug/Surprise#396]
Hi there,
I have started to use this library which is super useful!
What would be the best way to provide a method to return the clusters for the users after the training phase?
Using the movieset analogy I want to see how the users are distributed across clusters after factorization problem, for example there will be x users that like action movies and y that like comedy of course the cluster labelling will have to be made in a supervised fashion.
I remember from a university course that there was a way to use the eigenvalues or vectors to assign a cluster id to each user, but I can't find the equation/explanation anymore.
Any pointers much appreciated!

**Comment by NicolasHug** [comment]
Once the MF algorithm is trained you will have a `pu` attribute https://github.com/NicolasHug/Surprise/blob/master/surprise/prediction_algorithms/matrix_factorization.pyx#L118 with shape (n_users, n_factors), and it basically corresponds to each user projected into the dense "factors" space.

You can basically run any cluster algorithm from (e.g.) scikit-learn on that thing

**Comment by priamai** [comment]
Great that is what I was looking for!
