### ISSUE TITLE
Simple example so difficult to understand

### ISSUE THREAD

**Issue by prsolucoes** [NicolasHug/Surprise#40]
Hi,

Im making a simple book recommendation. So im using your "custom_dataset" in my example:

```
import os

from surprise import Dataset
from surprise import KNNBasic
from surprise import Reader

reader = Reader(line_format='user item rating', sep=' ', skip_lines=3, rating_scale=(1, 5))

custom_dataset_path = (os.path.dirname(os.path.realpath(__file__)) + '/custom_dataset')
print("Using: " + custom_dataset_path)

data = Dataset.load_from_file(file_path=custom_dataset_path, reader=reader)
trainset = data.build_full_trainset()

sim_options = {
    'name': 'cosine',
    'user_based': True  # compute  similarities between items
}

algo = KNNBasic(sim_options=sim_options)
algo.train(trainset)

uid = "user0"

pred = algo.predict(uid=uid, iid="", r_ui=0, verbose=True)
print(pred)
```

Results of execution:

```
python process.py 

Using: /Users/paulo/Developer/workspaces/python/ubook-recommender/custom_dataset
Computing the cosine similarity matrix...
Done computing similarity matrix.
user: user0      item:            r_ui = 0.00   est = 3.00   {u'reason': 'User and/or item is unkown.', u'was_impossible': True}
user: user0      item:            r_ui = 0.00   est = 3.00   {u'reason': 'User and/or item is unkown.', u'was_impossible': True}
```

Can you help me? 

I need understand how it works, i think it is simple, but it dont enter on my mind. It is not intuitive as this:

https://www.librec.net/dokuwiki/doku.php?id=introduction

I want understand your library to make it work at same level.

Can you help me?

**Comment by NicolasHug** [comment]
What do you not understand?

You've done everything right, except that you are asking for the prediction for user0 with no item, hence the result. You need to specify an item that exists in your dataset

**Comment by prsolucoes** [comment]
Hi,

I want get recommended itens for that user. I have all the user/items product views, and now i want get recommendations for that user.

Thanks.

**Comment by NicolasHug** [comment]
Ok, so you will need to call the `predict()` method on all the items for which  you want a prediction. Then you can sort these predictions by decreasing order of estimated rating, and take the first ones.

If you want to do that for all the users, it is explained in the first entry of the [FAQ](http://surprise.readthedocs.io/en/stable/FAQ.html#how-to-get-the-top-n-recommendations-for-each-user)

**Comment by NicolasHug** [comment]
Did it help?

**Comment by prsolucoes** [comment]
Im trying, but not understanding how it works.

**Comment by NicolasHug** [comment]
What do you not understand?

The steps are simple:
- read the data
- define an algorithm
- train the algortihm on the data
- predit some ratings.

That's it.

Have you read the User Guide?

**Comment by prsolucoes** [comment]
Using the following code it generated:

> user: user4      item: item1      r_ui = 0.00   est = 5.00   {u'actual_k': 1, u'was_impossible': False}

And with other items:

> user: user4      item: item1      r_ui = 0.00   est = 1.00   {u'actual_k': 1, u'was_impossible': False}

What means estimative 1 or 5, what is best? 

```
import os

from surprise import Dataset
from surprise import KNNBasic
from surprise import Reader

reader = Reader(line_format='user item rating', sep=' ', skip_lines=3, rating_scale=(1, 5))

custom_dataset_path = (os.path.dirname(os.path.realpath(__file__)) + '/custom_dataset')
print("> Using: " + custom_dataset_path)
print("> Loading data...")
data = Dataset.load_from_file(file_path=custom_dataset_path, reader=reader)
print("> OK")

print("> Building full trainset...")
trainset = data.build_full_trainset()
print("> OK")

sim_options = {
    'name': 'cosine',
    'user_based': True  # compute  similarities between items
}

print("> Training...")
algo = KNNBasic(sim_options=sim_options)
algo.train(trainset)
print("> OK")


print("> Predicting...")
uid = "user4"
iid = "item1"
pred = algo.predict(uid=uid, iid=iid, r_ui=0, verbose=True)
print("> OK")

print(pred)
```

**Comment by prsolucoes** [comment]
Dataset:

```
There are three lines to be ignored
Line format is user - item - rating

user1 item1 4
user1 item2 4
user1 item3 1
user1 item4 1
user2 item1 5
user2 item2 1
user2 item5 1
user3 item4 1
user3 item5 1
user4 item5 1
```

**Comment by NicolasHug** [comment]
> What means estimative 1 or 5, what is best?

1 means a rating of 1, 5 means a rating of 5. It's up to you whether you associate 1 with *good* and 5 with *bad* or the reverse (usually, 5 is the best rating).

If your question was more *how do I know these predictions are correct?*, then there is no way to know: you are predicting ratings that are not part of your initial dataset. If you want to know how accurate your algorithm is, you can do cross-validation and compute the RMSE or MAE. It's all clearly explained in the docs.

If your goal is still to get recommended items for a given user, I already gave you a link above that explains how to do it.

Hope that helps.

Nicolas

**Comment by prsolucoes** [comment]
Hi,

Sorry for late response, lot of things happen in the same time here:

```python
from collections import defaultdict

from surprise import SVD
from surprise import Dataset
from surprise import Reader

import os

def get_top_n(predictions, n=10):
    '''Return the top-N recommendation for each user from a set of predictions.

    Args:
        predictions(list of Prediction objects): The list of predictions, as
            returned by the test method of an algorithm.
        n(int): The number of recommendation to output for each user. Default
            is 10.

    Returns:
    A dict where keys are user (raw) ids and values are lists of tuples:
        [(raw item id, rating estimation), ...] of size n.
    '''

    # First map the predictions to each user.
    top_n = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))

    # Then sort the predictions for each user and retrieve the k highest ones.
    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings[:n]

    return top_n


# First train an SVD algorithm on the custom dataset.
# Pode botar tb: timestamp
reader = Reader(line_format='user item rating', sep=' ', skip_lines=3, rating_scale=(1, 5))

custom_dataset_path = (os.path.dirname(os.path.realpath(__file__)) + '/custom_dataset')
print("> Using: " + custom_dataset_path)
print("> Loading data...")
data = Dataset.load_from_file(file_path=custom_dataset_path, reader=reader)
print("> OK")

print("> Creating trainset...")
trainset = data.build_full_trainset()
print("> OK")

print("> Training...")
algo = SVD()
algo.train(trainset)
print("> OK")

# Than predict ratings for all pairs (u, i) that are NOT in the training set.
print("> Predicting...")
testset = trainset.build_anti_testset()
predictions = algo.test(testset)

top_n = get_top_n(predictions, n=10)
print("> OK")

# Print the recommended items for each user
print("> Results:")
for uid, user_ratings in top_n.items():
    print(uid, [iid for (iid, _) in user_ratings])
```

Now i get the correct results form my custom dataset, that is in file.

But how i can create the dataset direct from memory coming from database? I have +1mm of rows to train, how i can do it instead of read from file?

Example of my table:

> TempDataset: user, item, rating, timestamp

Example for code:

```python
rows = cursor.fetchall()
for row in rows:
    user = row["user"]
    item = row["item"]
    rating = row["rating"]
    timestamp = row["timestamp"]
    # train part ???
```

Thanks for any help.

**Comment by NicolasHug** [comment]
Hi,

Check the [latest docs](http://surprise.readthedocs.io/en/latest/getting_started.html#load-an-entire-dataset-from-a-file-or-a-dataframe), where I explain how to load data from a pandas dataframe. You'll need the latest version (not released yet, so clone the repo).

If you don't want to clone the repo or use a pandas dataframe, check [this issue](https://github.com/NicolasHug/Surprise/issues/20) to get some inspiration.

Nicolas

**Comment by prsolucoes** [comment]
Hi,

I see it:

```python
ratings_dict = {
    'itemID': [1, 2, 3],
    'userID': [9, 32, 2, 45, 100, 200],
    'rating': [3, 2, 4, 3, 1, 1]
}

df = pd.DataFrame(ratings_dict)
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(df[['userID', 'itemID', 'rating']], reader)
data.split(2)
```

Some questions:

1 - How can i use it from "master" in python?
2 - Why i need the reader?
3 - Why i need data.split?

Thanks.

**Comment by NicolasHug** [comment]
1 - Please look at the millions of tutorials on the web
2 - You need the reader to specify the rating scale.
3 - You don't need to split the data if you don't want to. I just did it to show that now `data` is a regular Dataset object, just as if it had been loaded from a file.

**Comment by prsolucoes** [comment]
Hi and thanks.

More questions:

```python
testset = trainset.build_anti_testset()
predictions = algo.test(testset)
top_n = get_top_n(predictions, n=10)
```

1 - Why i need call specifically "build_anti_testset" and not "build_testset", what i do?
2 - I always need call "algo.test"? What it do?

Thanks.

**Comment by NicolasHug** [comment]
Seriously man you need to read the docs. I can't do that for you.

**Comment by thaibv** [comment]
> What do you not understand?
> 
> The steps are simple:
> 
> * read your data
> * define an algorithm
> * train the algorithm on the data
> * predict some ratings.
> 
> That's it.
> 
> Have you read the User Guide?



> What do you not understand?
> 
> The steps are simple:
> 
> * read your data
> * define an algorithm
> * train the algorithm on the data
> * predict some ratings.
> 
> That's it.
> 
> Have you read the User Guide?

How to predict ratings for a set of user items? (Not one user or one item, but many)

**Comment by NicolasHug** [comment]
Using `predict` in a for loop, pretty much.
Or the `test` method.

**Comment by wee-analyze** [comment]
Can't you do a matrix multiplication of the 2 latent matrices to return 1 matrix with all user item predictions instead of doing predict in a loop?

I think you can access the latent matrices after fittting with .pu and .qu. I think.
