### ISSUE TITLE
Slopeone keeps saying {'was_impossible': True, 'reason': 'User and/or item is unkown.'}

### ISSUE THREAD

**Issue by linjunshi** [NicolasHug/Surprise#42]
When I am trying to look at the training dataset, I have this

    for trainset, testset in data.folds():
        # train and test algorithm.
        slopeone.train(trainset)
        for uid, mid, rate in trainset.all_ratings():
            uid, mid = str(uid), str(mid)
            slopepred = slopeone.predict(uid, mid, r_ui=4, verbose=True).est

and this keeps telling me that the user and item cannot be found.

**Comment by NicolasHug** [comment]
`uid` and `mid` are inner ids, you'll need to convert them to raw ids (see [this note](http://surprise.readthedocs.io/en/stable/getting_started.html#raw-inner-note)). I'll add a reference to it in the doc of `all_ratings` to avoid confusion.

**Comment by linjunshi** [comment]
Hi I've tried to construct training data and testing dataset, and I want to build from the whole dataset, and I did this

    slopeone = SlopeOne()
    for i in range(20):
       raw_ratings = data.raw_ratings
       random.shuffle(raw_ratings)
       trainset = data.build_full_trainset()
       testset = trainset.build_testset()
       slopeone.train(trainset)
       slopepred = slopeone.test(testset)
       accuracy.rmse(slopepred)
   
But the accuracy function shows me the same RMSE all the time regardless of the data has been shuffled.

**Comment by NicolasHug** [comment]
Hi,

Well you are training (and testing) on the same ratings at each iteration, so it's normal that you get the same RMSE. Shuffling the data does not have any impact on this scenerio: you are feeding the algorithm with the same data, the order is just changed each time.

Maybe you wanted to do cross-validation? In this case check out the basic examples in the User Guide.

Nicolas

**Comment by linjunshi** [comment]
I see, thank you so much, Nicolas.
