### ISSUE TITLE
real time recommendations

### ISSUE THREAD

**Issue by balajibalasubramanian** [NicolasHug/Surprise#43]
I wan't to make a movie recommendation website with real time predictions. I am thinking of combining scikit-surprise with django and socket.io/websockets/gevent for real time predictions. Are these the right tools to use or do you recommend something else ?

**Comment by NicolasHug** [comment]
Hi,

I can't honestly answer this kind of question as it entirely depends on your data workflow. Also, I have zero experience in the dev of web applications. Surprise is a  library for rating prediction algorithms, so if you need to predict ratings it may be helpful to you. 

You can take a look at [Mangaki](https://github.com/mangaki/mangaki) (in french) for an example of complete recommendation system.

Nicolas

**Comment by balajibalasubramanian** [comment]
Ok thanks, I will look into it.
