### ISSUE TITLE
Cannot import Dataset from Surprise (unknown location)

### ISSUE THREAD

**Issue by ayanatherate** [NicolasHug/Surprise#435]
#### Description

Hey,
I cloned this repo into my local system after repeated attempts using pip (also on anaconda prompt) failed. 
'import surprise' works but when I'm trying to import 'Dataset', it throws the same error as in the title. 

Any help would be appreciated. Thanks!

#### Steps/Code to Reproduce

```
import surprise
from surprise import Dataset, SVD
```

#### Expected Results
Hassle-free progress to the next part of my project.

#### Actual Results
```
ImportError: cannot import name 'Dataset' from 'surprise' (unknown location)
```

**Comment by NicolasHug** [comment]
Hi @ayanatherate , did you try the instructions to build from source? https://github.com/NicolasHug/Surprise/blob/master/CONTRIBUTING.md#set-up https://github.com/NicolasHug/Surprise#installation
