### ISSUE TITLE
MemoryError File "surprise/similarities.pyx", line 143, in surprise.similarities.msd (surprise/similarities.c:3524)

### ISSUE THREAD

**Issue by kyowill** [NicolasHug/Surprise#44]
how to solve this?

**Comment by NicolasHug** [comment]
Hi,

You are out of memory. Use a smaller dataset, or get more RAM.

Nicolas

**Comment by kyowill** [comment]
Thanks,  
There some java libraries like Lenkit which doesn't have this problem

**Comment by NicolasHug** [comment]
LensKit is a great library, no doubt.
