### ISSUE TITLE
No timestamp data in trainset

### ISSUE THREAD

**Issue by tseesurenb** [NicolasHug/Surprise#469]
Hi all,

I recently discovered that the trainset class design has omitted the "timestamp" feature, which I believe is a significant oversight. This limitation restricts the utilization of this excellent framework for those interested in implementing temporal effects. Do you have any suggestions on how to redesign the Training class to include the timestamp?

Best regards,
Tse

**Comment by NicolasHug** [comment]
Try https://github.com/NicolasHug/Surprise/issues/52#issuecomment-308640663

I added the timestamps originally thinking I'd implement predictors that use them, but ended up not doing so. So it's more of an unsupported feature at this point (and a wonky design but :shrug: ).
