### ISSUE TITLE
Can I apply number of listening instead of star rating?

### ISSUE THREAD

**Issue by jankogaga** [NicolasHug/Surprise#47]
I am doing a recommendation for a pair user/artist.
In the dataset, there is a number of user's listening of the artist instead of rating 1-5.
Can I apply the Surprise library on this task?

Thanks

**Comment by NicolasHug** [comment]
Hi,

For now the algorithms in Surprise rely on ratings, not on a number of view/listening. I guess you could convert those to rating using some heuristic but that may not be what you want.

If you want to implement your own algorithm that deals with this can of data you could do so fairly easily, but you would need to change the data workflow a little bit.

Nicolas
