### ISSUE TITLE
Matrix factorization algorithms - Utility of estimate function

### ISSUE THREAD

**Issue by namp** [NicolasHug/Surprise#48]
I'm not sure I understand why the function **estimate** is defined for each factorization algorithm.

Take for example SVD from [matrix_factorization.pyx](https://github.com/NicolasHug/Surprise/blob/master/surprise/prediction_algorithms/matrix_factorization.pyx):

At lines [210](https://github.com/NicolasHug/Surprise/blob/master/surprise/prediction_algorithms/matrix_factorization.pyx#L210) to [214](https://github.com/NicolasHug/Surprise/blob/master/surprise/prediction_algorithms/matrix_factorization.pyx#L214) the *prediction* is explicitly calculated as:

`
(global_mean + bu[u] + bi[i] + dot)
`

This is exactly what the function **estimate** does. The same calculation for each user/item pair can be calculated from a call to this function that is defined at line [233](https://github.com/NicolasHug/Surprise/blob/master/surprise/prediction_algorithms/matrix_factorization.pyx#L233)

This renders the **estimate** function completely *useless* unless: 

-  lines 210 to 214 are substituted by a simple call to **estimate** or 
- maybe the function **estimate** is used somewhere else in the framework (e.g. for evaluation purposes  (I haven't thoroughly checked if this is true), e.g. when calling:

```
#We'll use the famous SVD algorithm.
algo = SVD()
# Evaluate performances of our algorithm on the dataset.
perf = evaluate(algo, data, measures=['RMSE', 'MAE'])
```

**Comment by NicolasHug** [comment]
Hi,
> At lines 210 to 214 the prediction is explicitly calculated as:
   global_mean + bu[u] + bi[i] + dot)
   This is exactly what the function estimate does.

You are absolutely right!

> maybe the function estimate is used somewhere else in the framework

That is indeed the case. To make a prediction, you need to call the `predict()` method which will itself call the `estimate` method. Eeach algorithm **must** have an estimate method.

The reason the estimate() method is not called at line 210 is simply to avoid the function call overhead (plus the attributes `self.bu`, `self.pu` etc. are not yet defined).

Nicolas

**Comment by namp** [comment]
Thank you very much indeed for these clarifications.
