### ISSUE TITLE
gcc failed when I run basic_usage.py

### ISSUE THREAD

**Issue by murdonson** [NicolasHug/Surprise#49]
File "D:\python\lib\distutils\command\build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "D:\python\lib\distutils\ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "D:\python\lib\distutils\cygwinccompiler.py", line 166, in _compile
    raise CompileError, msg
ImportError: Building module surprise.similarities failed: ["CompileError: command 'gcc' failed: No such file or directory\n"]

**Comment by murdonson** [comment]
@NicolasHug  How to fix this? I sure get gcc.

**Comment by NicolasHug** [comment]
That's weird, gcc errors should only show up during the installation.

I stumbled upon [this](https://stackoverflow.com/questions/17972347/error-command-gcc-failed-no-such-file-or-directory), does it help?

Nicolas
