### ISSUE TITLE
Missing prediction algorithms when installing through pip

### ISSUE THREAD

**Issue by mahermalaeb** [NicolasHug/Surprise#5]
Hello,

I have installed this library using pip on my Ubuntu machine 2 days ago. However I am not able to import the `SlopeOne` and `CoClustering` algorithms. I have checked the files inside the library and noticed that the corresponding python files are actually missing.

![image](https://cloud.githubusercontent.com/assets/6735175/21296387/2f32b1c6-c573-11e6-8f8b-de961484de17.png)

I am not an expert in python or pip, but I thought I should highlight this issue. Please let me know if I am missing something.

Thanks for all the hardwork put in this library.

Cheers,
Maher

**Comment by NicolasHug** [comment]
Hi Maher,

Actually these algorithms are only available on the latest version which I haven't published to PyPI (the official python package index), so they're not yet available using `pip install surprise`.

To use them you'll need to clone the github repo:

    $ git clone git@github.com:NicolasHug/Surprise.git

and install the package:

    $ cd surprise
    $ python setup.py install

or if you want to use pip:

    $ cd surprise
    $ pip install .

By default the [documentation](http://surprise.readthedocs.io/en/latest/) is for the latest version but you can also see [the one for version 1.0.0](http://surprise.readthedocs.io/en/v1.0.0/index.html), which is the version on PyPI.

I'm sorry about all this, it's not clear at all from the README or the project main page that these two algorithms are only available for the latest version. I'll try make it clearer as soon as I can!

Thanks for the feedback! Cheers,
Nicolas

**Comment by NicolasHug** [comment]
Update: I changed the README and the main page to indicate that these algorithms are only available on latest version.
