### ISSUE TITLE
SVD variants - dump user/item features

### ISSUE THREAD

**Issue by namp** [NicolasHug/Surprise#50]
Is there an easy way to dump the user (pu) and item (qi) features after an SVD variant training, e.g. like 

`
from surprise import dump
`
`
algo_svd = SVD()    
`
...
`
dump.dump('./dump_SVD_features', get_features_somehow, algo_svd)
`

**Comment by NicolasHug** [comment]
Hi,
Dumping the algorithm should dump the factor vectors as well (as attributes).

Nicolas

**Comment by namp** [comment]
Indeed

Thank you
