### ISSUE TITLE
Create DataFrame from database with timestamp

### ISSUE THREAD

**Issue by prsolucoes** [NicolasHug/Surprise#52]
Hi,

Im using Dataset.load_from_df as you said, but i need put the timestamp column inside dictionary. But reading the source code it only have a comment about the 3 columsn (item, user, rating).

It has support for timestamp?

Thanks for any help

**Comment by NicolasHug** [comment]
Hi,

No I have removed the timestamp option from dataframe reading, as no algorithm uses the timestamps anyway.

If you really need timestamps you could replace [this part](https://github.com/NicolasHug/Surprise/blob/master/surprise/dataset.py#L327) by

```
            self.df = df
            self.raw_ratings = [(uid, iid, r, timestamp) for (uid, iid, r, timestamp) in
                                           self.df.itertuples(index=False)]
```

and feed the dataframe with timestamp at the last column.

Nicolas

**Comment by prsolucoes** [comment]
Ok, thanks.
