### ISSUE TITLE
Can we use it with Spark?

### ISSUE THREAD

**Issue by prsolucoes** [NicolasHug/Surprise#53]
Hi,

Can we use it with Spark?

If yes, do you have any example?

1 - I have a database of 76m rows(10.5mb), i can't predict in my machine (macbook with 8gb - ssd). Im processing on AWS with a machine with 64gb RAM. It is normal?
2 - It consumes a lot of memory? With spark it can be solved?

Thanks.

**Comment by NicolasHug** [comment]
Hi,

Sorry I have zero experience with Spark, so I won't be able to help you here.

Nicolas

**Comment by prsolucoes** [comment]
But and about other questions? Is normal? Have any experience / recommendation?

**Comment by NicolasHug** [comment]
I'm sorry man but

>  76m rows(10.5mb)

is really not an information I can help you with. How many users do you have? How many items? How many ratings do you train on, how many ratings do you want to predict? What algorithm are you using? This is the important information.

**Comment by NicolasHug** [comment]
Also I would really appreciate if you would just make a little bit of research on your own before asking questions here.

Most of all of the stuff you have asked me are things that you could have easily answered yourself if you had taken 5 minutes of your time to look for it.

I try to help users as best I can but I'm really not a living FAQ.

**Comment by prsolucoes** [comment]
Hi,

Im searching man, im searching, but the most articles is about scala, spark and bizarre languages examples.

76.000 rows, with last 10 items that users listen (+/- 7.600 users).

**Comment by NicolasHug** [comment]
So 76 000 ratings from 7600 users and 10 items?

Again, what algorithm are you using?

What is your issue? Are you running  into an OutOfMemoryError?

As long as you don't give me this information, I can't help you. Please be clear.

**Comment by prsolucoes** [comment]
Im using the same of docs for recommendation, top of 10 items for user.

On aws only works on a machine with 64gb.


<img width="491" alt="screenshot 2017-06-15 16 23 13" src="https://user-images.githubusercontent.com/395096/27201191-26370ee8-51f3-11e7-9fcc-577d794e9f88.png">

**Comment by prsolucoes** [comment]
Code:

```
print("> Training...")
algo = SVD()
algo.train(trainset)
print("> OK\n")

# realiza a predicao para todos os pares (u, i) que nao esta no training set
print("> Predicting...")
testset = trainset.build_anti_testset()
predictions = algo.test(testset, verbose=False)
top_n = get_top_n(predictions, n=10)
print("> OK\n")

# mede a precisao
print("> Accuracy...")
print(accuracy.rmse(predictions, verbose=False))
print("> OK\n")
```

**Comment by NicolasHug** [comment]
Still haven't answered any of my questions

**Comment by prsolucoes** [comment]
I don't have rating, so I use all with rating=1. So 76.000 rows with user, item and rating = 1. It need recommend by item similar.

My problem is the big memory consume.

**Comment by NicolasHug** [comment]
You're still not answering my questions. 

Anyway, it appears that you are using implicit ratings. Surprise can't handle implicit ratings for now, so you'll need to use something else. LightFM may be of help to you, so check that out.

I'll close the issue.
