### ISSUE TITLE
Accuracy behavior is strange

### ISSUE THREAD

**Issue by prsolucoes** [NicolasHug/Surprise#54]
Hi,

With my simple test, the accuracy behavior is very strange:

**DATASET [user, item, rating]:**

```
100	1	1
100	2	1
100	3	1
100	4	1
100	5	1
200	1	1
200	2	1
200	3	1
200	6	1
```

**PRECISION IN 10x EXECUTIONS:**

```
0.00771723811595
0.0278066509315
0.0170203594873
0.111386411745
0.103972524222
0.0
0.0134623913693
0.0974465112307
0.0574640800362
0.0122466495424
```

Why the precision change between 0 to 97% on every execution?

**Comment by NicolasHug** [comment]
I don't know.

Closing the issue. (For  reference, if anyone thinks I'm overreacting: #40 #51 #53)
