### ISSUE TITLE
raise ValueError('line_format parameter is incorrect.')

### ISSUE THREAD

**Issue by dilipbobby** [NicolasHug/Surprise#58]
When I try to change the inline parameter names I'm getting following error.Can't I change the inline parameter names ?

File "Reco.py", line 114, in <module>
    reader = Reader(line_format='user itemd ratinge', rating_scale=(0, 5))
  File "/usr/local/lib/python2.7/dist-packages/surprise/dataset.py", line 423, in __init__
    raise ValueError('line_format parameter is incorrect.')
ValueError: line_format parameter is incorrect.

**Comment by NicolasHug** [comment]
You cannot change these terms, only the order. May I ask why you wanted to change them?

Nicolas

**Comment by dilipbobby** [comment]
No important reason.just to avoid the confusion, I tried out giving own names in read-line and it thrown me the error.

**Comment by gauravc2708** [comment]
I have another problem related to it

when i read data such as 
`# Define the format
reader = Reader(line_format='a b d', sep='\t')
# Load the data from the file using the reader format
data = Dataset.load_from_file('cd.data', reader=reader)`

It shows error

ValueError: line_format parameter is incorrect.


Why ?

**Comment by gauravc2708** [comment]
` # check that all fields are correct
     71             if any(field not in entities for field in splitted_format):
---> 72                 raise ValueError('line_format parameter is incorrect.')
     73 
     74             self.indexes = [splitted_format.index(entity) for entity in

ValueError: line_format parameter is incorrect.
In [ ]:

​
`
