### ISSUE TITLE
In KNN example code which file is considered for training model?

### ISSUE THREAD

**Issue by dilipbobby** [NicolasHug/Surprise#62]
Hi,

I have small doubt.In the example of KNN you used ml-k100 as the training set but I'm bit confused with it.ml-k100 set has set of files like u.items, u.persons etc my doubt is from those bunch of files which file is considered as training set with KNN ? 

can i have format of that file which is given to KNN  for finding the neighbors ?
why I'm asking this because I want to read data from pandas df.

**Comment by NicolasHug** [comment]
Hi,

All the ratings are loaded from the file [u.data](https://github.com/NicolasHug/Surprise/blob/master/surprise/dataset.py#L63).

Nicolas

**Comment by dilipbobby** [comment]
yeah,Got it thank you :)
