### ISSUE TITLE
How can I predict for new data after training my algorithm on all dataset?

### ISSUE THREAD

**Issue by MaxBalashov** [NicolasHug/Surprise#64]
I mean data of new users about current items.

I used it:
```
# Retrieve the trainset.
trainset = user_data.build_full_trainset()

# Build an algorithm, and train it.
algo = sp.SVD()
algo.train(trainset)
```

And I what something like that:
`predict(new_data)`

Is there such opportunity?

**Comment by NicolasHug** [comment]
Check out [this](http://surprise.readthedocs.io/en/latest/getting_started.html#train-on-a-whole-trainset-and-specifically-query-for-predictions)
and [this] http://surprise.readthedocs.io/en/latest/dataset.html#surprise.dataset.Trainset.build_anti_testset)
