### ISSUE TITLE
Is there opportunity input Pandas.Dataframe into algorithms?

### ISSUE THREAD

**Issue by MaxBalashov** [NicolasHug/Surprise#65]
May be it will make data preprocessing more flexible.

May be I don't understand existing paradigm, I would be appreciate, if anybody explained it for me.

**Comment by NicolasHug** [comment]
Yes, please check out closed issue #20

**Comment by MaxBalashov** [comment]
Hello, Nicolas, could you help me to get all estimated ratings after SVD?I want to create SVD approximation of initial matrix.I need all known and unknown elements of User-Item matrix. 06.07.2017, 08:57, "Nicolas Hug" <notifications@github.com>:Closed #65.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by NicolasHug** [comment]
Hi,

You can use the [build_anti_testset](http://surprise.readthedocs.io/en/stable/dataset.html#surprise.dataset.Trainset.build_anti_testset) method and get all the predictions for this testset.

Nicolas
