### ISSUE TITLE
Can we use surprise for giving recommendations on multiple dimensions ?

### ISSUE THREAD

**Issue by dilipbobby** [NicolasHug/Surprise#69]
As per the examples surprise is giving out recommendations based on ratings which is single dimension.I have data like ratings on movies and review ratings for the movies.Can I make use of both the dimensions of ratings given to movies and review ratings of the movies for making recommendations ? Is it possible to do so ? If yes can I make use of surprise for that task ?

**Comment by NicolasHug** [comment]
Surprise can handle prediction algorithms based on triples `user - item - rating`.

Handling additional dimensions is possible, but not as is: you'll need to tweak the data pipeline machinery yourself.

Nicolas

**Comment by Roee16** [comment]
what does it means "   to tweak the data pipeline machinery yourself.  "?
how?
where?
for example:
if i have more features user_location user_language user_height - item_lang  item_old  item_price

**Comment by littlehome-eugene** [comment]
I am also interested in this.
