### ISSUE TITLE
Missing Precision@k and Recall@k evaluation metrics

### ISSUE THREAD

**Issue by mahermalaeb** [NicolasHug/Surprise#70]
Hello Nicolas,

I did a basic implementation of Precision@k and Recall@k evaluation metrics for surprise. Before going further, I wanted to check if you are open to accept a pull request for these 2 metrics if my implementation is inline with the repository contribution rules.

The implementation I did is based on the below 2 links:
[1] [here](https://grouplens.org/site-content/uploads/evaluating-TOIS-20041.pdf)  Precision and Recall and Related Measures in particular
[2] [here](http://sdsawtelle.github.io/blog/output/mean-average-precision-MAP-for-recommender-systems.html)

A high level summary of the metrics is as follows
```
    relevant documents: true value >= 4 (or other user definable threshold)
    retrieved documents: predicted value >=3.5 (or other user definable threshold)

    relevant@k: true value >=4 in the top k returned results (sorted by predictions descending)
    retrieved@k: predicted value >=3.5 in the top k results (sorted by predictions descending)

    precision at k: (relevant@k UNION retrieved@k)/retrieved@k
    recall at k: (relevant@k UNION retrieved@k) / relevant@k
```
I have also drafted a medium article that explains in detail the algorithm. You can check it [here ](https://medium.com/@m_n_malaeb/recall-and-precision-at-k-for-recommender-systems-detailed-explanation-with-examples-3f980b76857c) (still a draft, don't hesitate to report anything wrong)

Let me know what you think.

Regards,
Maher

**Comment by NicolasHug** [comment]
Hi Maher, 
Thanks for this!

I'd rather not merge precision and recall metrics in the source right now, because I think it could be merged with the metrics related to implicit ratings (see my comment on #46).

However I think that this would be a good idea to create a new entry in the FAQ explaining how to compute precision and recall with a code example, much like [this](http://surprise.readthedocs.io/en/stable/FAQ.html#how-to-get-the-top-n-recommendations-for-each-user). Would that work for you?

Nicolas

**Comment by mahermalaeb** [comment]
Yes this is a good idea while waiting for Surprise to support implicit rating. I will work (hopefully over the weekend) on adding a new section to the FAQ. *Note* however that I am doing precision@k and recall@k which is more complex than simple precision and recall calculation done at #46. So the code sample will be large but I'll try to optimize it as much as possible. Working code for now is pushed to my fork [here](https://github.com/mahermalaeb/Surprise/blob/new_metrics/surprise/accuracy.py).

**Comment by NicolasHug** [comment]
If I'm not mistaken the recall@k and precision@k could be some simple adaptation of the get_top_n() example of the FAQ?

**Comment by mahermalaeb** [comment]
You are totally right. I started from the top-N recommendation examples and created the pull request in #74

**Comment by noemi-mauro** [comment]
Hi guys,
I was looking at the computation of precision and recall

    # Precision@K: Proportion of recommended items that are relevant
    precisions[uid] = n_rel_and_rec_k / n_rec_k if n_rec_k != 0 else 1

    # Recall@K: Proportion of relevant items that are recommended
    recalls[uid] = n_rel_and_rec_k / n_rel if n_rel != 0 else 1

and I was wondering why we assign 1 if n_rec_k is 0 which means that there are not good recommendations. Isn't it wrong? This will increase the final mean over all the users.
