### ISSUE TITLE
toy_story_neighbors is generating sequence list of elements [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] with my data

### ISSUE THREAD

**Issue by dilipbobby** [NicolasHug/Surprise#72]
Hi,

I'm training the data using or from pandas data frame & trying out to implement KNN example.When i try to recommend knn toy_story_neighbors is giving out  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] for any number of inner_id's
my data in data-frame look as follow
index|  id                         | itemId                                                          |rating
 4  1220332944702810  1220332944702810_1278192568916847       0.4)
 can you say why i'm seeing this seq list in my toy_story_neighbors ?

**Comment by dilipbobby** [comment]
I interchanged the uid and iid and I'm see some output but for every new query,it is giving me same output.

**Comment by dilipbobby** [comment]
in my case `toy_story_neighbors = algo.get_neighbors(toy_story_inner_id, k=10)` give me the list as sequence number elements [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] even if by inner id is getting changed.but In knn example if the inner id is changed then list elements are getting changed.Can you tell why I'm seeing this type of output.

**Comment by NicolasHug** [comment]
I'm sorry but this is quite confusing.
Please submit a minimal code example and clearly state your problem so I can reproduce it and see what's wrong.
Nicolas

**Comment by dilipbobby** [comment]
Every thing I want to do from pandas data frame only so as 
Step 1: I loaded u.items and u.data in data frames
Step 2: I applied KNN algo on those data frames for getting nearest neighbors.

Here is the code I'm using 

```
import pandas as pd
import os
import io
from surprise import Reader
from surprise import dataset
from surprise import KNNBaseline
import numpy as np


#this function takes the dataframe as the input parameter
def read_item_names(df):
    """Read the u.item file from MovieLens 100-k dataset and return two
    mappings to convert raw ids into movie names and movie names into raw ids.
    """
    rid_to_name = {}
    name_to_rid = {}
#appending and converting datafram to a list 
    #line=df["ids"]+"|"+df["names"].tolist()
    #print(df.head())
    df['append'] = df.apply(lambda x: '|'.join(x.dropna().astype(str).values), axis=1)
    #print(df)
    strappend=df['append']
    print(strappend.head())
    for val in strappend:
	print(val)
        val = val.split('|')
        print("line[0]",val[0])
        print("line[1]",val[1])
	rid_to_name[val[0]] = val[1]
        name_to_rid[val[1]] = val[0]
    return rid_to_name, name_to_rid
    

"""converting the u.items file data as the dataframe for my use"""
#cols=['id','name']
Itemdf=pd.read_table("/home/xxxxx/.surprise_data/ml-100k/ml-100k/u.item", sep='|',header=None)
print(Itemdf.head())
print("print",type(Itemdf))
oldlist=Itemdf.columns
newlist=['ids','names',3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23]
Itemdf.rename(columns=dict(zip(oldlist, newlist)), inplace=True)
print(Itemdf.head())
idMessage=Itemdf[['ids', 'names']]
print(idMessage.head())

""""inorder to train data, I'm taking that also from the dataframe only taking u.data file and loading that into df"""
userdf=pd.read_table("/home/xxxxx/.surprise_data/ml-100k/ml-100k/u.data", sep='	',header=None)
print(userdf.head())
oldlistu=userdf.columns
newlistu=['userids','itemids','ratings','timestamp']
userdf.rename(columns=dict(zip(oldlistu, newlistu)), inplace=True)
print(userdf.head())


"""now training the data from df  """
# You'll need to create a dummy reader
reader = Reader(line_format='user item rating', rating_scale=(1,5))

# Also, a dummy Dataset class
class ReadDataset(dataset.DatasetAutoFolds):

    def __init__(self, df, reader):

        self.raw_ratings = [(uid,iid, r, None) for (uid,iid,r) in
                            zip(df['userids'],df['itemids'], df['ratings'])]
        self.reader=reader
	#print("read",df.head())

data = ReadDataset(userdf, reader)
print(data)
trainset = data.build_full_trainset()
sim_options = {'name': 'pearson_baseline', 'user_based': False}
algo = KNNBaseline(sim_options=sim_options)
algo = algo.train(trainset)
rid_to_name, name_to_rid = read_item_names(idMessage)
#print(rid_to_name,rid_to_name)

searchneg="Toy Story (1995)"
raw_id = name_to_rid[searchneg]
print("post id",raw_id)
toy_story_inner_id = algo.trainset.to_inner_iid(toy_story_raw_id)
# Retrieve inner ids of the nearest neighbors of Toy Story.
toy_story_neighbors = algo.get_neighbors(toy_story_inner_id, k=10)

# Convert inner ids of the neighbors into names.
toy_story_neighbors = (algo.trainset.to_raw_iid(inner_id)
                       for inner_id in toy_story_neighbors)
toy_story_neighbors = (rid_to_name[rid]
                       for rid in toy_story_neighbors)

print()
print('The 10 nearest neighbors of Toy Story are:')
for movie in toy_story_neighbors:
    print(movie) ```


**I don't why from today morning I'm getting error saying for above code.**
```Traceback (most recent call last):
  File "pdKNN.py", line 82, in <module>
    toy_story_inner_id = algo.trainset.to_inner_iid(toy_story_raw_id)
AttributeError: 'NoneType' object has no attribute 'trainset'```

**Normal git example  of knn also giving me the error like**
```Traceback (most recent call last):
  File "KNN.py", line 34, in <module>
    rid_to_name, name_to_rid = read_item_names()
  File "KNN.py", line 20, in read_item_names
    rid_to_name[line[0]] = line[1]
IndexError: list index out of range```

**Comment by NicolasHug** [comment]
The error message is very clear, you need to read it carefully:

`AttributeError: 'NoneType' object has no attribute 'trainset'`

This corresponds to this line

`algo = algo.train(trainset)`

The `train` method of the `algo` object does not return anything (or more precisely, it returns `None`).
You need to use 

` algo.train(trainset)`

Nicolas

**Comment by dilipbobby** [comment]
okay ! don't close the issue. I will check it from side once again

**Comment by NicolasHug** [comment]
I'm sorry mate but you can't expect me to read 100 lines of code. Also, your problems so far do not seem to be related to surprise.
I still don't clearly know what your issue is: you talk about Toy Story, then come back with another error, then talk about a list with Toy Story in your code while your data files are clearly not movie ratings.

Again, if you want me to help you, you will need to provide a minimal code example (very, very succinct) clearly stating your issue, where it happens in the code, etc. There are two reasons for this:
- I do all this on my free time and I'm really really not an after-sales service. 
- There's a 99% chance that you will solve your problem on your own simply by trying to clear things up, which you clearly haven't done yet.

Nicolas

**Comment by dilipbobby** [comment]
I'm using your KNN code with change of data only that why you see the movie name in the code.I'm so sorry that still you did not understand what my problem is.As you said I will not keep the entire code any more.

**Comment by dilipbobby** [comment]
I try to get nearest - neighbors using at following statements. In the place of movie name i'm using a message or post string.
```searchneg="Today I am delivering my first weekly address to the nation as President. God bless you and God bless America!"
# Retieve inner id of the (message or post) searchneg  in my case.
raw_id = name_to_rid[searchneg]
print("post id",raw_id)

inner_id = algo.trainset.to_inner_iid(raw_id)
print("inner id",inner_id)
print(type(inner_id))
# Retrieve inner ids of the nearest neighbors of searchneg.
neighbors = algo.get_neighbors(inner_id, k=10)
print ("list",neighbors) 
#Neighbors should return me the list elements but not as sequence like 0,1,2,3 .....
 but at this statement I'm getting sequence list like [0,1,2,3,4, 5,6,7,8,9] 

But your KNN example at same step ```toy_story_neighbors = algo.get_neighbors(toy_story_inner_id, k=10)
gives out a list which ```toy_story_neighbors which contain elements which are not in sequence.
when I checked ```toy_story_neighbors list with print,I can elements of numbers which are not in sequence 
```print(toy_story_neighbors) #output:[433, 101, 302, 309, 971, 95, 26, 561, 816, 347]

In my case, I'm getting list as [0,1,2,3,4, 5,6,7,8,9] ,if increase k=15 i'm seeing list with 0 to 14. I'm unable to figure it out why i'm seeing a sequence list.

**Comment by NicolasHug** [comment]
Isn't just simply because the item you are using only has one single rating in your dataset?

Try
`print(algo.trainset.ir[inner_id])`

If there's only one rating (of a few ratings) then it's perfectly normal that neighbors are always the first items. That's because all the similarities for this item are zero.

**Comment by dilipbobby** [comment]
are you talking about u.data file ratings ? if that is the case then I too have different ratings values for each post or message.
Here is my sample i/p train raw data look like:
u_id 			                           Item_ids 			                            rating
==================================================================
 210302285192            210302285192_10158271238825193                 5.999999999999999
 210302285192            210302285192_10158228294290193                 0.3999999999999999
 210302285192            210302285192_10158225457345193                 20.799999999999997
 210302285192            210302285192_10158190088890193                 5.899999999999999
 1220332944702810    1220332944702810_1278192568916847           0.3999999999999999
 210302285192             210302285192_10158161052450193                16.099999999999998

and when I tried out `print(algo.trainset.ir[inner_id]) #output ('ratingsss', [(1, 15.999999999999995)])`
but In your knn example I'm seeing bunch of tuple value with (id,ratings) elements inside the list.I'm getting only one single post rating in this case.So where do you think I'm going wrong ?

**Comment by NicolasHug** [comment]
So that's what I said: your item has only been rated by a single user (in this case the user's inner id is `1`, and the associated rating is 15.9).
As this item has only been rated once, it has no neighborhood. Hence, you always obtain the first k users when you try to retrieve the neighbors.
