### ISSUE TITLE
how to find similar users and recommend items?

### ISSUE THREAD

**Issue by juanremi** [NicolasHug/Surprise#73]
I try Surprise and I like this :+1: , but i dont understand fine how can i get:
- recommendItemsTo(userid)
- similarUsersTo(userid)
any suggestions for both?

for the first question i think i can do:
`foreach item in unseenItemsBy(user): predict(user, item, 0)`

but is a hard work to do if a have a lot of users/items

**Comment by NicolasHug** [comment]
Hi,
Both your questions are answered by the first 2 entries of the [FAQ](http://surprise.readthedocs.io/en/stable/FAQ.html).

Nicolas
