### ISSUE TITLE
In load dataframe example, AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by kyowill** [NicolasHug/Surprise#75]
https://github.com/NicolasHug/Surprise/blob/master/examples/load_from_dataframe.py

reader = Reader(rating_scale=(1, 5)) report error.

How to fix it?

**Comment by NicolasHug** [comment]
What version are you using?

**Comment by Guzpenha** [comment]
I had the same issue here , scikit-surprise==1.0.3

**Comment by NicolasHug** [comment]
Loading from a dataframe is only available from the latest version, i.e. you have to clone the repo. If you need/want to use version 1.0.3, you can still  refer to issue #20.
