### ISSUE TITLE
Could data only be loaded from a CSV file?

### ISSUE THREAD

**Issue by AEzzatA** [NicolasHug/Surprise#76]
It seems inconvenient that I have to make a CSV file first of my own data before loading them, is there another way to load the data around python dicts? or creating CSV in memory on the fly without saving it to desk first?

**Comment by NicolasHug** [comment]
Hi,
You can load the data from a Pandas dataframe: see issue #20.

Nicolas

**Comment by AEzzatA** [comment]
Thanks a lot! It would be helpful if it was mentioned in the docs one way or another, as users do not really dig into issues

**Comment by NicolasHug** [comment]
Yes you are right. It's actually mentioned in the docs but on the 'latest' version only, so it will become available by default when the next version is released

**Comment by AEzzatA** [comment]
Perfect, Good job!

**Comment by a6822342** [comment]
@AEzzatA Hello AEzzatA, Can you provide a demo of reading data from csv file ? I have tried this many times .At the end, I failed.Thanks.
