### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ankitjha97** [NicolasHug/Surprise#78]
I am getting this error.

`ImportError                               Traceback (most recent call last)
<ipython-input-1-ca7cc839673c> in <module>()
----> 1 import surprise

/home/ankit97/Surprise/Surprise/surprise/__init__.py in <module>()
      1 from pkg_resources import get_distribution
      2 
----> 3 from .prediction_algorithms import AlgoBase
      4 from .prediction_algorithms import NormalPredictor
      5 from .prediction_algorithms import BaselineOnly

/home/ankit97/Surprise/Surprise/surprise/prediction_algorithms/__init__.py in <module>()
     20 """
     21 
---> 22 from .algo_base import AlgoBase
     23 from .random_pred import NormalPredictor
     24 from .baseline_only import BaselineOnly

/home/ankit97/Surprise/Surprise/surprise/prediction_algorithms/algo_base.py in <module>()
      8                         unicode_literals)
      9 
---> 10 from .. import similarities as sims
     11 from .predictions import PredictionImpossible
     12 from .predictions import Prediction

ImportError: cannot import name similarities`

**Comment by ankitjha97** [comment]
I have cloned the repo and then ran the setup.py file.Then, I have ran this command in anaconda cell.
"import surprise" and it shows error.

**Comment by NicolasHug** [comment]
You're probably running conda from the surprise repository? You need to run the python shell from outside

**Comment by ankitjha97** [comment]
Yes, I am running it in conda.

**Comment by NicolasHug** [comment]
So is it working now?

**Comment by ankitjha97** [comment]
Yes from the command line, its working.
I want to know two things, please reply.
1) How to use surprise on jupyter notebook?
2) In the movielens example there are only four columns so in **Reader** we have specified _(line_format='user item rating timestamp', sep='\t')_ , but how will we make a surprise data instance of the data which have multiple rows?What should be parameters passed inside **Reader** so as to create a data instance for dividing it in folds?

I will delete this comment and close this issue if you want after you help me with these two problems.

**Comment by NicolasHug** [comment]
Jupyter notebooks are simply IPython shells so surprise will work just like any other package. Have you even tried it?
> how will we make a surprise data instance of the data which have multiple rows? 

You mean multiple columns? If so: you can only have 3 or 4 columns in your rating files.
> What should be parameters passed inside Reader so as to create a data instance for dividing it in folds?

The Reader object has nothing to do with creating folds (or not). Please follow the instruction on the documentation.

No need to delete the comment but please next time close the issue when it's fixed, and open a new one if needed.

**Comment by ankitjha97** [comment]
Thanks a lot.
