### ISSUE TITLE
Pushing a Django project on Heroku with Surprise (related to numpy)

### ISSUE THREAD

**Issue by pierre-vr** [NicolasHug/Surprise#79]
Hi !

I am trying to push my git repository to Heroku but I get a really strange error related to Surprise and Numpy.

My requirement.txt file looks like this : 
```
pytz==2013.7
requests==2.18.4
Django==1.10.5
dj_database_url==0.4.2
numpy>=1.11.2
pandas==0.20.3
progress==1.3
unicode_slugify==0.1.3
surprise>=0.1
```

$ git push heroku master

```
Counting objects: 276, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (269/269), done.
Writing objects: 100% (276/276), 8.53 MiB | 808.00 KiB/s, done.
Total 276 (delta 121), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote: -----> Installing python-3.6.2
remote: -----> Installing pip
remote: -----> Installing requirements with pip

[...]

remote:        Collecting numpy>=1.11.2 (from -r /tmp/build_(...)/requirements.txt (line 5))
remote:          Downloading numpy-1.13.1-cp36-cp36m-manylinux1_x86_64.whl (17.0MB)

[...]

remote:        Collecting scikit-surprise (from surprise>=0.1->-r /tmp/build_(...)/requirements.txt (line 9))
remote:          Downloading scikit-surprise-1.0.3.tar.gz (2.4MB)
remote:            Complete output from command python setup.py egg_info:
remote:            Please install numpy>=1.11.2 first.
remote:            
remote:            ----------------------------------------
remote:        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-(...)/scikit-surprise/
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
```

What I do not understand is that it asks me to install a version of numpy above or equal to 1.11.2. But a few lines above, numpy is intalled.
I tried with different version of numpy and I updated surprise but it didn't work.

Do you have any idea where that's coming from ? Had the same issue ? Or know a fix ?

P.S. This project is amazing by the way! Thank you for your work.

**Comment by pierre-vr** [comment]
It could be related to your setup.py file and its lines 10 to 14:
```
try:
    import numpy as np
except ImportError:
    exit('Please install numpy>=1.11.2 first.')
```
But I don't have the knowledge necessary to see a problem here

**Comment by NicolasHug** [comment]
Hi,
It seems that numpy is only installed at the end of the pip process, so when surprise is installed it can't find numpy.
Try installing surprise in a separate pip process and it should work fine.

Nicolas

**Comment by pierre-vr** [comment]
Indeed, it worked by installing without surprise the first time and then adding it.

**Comment by Harrish-Selvarajah** [comment]
@NicolasHug @pierre-vr 
Hi,
I'm having the error with flask deploying to Heroku, can you please explain to me your solution.

**Comment by morenoh149** [comment]
https://devcenter.heroku.com/articles/release-phase ?
