### ISSUE TITLE
Paper reference; Use pandas dataframe; time feature

### ISSUE THREAD

**Issue by samshipengs** [NicolasHug/Surprise#85]
Hi, 

I'm new here and not sure where to ask questions, please let me know if there is a better place for discussion.
For now here are my questions:

1) Is there any paper reference that this repo is based on? Some other similar project e.g (implicit) has provided paper reference, it helps me to understand how the code works better.

2) Is there anyway to just convert the pandas dataframe or numpy array to the Reader object? So far it seems like I can only load my own file from disk.

3) I don't quite understand  the optional column - timestamp in Reader: "user ; item ; rating ; [timestamp]", why would it be possibly needed? I just started getting to know collaborative filtering etc, but I don't see how timestamp is used here.

Thanks

**Comment by NicolasHug** [comment]
Hi,

1. No there is no paper reference for surprise. However,  references related to the implemented algorithms are mentionned in the doc, as well as all the necessary details to understand the algorithms' implementation.
2. Please check closed issues
3. A timestamp can be needed by some algorithms that are time-dependent (e.g. some extensions of the 'SVD' algorithm need a timestamp). Right now, none of the built-in algorithms use a timestamp so it's not really useful unless you want to implement a new algorithm.

Nicolas

**Comment by samshipengs** [comment]
@NicolasHug  Thanks for the quick reply. 
2. Found it, I haven't got chance to try it yet, but seems like 'load_from_df' is the way to go. Although, this leads to another question, to use this function I need to specify the 'rating_scale', I'm working on clicks data instead of for example 1~5 rating data, so do I just increase the range from 1 to maximum clicks or this would not make sense?
3. Since the 'timestamp' is not used, wouldn't it create issue when I'm passing a data with the timestamp? because there can be same user rated/clicked at different time, since timestamp is not used, the userID would just be duplicates.

**Comment by NicolasHug** [comment]
2. No, converting a number of clicks into a rating would not be efficient. Actually, the currently implemented algorithms only support explicit ratings, i.e. 1-5 ratings (or any other rating scale). You may be interested in [this paper](chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/http://yifanhu.net/PUB/cf.pdf) 
3. Yes this would be a problem: a user is supposed to rate an item only once.

**Comment by samshipengs** [comment]
@NicolasHug 
2. I see. Which paper?
3. Thanks for the confirmation.

**Comment by NicolasHug** [comment]
Oops sorry about that, I edited my comment. It's a direct adaptation of the 'SVD' algorithm (implemented in surprise) to handle data such as the number of clicks instead of ratings.

Nicolas

**Comment by samshipengs** [comment]
Thanks!
