### ISSUE TITLE
Very large Error values for binary ratings (0,1)

### ISSUE THREAD

**Issue by Skorkmaz88** [NicolasHug/Surprise#87]
#### Description

 I am getting extremely large (grows by dataset size), for predictions that have rating (0,1)

#### Steps/Code to Reproduce

reader = Reader(line_format='item user rating', rating_scale=(0, 1))

data = Dataset.load_from_file(file_path, reader=reader)
raw_ratings = data.raw_ratings
data.split(n_folds=5)

algo = SVD()

perf = evaluate(algo, data, measures=['RMSE', 'MAE'])

print_perf(perf)
#### Expected Results
Matrix dimensions  2798 users and 1764 items
any value of RMSE and MAE between 0 and zero 
#### Actual Results
------------
Mean RMSE: 1614.1631
Mean MAE : 1397.5424
------------

#### Versions

Linux-4.10.0-35-generic-x86_64-with-debian-stretch-sid
(u'Python', '2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]')
(u'surprise', '1.0.3')

**Comment by NicolasHug** [comment]
Hi,

SVD isn't really suited for 0-1 ratings. That being said you should not see such a high RMSE. I suspect your reading the user or item ids instead of the ratings, hence the error value.
Nicolas

**Comment by Skorkmaz88** [comment]
Hi, thanks for responding. SVD was just an example, I tried other methods to see if the problem was method related. I had the same issue again. But as you said, this shouldn't explain why this problem is happening. I will double check what you said and return with a response. But in any case, in our out of suprise context, do you know other good techniques as well, that has open source implementation for this task?

**Comment by Skorkmaz88** [comment]
One more thing that, there is an open pull request, which mentions adding mean for score for normalized ratings, can that be the issue ?

**Comment by NicolasHug** [comment]
Hi,
You'd probably be better served by other libraries implementing implicit feedback algorithms. You'll find plenty on with a simple google search.

**Comment by Skorkmaz88** [comment]
Thanks

**Comment by estebanbouza** [comment]
@NicolasHug from what I understand, SVD++ can be used when there is both implicit and explicit feedback: e.g. a user has rated [1-5] a few items AND saved for later [0-1] a few different ones.

Would SVD++ work in this case? Would Surprise be a good fit for it?

**Comment by NicolasHug** [comment]
> from what I understand, SVD++ can be used when there is both implicit and explicit feedback: e.g. a user has rated [1-5] a few items AND saved for later [0-1] a few different ones.

Yes that is correct. SVD++ will work for **integer** explicit ratings e.g. {1, 2, 3, 4, 5} and **integer** implicit ratings in {0, 1}, but would probably do poorly 
 with real ratings in [0, 1].

Surprise implementation for SVD++ is that of the papers that introduced it (see refs on the doc, or online). That is, the implicit ratings actually come from the explicit ones: we consider that there's an implicit rating of value 1 iff user u has rated item i, regardless of the explicit (integer) rating value (that is in [1, 5]).
Using two different sources for explicit and implicit ratings is possible, but it would require a bit a tweaking.

Nicolas

**Comment by NicolasHug** [comment]
Surprise does not support implicit ratings for now, there's no contradiction. From my previous comment:

>Surprise implementation for SVD++ is that of the papers that introduced it (see refs on the doc, or online). That is, the implicit ratings actually come from the explicit ones: we consider that there's an implicit rating of value 1 iff user u has rated item i, regardless of the explicit (integer) rating value (which is in [1, 5]).

SVD++ uses some kind of implicit rating, but it actually comes from the explicit ones.

**Comment by rishabh-vij** [comment]
Hi @Skorkmaz88  How did you handle this issue finally? Did you use some other library or found a workaround to use surprise for handling binary ratings?

**Comment by NicolasHug** [comment]
@rishabh-vij , please don't comment asking for the same thing on every single issue that deals with implicit ratings. I've already answered multiple times and added various pointers. Please follow them.
Thank you

**Comment by rishabh-vij** [comment]
@NicolasHug  Hi. I understand issues may not be the right place to get these answers but I just wanted some insights from people who have already faced this problem on how they dealt with it. I'm sorry for any inconveniences. The surprise library is a great tool. Cheers and thanks. 
Also please help me if you can with this problem, wherein I've binary ratings collected implicitly. I followed all your pointers to this issue but could not reach a concrete solution. I'll be greatful if you can help. Thanks for the help and for SURPRISE!

**Comment by NicolasHug** [comment]
You're looking for a library that can handle implicit feedback. Try e.g. LightFM, Spotlight, implicit, OpenRec... 
There's also https://github.com/Microsoft/Recommenders that is going to be advertised soon.

There is no magical solution, you'll need to do your own search.
