### ISSUE TITLE
Installation Issues in PyCharm Anaconda

### ISSUE THREAD

**Issue by sarwatfatimam** [NicolasHug/Surprise#89]
I have installed scikit-surprise through pip. It works fine on Spyder but when I try to run scripts on PyCharm Community Edition 2016.3.3, I get ERROR: ModuleNotFound. I have tried to add the package from Project Interpreter but the scikit-surprise does not appear on the Anaconda python version. Is there a way to install scikit-surprise using anaconda.

**Comment by NicolasHug** [comment]
I'm sorry, this issue is related to PyCharm and not to Surprise. I've zero experience with PyCharm, you'll have more success on SO or other websites.
Anyway, have you tried [this](https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html)?

Nicolas

**Comment by sarwatfatimam** [comment]
Yes, I have looked at it. Also, can you tell me how to install it in conda? Because if I try, conda install scikit-surprise, it gives no package found error. Most packages in anaconda can be installed with this command but not this one.

**Comment by NicolasHug** [comment]
Surprise is only available on PyPI (so with pip), not on the anaconda repositories. You'll find plenty of resources online explaining how to install a package with pip and use it with anaconda.

**Comment by sarwatfatimam** [comment]
Okay. Thankyou.
