### ISSUE TITLE
Reproducing results and tuning parameters

### ISSUE THREAD

**Issue by aman7895** [NicolasHug/Surprise#92]
I have a couple of questions:

+ I ran the code on my dataset and the results seemed to be great! But, how do I reproduce the same results? They change after every run, and using a random_state variable gives an error. 

+ I ran the gridsearch algorithm and found the best parameters, but how can I use them to finetune my algorithm? What's the process to do this in Surprise? 
```
param_grid = {'n_epochs': [5, 10], 'lr_all': [0.002, 0.005],
              'reg_all': [0.4, 0.6]}
grid_search = GridSearch(SVD, param_grid, measures=['RMSE', 'FCP'])
data.split(n_folds=5)

grid_search.evaluate(data)
```

**Comment by NicolasHug** [comment]
You can reproduce results by setting the random seed at the beginning of your program.
I'm not sure what you mean by 'finetune the algorithm' because as I understand it, finetuning is exactly what grid search does.

**Comment by aman7895** [comment]
Could you give me an example how? With `random_seed` as an argument to SVD(), I get an error. 

Yes, it does, but to use the optimized parameters, we need to change the parameters while running the algorithm or does it do that itself? It feels like I need to do it separately, just need suggestion on this.

**Comment by aman7895** [comment]
For the random seed, I have tried:
```
random_seed = 34
trainset = data.build_full_trainset()
algo = SVD(random_seed)
algo.train(trainset)
```
and
```
my_seed = 2
import random
random_seed = random.seed(my_seed)
algo = SVD(random_seed)
```

The result is still different. 
Please help.

**Comment by aman7895** [comment]
I am wondering, why would the results be different? Shouldn't they be the same considering they are the top recommendations? I would think that a few recommendations could change, but none of the recommendations are same after running the algorithm multiple times.

**Comment by NicolasHug** [comment]
The algorithm does not take any seed as parameter.

As SVD uses some random initialization from numpy, you have to define two seeds:

```
import random                                                                     
import numpy as np                                                                
random.seed(0)                                                                    
np.random.seed(0)
```

As for GridSearch, everything you need to know is carefully explained in the doc. Please read it, and come back to me if you still have an issue.

**Comment by aman7895** [comment]
The random seed solution worked! Thanks. I will get back with a better explanation for the GridSearch problem I face.

**Comment by resurrexi** [comment]
Hmm, even after setting the seeds, I'm getting varying results on GridSearchCV. Pasting complete code for reproducibility (or lack of).

```python
!pip install scikit-surprise
from surprise import SVD
from surprise import Dataset, Reader
from surprise.model_selection import GridSearchCV
from surprise import accuracy
import pandas as pd
import numpy as np
import random

# set seed for reproducibility
random.seed(123)
np.random.seed(123)

df = pd.DataFrame({
    'usr': [1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 8, 8, 9, 9, 9, 9, 10, 10],
    'item': [1, 3, 5, 6, 7, 3, 4, 7, 1, 2, 3, 4, 7, 8, 9, 2, 5, 6, 8, 9, 1, 4, 6, 7, 4, 6, 7, 9, 5, 7, 1, 2, 4, 7, 2, 5],
    'rating': [1, 0, 2, 2, 1, 0, 2, 2, 3, 0, 1, 1, 1, 0, 3, 2, 3, 0, 0, 2, 2, 1, 3, 3, 0, 2, 0, 1, 0, 3, 2, 2, 1, 0, 3 ,1]
})

reader = Reader(rating_scale=(0, 3))

# load to surprise; columns need to be in user, item, rating as the order
ratings_data = Dataset.load_from_df(df[['usr', 'item', 'rating']],
                                    reader)

s_grid = GridSearchCV(
    SVD,
    param_grid={
        'n_factors': [2, 3, 4],
        'lr_all': [0.001, 0.01, 0.05, 0.1],
        'reg_all': [0.01, 0.05, 0.1, 0.2]
    },
    measures=['rmse'],
    cv=5,
    n_jobs=4
)

s_grid.fit(ratings_data)
print("Best RMSE: {}".format(s_grid.best_score['rmse']))
print("Best params: {}".format(s_grid.best_params['rmse']))
```

Even after resetting the kernel before each run, I still get varying results. Here's an example of 3 different results. Note, I'm running this on Google Colab so to reset the kernel, you would click "Runtime" in the menu and then click "Reset all runtimes...":

```
Best RMSE: 1.104818528572036
Best params: {'n_factors': 3, 'lr_all': 0.001, 'reg_all': 0.2}

Best RMSE: 1.1047908680817087
Best params: {'n_factors': 4, 'lr_all': 0.001, 'reg_all': 0.05}

Best RMSE: 1.1076146124402966
Best params: {'n_factors': 3, 'lr_all': 0.001, 'reg_all': 0.2}
```

What's interesting is that the 1st and 3rd results generated the same best parameters, but the RMSE scores were different. This leads me to believe that some randomness not controlled by the seed is happening when creating the CV folds.

**Comment by NicolasHug** [comment]
Please see https://github.com/NicolasHug/Surprise/issues/212
