### ISSUE TITLE
Data shuffle problem in parallel GridSearch

### ISSUE THREAD

**Issue by hengji-liu** [NicolasHug/Surprise#95]
#### Description
Thanks for the parallel GridSearch. Just want to tell you there could potentially be a problem.

When you call this parallel method, each CPU core will execute an evaluate(). Unfortunately, if the data is not pre-shuffled, which is the default case, then each evaluate() will shuffle the data differently (Python duplicates data for each core before execution, each core run on its own data copy).

This means different param settings will run on differently split data, which may make the resulting RMSE not comparable. Or in other words, even the same param settings would get different error measure results because data is different on each thread. 

The call chain is: evaluate() -> folds() -> DatasetAutoFolds.raw_folds() -> shuffle happens here

(Encountered the same problem when using my own RandomSearch. So the problem shooting is done for you. Haha. Anyway, it's more like a design issue, so it's up to you how to fix it. Maybe just adding a note in the description would do the job)

(Hope you don't get annoyed by me issuing a lot .... My work is related to this. You library has been a great help! Thanks! )

#### Steps/Code to Reproduce
Just run a GridSearch with the same param setting.

**Comment by NicolasHug** [comment]
Thank you very much for issuing this, I hadn't thought it through. Which makes me realize I should write more conservative tests...

I believe that seeding the RNG in `evaluate` (not `GridSearch.evalutate`) with a given seed would do he job, what do you think of this? Have you managed to fix the issue with `RandomSearch`?


>(Hope you don't get annoyed by me issuing a lot .... My work is related to this. You library has been a great help! Thanks! )

No not at all, on the contrary! It helps bettering the library so keep'em coming! ;)

**Comment by hengji-liu** [comment]
Yes, seeding RNG in the evaluate method does work.
And, what I did in my RandomSearch is shuffling beforehand manully:
```
random.shuffle(data.raw_ratings)
data.split(n_folds=5, shuffle=False)
param_search = RandomSearch(**some_params)
param_search.evaluate(data)
```
So later when each job is dispatched,  shuffling won't be activated again.
