### ISSUE TITLE
AttributeError: class Dataset has no attribute 'global_mean'

### ISSUE THREAD

**Issue by aliasneo1** [NicolasHug/Surprise#97]
While training the algo using dataset loaded from dataframe, it throws an error

reader = Reader(rating_scale=(0,1 ))
data=Dataset.load_from_df(uir_encoded_train_x,reader)
algo.train(Dataset)

AttributeError: class Dataset has no attribute 'global_mean'

**Comment by NicolasHug** [comment]
You need to read the docs.
