### ISSUE TITLE
Issue with conda install

### ISSUE THREAD

**Issue by Gunnvant** [NicolasHug/Surprise#99]
I installed surprise using conda install as described in the documentation, `conda install -c nicolashug scikit-surprise` 

After installation when I imported the surprise, package, I got this error
`ImportError: cannot import name 'similarities'`

Then I removed the package and installed using pip install. Everything worked fine after that. I think there is an issue with conda install. 

I am using anaconda python 3.6 on windows 10.

**Comment by NicolasHug** [comment]
Thanks for reporting this.
Unfortunately I have no windows machine available so that may be hard to fix.

Would you have the complete log of the installation with conda?

**Comment by Gunnvant** [comment]
Nicolas, the install with conda had no issues. I encountered the error, only, when I started a jupyter notebook and imported surprise.

However, I do recall, that when I used conda, the file size that was downloaded was very small compared to when I used pip. Also, I didn't notice any wheel building while installing via conda, but I remember seeing wheel being built when I used pip.

Since, I was able to fix the issue by using pip, so I didn't keep installation log with conda. I will try to uninstall the pip version and see if the problem with conda persists.

Hope that would help.

**Comment by NicolasHug** [comment]
Thanks a lot for the feedback.
I believe this is related to the Cython files not being compiled or something like that. It seems that the  the win x64 installer is shipped with the `similarities.cpython-36m-x86_64-linux-gnu.so`, which obviously can't work for windows: it should compile the similarities.c file to a windows extension.

I have only very minimal knowledge of building conda packages, so if anybody has more insight on this it would be very helpful. I'll leave this issue open in case other users report the same problems.

**Comment by howcouldyouforgetthisusername** [comment]
Nicolas, I think your conclusion is absolutely right -- I tried installing via Anaconda on my Mac, and had a similar experience. Haven't tried installing with pip yet, but I suspect that should fix it. Here's the relevant output:

```
    from .. import similarities as sims
ImportError: dlopen(/anaconda2/lib/python2.7/site-packages/surprise/similarities.so, 2): no suitable image found.  Did find:
	/anaconda2/lib/python2.7/site-packages/surprise/similarities.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/anaconda2/lib/python2.7/site-packages/surprise/similarities.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by NicolasHug** [comment]
Thanks for the feedback.

I checked the other files and all the installers are shipped with the 'original' .so file, so if the installer does not compile the .c files (and it looks like it does not), none of the installations would work except for linux-64 which is my current setup.

I updated the Readme indicating that even with conda, the package should be installed using pip.

I'll try to see how I can make it work eventually. Meanwhile if anybody has a quick recipe for building conda packages that ship Cython code, any help is welcome!

**Comment by NicolasHug** [comment]
Update:

I asked [this question](https://stackoverflow.com/questions/46928961/build-conda-package-upon-installation?noredirect=1#comment80821499_46928961) on SO and the answer is that conda won't build packages (i.e. it won't compile the .c extensions) upon installation, because it wasn't designed to do so. Supporting all platforms would mean building surprise on each platform before uploading the archive on anaconda, which can't be done unless using some CI services. I don't think the pain is worth it though, as even conda users can still use pip.

I think I'll just remove the package from anaconda, until I find the courage to work out a solution with CI.
